#!/usr/bin/env python3
"""Generate numerical-parity fixtures for the M0-04 front-end ops.

M0-04-T07/T13/T16. Emits reference outputs used by the `vokra-parity` tests
(NFR-QL-01, FP32 atol=0.01). Fixtures are committed so CI needs no Python
(cargo test only); this script only reproduces them.

Placement note: the M0-04 tickets proposed `scripts/gen_parity_fixtures.py`.
It lives under `tests/parity/` instead so the fixture generator, fixtures and
tests share one owned directory.

Reference implementations
-------------------------
- ``fft`` / ``window`` : numpy (always available; see parity-requirements.txt).
  numpy.fft is a mature, independent DFT reference and numpy.{hanning,hamming,
  kaiser} are the symmetric-window references.
- ``stft`` / ``istft`` : PyTorch (torch.stft / torch.istft).
- ``mel`` / ``mfcc``  : librosa (librosa.filters.mel, librosa.feature.mfcc).
- ``dct``            : scipy.fft.dct.

If torch / librosa / scipy are not installed, those subcommands print a notice
and are skipped — the corresponding Rust tests are ``#[ignore]`` and only run
once the fixtures exist. Fixture NUMBERS are never invented here.

Fixture format (dependency-free, parsed by tests/parity/src/lib.rs):
    # comment
    key = value
    arr = v0 v1 v2 ...        # whitespace-separated floats

Usage:
    python3 gen_parity_fixtures.py [all|fft|window|stft|mel|mfcc|dct]
"""

from __future__ import annotations

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
FIX = os.path.join(HERE, "fixtures", "m0-04")
SEED = 1234


def _fmt(arr) -> str:
    return " ".join(f"{float(v):.10e}" for v in np.asarray(arr).ravel())


def _write(subdir: str, name: str, fields: dict) -> None:
    d = os.path.join(FIX, subdir)
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, name)
    lines = [f"# generated by gen_parity_fixtures.py (seed={SEED})"]
    for k, v in fields.items():
        lines.append(f"{k} = {v}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"  wrote {os.path.relpath(path, HERE)}")


def gen_fft() -> None:
    print("fft (numpy reference)")
    rng = np.random.default_rng(SEED)
    for n in (8, 12, 16, 64):
        x = rng.standard_normal(n) + 1j * rng.standard_normal(n)
        for norm in ("backward", "ortho", "forward"):
            fwd = np.fft.fft(x, norm=norm)
            _write(
                "fft",
                f"fwd_n{n}_{norm}.txt",
                {
                    "kind": "fft_forward",
                    "n": n,
                    "norm": norm,
                    "in_re": _fmt(x.real),
                    "in_im": _fmt(x.imag),
                    "out_re": _fmt(fwd.real),
                    "out_im": _fmt(fwd.imag),
                },
            )
            inv = np.fft.ifft(x, norm=norm)
            _write(
                "fft",
                f"inv_n{n}_{norm}.txt",
                {
                    "kind": "fft_inverse",
                    "n": n,
                    "norm": norm,
                    "in_re": _fmt(x.real),
                    "in_im": _fmt(x.imag),
                    "out_re": _fmt(inv.real),
                    "out_im": _fmt(inv.imag),
                },
            )
    # Real-input FFT (rfft): n/2+1 bins, backward normalization.
    for n in (8, 16, 64):
        r = rng.standard_normal(n)
        spec = np.fft.rfft(r)
        _write(
            "rfft",
            f"n{n}.txt",
            {
                "kind": "rfft",
                "n": n,
                "in_re": _fmt(r),
                "out_re": _fmt(spec.real),
                "out_im": _fmt(spec.imag),
            },
        )


def gen_window() -> None:
    print("window (numpy reference, symmetric)")
    funcs = {
        "hann": np.hanning,
        "hamming": np.hamming,
    }
    for name, fn in funcs.items():
        for length in (16, 32):
            _write(
                "window",
                f"{name}_{length}.txt",
                {
                    "kind": "window",
                    "window": name,
                    "symmetry": "symmetric",
                    "length": length,
                    "values": _fmt(fn(length)),
                },
            )
    for length in (16, 32):
        for beta in (5.0, 8.6):
            _write(
                "window",
                f"kaiser_{length}_b{beta}.txt",
                {
                    "kind": "window",
                    "window": "kaiser",
                    "beta": beta,
                    "symmetry": "symmetric",
                    "length": length,
                    "values": _fmt(np.kaiser(length, beta)),
                },
            )


def gen_stft() -> None:
    try:
        import torch
    except ImportError:
        print("stft: torch not installed — skipped (Rust test stays #[ignore])")
        return
    print(f"stft (torch {torch.__version__})")
    rng = np.random.default_rng(SEED)
    for n_fft, hop in ((256, 64), (400, 160)):
        sig = rng.standard_normal(4096).astype(np.float32)
        w = torch.hann_window(n_fft, periodic=True)
        spec = torch.stft(
            torch.from_numpy(sig),
            n_fft=n_fft,
            hop_length=hop,
            win_length=n_fft,
            window=w,
            center=True,
            pad_mode="reflect",
            normalized=False,
            return_complex=True,
        )  # [freq, frames]
        spec = spec.transpose(0, 1).contiguous()  # [frames, freq]
        _write(
            "stft",
            f"n{n_fft}_h{hop}.txt",
            {
                "kind": "stft",
                "n_fft": n_fft,
                "hop": hop,
                "frames": spec.shape[0],
                "bins": spec.shape[1],
                "signal": _fmt(sig),
                "out_re": _fmt(spec.real.numpy()),
                "out_im": _fmt(spec.imag.numpy()),
            },
        )


def gen_mel() -> None:
    try:
        import librosa
    except ImportError:
        print("mel: librosa not installed — skipped (Rust test stays #[ignore])")
        return
    print(f"mel (librosa {librosa.__version__})")
    for htk in (False, True):
        fb = librosa.filters.mel(
            sr=16000, n_fft=400, n_mels=80, fmin=0.0, fmax=8000.0, htk=htk, norm="slaney"
        )
        _write(
            "mel",
            f"sr16k_n400_m80_htk{int(htk)}.txt",
            {
                "kind": "mel",
                "sample_rate": 16000,
                "n_fft": 400,
                "n_mels": 80,
                "fmin": 0.0,
                "fmax": 8000.0,
                "htk": int(htk),
                "norm": "slaney",
                "n_freqs": fb.shape[1],
                "weights": _fmt(fb),
            },
        )


def gen_mfcc() -> None:
    try:
        import scipy.fft  # noqa: F401
    except ImportError:
        print("mfcc/dct: scipy not installed — skipped (Rust test stays #[ignore])")
        return
    print("dct (scipy reference)")
    rng = np.random.default_rng(SEED)
    import scipy.fft as sfft

    for n in (8, 16, 40):
        x = rng.standard_normal(n)
        y = sfft.dct(x, type=2, norm="ortho")
        _write(
            "dct",
            f"ortho_n{n}.txt",
            {
                "kind": "dct",
                "n": n,
                "norm": "ortho",
                "in": _fmt(x),
                "out": _fmt(y),
            },
        )


COMMANDS = {
    "fft": gen_fft,
    "window": gen_window,
    "stft": gen_stft,
    "mel": gen_mel,
    "mfcc": gen_mfcc,
    "dct": gen_mfcc,
}


def main() -> int:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    print(f"numpy {np.__version__}; writing fixtures under {os.path.relpath(FIX, HERE)}")
    if cmd == "all":
        gen_fft()
        gen_window()
        gen_stft()
        gen_mel()
        gen_mfcc()
    elif cmd in COMMANDS:
        COMMANDS[cmd]()
    else:
        print(f"unknown command {cmd!r}; use one of all/{'/'.join(COMMANDS)}")
        return 2
    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
