#!/usr/bin/env bash
# VAST/Linux-only SGMSE end-to-end CPU enhancement parity.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VOKRA_ROOT="${VOKRA_ROOT-$(cd "$SCRIPT_DIR/../../.." && pwd)}"
PARITY_PROJECT="$VOKRA_ROOT/tools/parity"
TOOL="$PARITY_PROJECT/sgmse_native_enhancement_parity.py"
REFERENCE_DIR="/workspace/vokra-sgmse-enhancement-reference"
NATIVE_OUTPUT_DIR="/workspace/vokra-sgmse-enhancement-native"
GGUF=""
GGUF_SHA256=""
SELF_TEST=0

log() { printf '[sgmse-native-enhancement-vast] %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 2; }

usage() {
  cat <<'EOF'
usage: run-sgmse-native-enhancement-parity.sh \
  --gguf <absolute-authenticated-gguf> --gguf-sha256 <64-hex-digest> \
  --reference-dir <absolute-verified-enhancement-packet> \
  --native-output-dir <absolute-absent-tmpfs-dir>
       run-sgmse-native-enhancement-parity.sh --self-test

The reference packet must have been generated by the official upstream
ScoreModel.enhance path with captured prior/corrector/predictor noise. The
native test consumes that exact packet; this runner never downloads a model,
generates reference values, converts GGUF, or publishes.
EOF
}

self_test() {
  local fail=0 token
  for token in \
    'VOKRA_PUBLISH_ON_VAST=1' 'VAST/Linux-only' 'x86_64' \
    'sgmse_native_enhancement_parity.py' 'ScoreModel.enhance' \
    'REFERENCE_COMPLETE_NO_UPLOAD' 'CPU_ENHANCEMENT_PARITY_PASS' \
    'prior/corrector/predictor' 'noise_calls.txt' 'NO_UPLOAD' \
    'cargo test --locked --test sgmse_native_enhancement -p vokra-models' \
    '-- --ignored --exact --show-output' 'findmnt' 'tmpfs' \
    'reference packet'; do
    grep -Fq -- "$token" "$0" || { log "self-test FAIL: missing token: $token"; fail=1; }
  done
  if grep -En '(^|[[:space:]])(git[[:space:]]+push|.*upload\.sh|.*publish-one\.sh|--push|--upload)([[:space:]]|$)' "$0" >/dev/null; then
    log 'self-test FAIL: publication command found'
    fail=1
  fi
  if ! UV_CACHE_DIR="$(printenv UV_CACHE_DIR || printf /tmp/vokra-sgmse-uv-cache)" \
    uv run --frozen --no-sync --project "$PARITY_PROJECT" --python 3.12 python \
    "$TOOL" --self-test >/dev/null; then
    log 'self-test FAIL: enhancement tool self-test failed'
    fail=1
  fi
  if "$0" --self-test --gguf /tmp/not-accepted >/dev/null 2>&1; then
    log 'self-test FAIL: extra argument accepted with --self-test'
    fail=1
  fi
  if "$0" --unknown-flag >/dev/null 2>&1; then
    log 'self-test FAIL: unknown argument accepted'
    fail=1
  fi
  (( fail == 0 )) || return 1
  log 'self-test PASS'
}

while (($#)); do
  case "$1" in
    --self-test) (( SELF_TEST == 0 )) || die 'duplicate --self-test'; SELF_TEST=1; shift ;;
    --gguf) (($# >= 2)) || die '--gguf requires a path'; GGUF="$2"; shift 2 ;;
    --gguf-sha256) (($# >= 2)) || die '--gguf-sha256 requires a digest'; GGUF_SHA256="$2"; shift 2 ;;
    --reference-dir) (($# >= 2)) || die '--reference-dir requires a path'; REFERENCE_DIR="$2"; shift 2 ;;
    --native-output-dir) (($# >= 2)) || die '--native-output-dir requires a path'; NATIVE_OUTPUT_DIR="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done
if (( SELF_TEST )); then
  [[ -z "$GGUF$GGUF_SHA256" && "$REFERENCE_DIR" == "/workspace/vokra-sgmse-enhancement-reference" && "$NATIVE_OUTPUT_DIR" == "/workspace/vokra-sgmse-enhancement-native" ]] || die '--self-test accepts no other arguments'
  self_test
  exit 0
fi

[[ -n "$GGUF" && -n "$GGUF_SHA256" ]] || { usage >&2; exit 1; }
[[ "$(uname -s)" == Linux ]] || die 'SGMSE enhancement parity is VAST/Linux-only'
[[ "$(uname -m)" == x86_64 ]] || die 'SGMSE enhancement parity requires x86_64 VAST'
[[ "$(printenv VOKRA_PUBLISH_ON_VAST || true)" == 1 ]] || die 'VOKRA_PUBLISH_ON_VAST=1 is absent'
[[ -f "$VOKRA_ROOT/Cargo.toml" && -d "$VOKRA_ROOT/.git" ]] || die 'not a Vokra checkout'
[[ -z "$(git -C "$VOKRA_ROOT" status --porcelain --untracked-files=all)" ]] || die 'VAST Vokra checkout must be clean'
[[ -f "$PARITY_PROJECT/pyproject.toml" && -f "$PARITY_PROJECT/uv.lock" && -f "$TOOL" ]] || die 'parity project/tool is missing'
[[ "$GGUF" == /* && "$REFERENCE_DIR" == /* && "$NATIVE_OUTPUT_DIR" == /* ]] || die 'all paths must be absolute'
[[ "$GGUF_SHA256" =~ ^[0-9a-f]{64}$ ]] || die '--gguf-sha256 must be lowercase 64-hex'
[[ -f "$GGUF" && ! -L "$GGUF" ]] || die 'GGUF is missing or symlinked'
[[ -d "$REFERENCE_DIR" && ! -L "$REFERENCE_DIR" ]] || die 'reference packet is missing or symlinked'
[[ ! -e "$NATIVE_OUTPUT_DIR" && ! -L "$NATIVE_OUTPUT_DIR" ]] || die 'native output must be absent'
native_parent="$(dirname "$NATIVE_OUTPUT_DIR")"
[[ -d "$native_parent" && ! -L "$native_parent" ]] || die 'native output parent must be real'
[[ "$(findmnt -T "$native_parent" -no FSTYPE 2>/dev/null || true)" == tmpfs ]] || die 'native output parent must be tmpfs'
command -v sha256sum >/dev/null 2>&1 || die 'sha256sum is missing'
command -v awk >/dev/null 2>&1 || die 'awk is missing'
command -v cargo >/dev/null 2>&1 || die 'cargo is missing'
command -v uv >/dev/null 2>&1 || die 'uv is missing'

# Independent packet verification is the first data operation.
UV_CACHE_DIR="$(printenv UV_CACHE_DIR || printf /tmp/vokra-sgmse-uv-cache)" \
  uv run --frozen --no-sync --project "$PARITY_PROJECT" --python 3.12 python \
  "$TOOL" --verify-reference --reference-dir "$REFERENCE_DIR"
actual_gguf_sha256="$(sha256sum "$GGUF" | awk '{print $1}')"
[[ "$actual_gguf_sha256" == "$GGUF_SHA256" ]] || die "GGUF SHA-256 mismatch: got $actual_gguf_sha256"

export CARGO_BUILD_JOBS="$(printenv CARGO_BUILD_JOBS || printf 1)"
tmpdir="$(printenv TMPDIR || printf /tmp)"
native_log="$(mktemp "$tmpdir/vokra-sgmse-native-enhancement.XXXXXX")"
trap 'rm -f -- "$native_log"' EXIT
VOKRA_SGMSE_GGUF="$GGUF" \
VOKRA_SGMSE_GGUF_SHA256="$GGUF_SHA256" \
VOKRA_SGMSE_REFERENCE_DIR="$REFERENCE_DIR" \
VOKRA_SGMSE_NATIVE_OUTPUT_DIR="$NATIVE_OUTPUT_DIR" \
VOKRA_PUBLISH_ON_VAST=1 \
  cargo test --locked --test sgmse_native_enhancement -p vokra-models \
    -- --ignored --exact --show-output 2>&1 | tee "$native_log"
[[ "$(grep -Fxc 'test sgmse_native_enhancement_matches_official_reference ... ok' "$native_log" || true)" == 1 ]] || die 'native enhancement test did not pass exactly once'
[[ -f "$NATIVE_OUTPUT_DIR/enhanced_pcm.f32" ]] || die 'native enhancement output is missing'

UV_CACHE_DIR="$(printenv UV_CACHE_DIR || printf /tmp/vokra-sgmse-uv-cache)" \
  uv run --frozen --no-sync --project "$PARITY_PROJECT" --python 3.12 python \
  "$TOOL" --compare --reference-dir "$REFERENCE_DIR" --native-dir "$NATIVE_OUTPUT_DIR"
log "CPU enhancement parity complete; no upload performed; destroy the disposable VAST instance after evidence transfer"
