//! CSM's staged Llama-3.2 text-tokenizer route.
//!
//! The fixed CSM snapshot carries a `tokenizer.json` generated by the
//! HuggingFace `tokenizers` library. The staged parser can inspect that JSON
//! blob with Vokra's dependency-free JSON reader and implements a candidate
//! subset: Llama byte-level BPE, its Llama regex pre-tokenizer, and BOS/EOS
//! template processing. It is not accepted as source-exact until the fixed
//! snapshot's canonical ID/value parity packet has passed; there is
//! deliberately no Meta tokenizer package dependency and no placeholder
//! byte-token fallback in the production path.
//!
//! `FixtureByteTokenizer` remains an explicit, test-only convenience for
//! synthesized weights. It is never selected by a GGUF loader.

use std::collections::{HashMap, HashSet};

use vokra_core::gguf::{GgufFile, GgufMetadataValue};
use vokra_core::json::JsonValue;
use vokra_core::{Result, VokraError};

/// GGUF key carrying the authenticated raw `tokenizer.json` blob.
pub const KEY_TOKENIZER_MODEL: &str = "vokra.tokenizer.model";

/// The exact ordered Llama-3 pre-tokenizer expression authenticated by the
/// CSM snapshot.  Keeping this as a literal (rather than checking a few
/// substrings) prevents a subtly different regex topology from being treated
/// as source-compatible by the dependency-free scanner.
const LLAMA3_SPLIT_REGEX: &str = r"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+(?!\S)|\s+";

/// Text → token ids for the CSM text slots.
pub trait CsmTextTokenizer: Send + Sync {
    /// Encodes text with the tokenizer's authenticated post-processing.
    fn encode(&self, text: &str) -> Result<Vec<u32>>;

    /// The vocabulary bound every returned id respects.
    fn vocab_size(&self) -> usize;
}

#[derive(Debug)]
struct LlamaBpe {
    vocab: HashMap<String, u32>,
    merges: HashMap<(String, String), usize>,
    bos_id: u32,
    eos_id: u32,
    byte_fallback: bool,
    split_regex: bool,
}

impl LlamaBpe {
    fn parse(blob: &[u8], vocab_size: usize) -> Result<Self> {
        if blob.len() > 64 * 1024 * 1024 {
            return Err(VokraError::ModelLoad(
                "csm tokenizer: tokenizer.json exceeds the bounded 64 MiB limit".into(),
            ));
        }
        let root = vokra_core::json::parse(blob).map_err(|e| {
            VokraError::ModelLoad(format!("csm tokenizer: invalid tokenizer.json: {e}"))
        })?;
        reject_duplicate_keys(&root)?;
        let model = object_field(&root, "model")?;
        if string_field(model, "type")? != "BPE" {
            return Err(VokraError::ModelLoad(
                "csm tokenizer: tokenizer.json model.type must be BPE".into(),
            ));
        }
        let model_obj = model.as_object().ok_or_else(|| {
            VokraError::ModelLoad("csm tokenizer: model must be an object".into())
        })?;
        let vocab_value = object_value(model_obj, "vocab")
            .ok_or_else(|| VokraError::ModelLoad("csm tokenizer: BPE vocab is missing".into()))?;
        let vocab_entries = vocab_value.as_object().ok_or_else(|| {
            VokraError::ModelLoad("csm tokenizer: BPE vocab must be an object".into())
        })?;
        if vocab_entries.is_empty() {
            return Err(VokraError::ModelLoad(
                "csm tokenizer: BPE vocab is empty".into(),
            ));
        }
        let mut vocab = HashMap::with_capacity(vocab_entries.len());
        for (token, id) in vocab_entries {
            let id = id.as_u64().ok_or_else(|| {
                VokraError::ModelLoad(format!(
                    "csm tokenizer: vocab id for {token:?} is not a non-negative integer"
                ))
            })?;
            if id >= vocab_size as u64 {
                return Err(VokraError::ModelLoad(format!(
                    "csm tokenizer: vocab id {id} for {token:?} >= configured vocab {vocab_size}"
                )));
            }
            vocab.insert(token.clone(), id as u32);
        }

        let merges_value = object_value(model_obj, "merges")
            .ok_or_else(|| VokraError::ModelLoad("csm tokenizer: BPE merges are missing".into()))?;
        let merge_entries = merges_value.as_array().ok_or_else(|| {
            VokraError::ModelLoad("csm tokenizer: BPE merges must be an array".into())
        })?;
        let mut merges = HashMap::with_capacity(merge_entries.len());
        for (rank, merge) in merge_entries.iter().enumerate() {
            let (left, right) = match merge {
                JsonValue::Str(s) => {
                    let mut parts = s.splitn(2, ' ');
                    let left = parts.next().unwrap_or_default();
                    let right = parts.next().unwrap_or_default();
                    if left.is_empty() || right.is_empty() {
                        return Err(VokraError::ModelLoad(format!(
                            "csm tokenizer: malformed BPE merge at rank {rank}"
                        )));
                    }
                    (left.to_owned(), right.to_owned())
                }
                JsonValue::Array(items) if items.len() == 2 => {
                    let left = items[0].as_str().ok_or_else(|| {
                        VokraError::ModelLoad(format!(
                            "csm tokenizer: non-string left BPE merge at rank {rank}"
                        ))
                    })?;
                    let right = items[1].as_str().ok_or_else(|| {
                        VokraError::ModelLoad(format!(
                            "csm tokenizer: non-string right BPE merge at rank {rank}"
                        ))
                    })?;
                    (left.to_owned(), right.to_owned())
                }
                _ => {
                    return Err(VokraError::ModelLoad(format!(
                        "csm tokenizer: malformed BPE merge at rank {rank}"
                    )));
                }
            };
            merges.entry((left, right)).or_insert(rank);
        }
        if merges.is_empty() {
            return Err(VokraError::ModelLoad(
                "csm tokenizer: BPE merges are empty".into(),
            ));
        }

        let added = object_field(&root, "added_tokens")?;
        let mut bos_id = None;
        let mut eos_id = None;
        let mut added_contents = HashSet::new();
        let mut added_ids = HashSet::new();
        for item in added.as_array().ok_or_else(|| {
            VokraError::ModelLoad("csm tokenizer: added_tokens must be an array".into())
        })? {
            let obj = item.as_object().ok_or_else(|| {
                VokraError::ModelLoad("csm tokenizer: added token must be an object".into())
            })?;
            let content = object_value(obj, "content")
                .and_then(JsonValue::as_str)
                .ok_or_else(|| {
                    VokraError::ModelLoad("csm tokenizer: added token content missing".into())
                })?;
            let id = object_value(obj, "id")
                .and_then(JsonValue::as_u64)
                .ok_or_else(|| {
                    VokraError::ModelLoad("csm tokenizer: added token id missing".into())
                })?;
            if id >= vocab_size as u64 {
                return Err(VokraError::ModelLoad(format!(
                    "csm tokenizer: added token id {id} >= configured vocab {vocab_size}"
                )));
            }
            if !added_contents.insert(content) || !added_ids.insert(id) {
                return Err(VokraError::ModelLoad(
                    "csm tokenizer: added_tokens contains a duplicate content or ID".into(),
                ));
            }
            match content {
                "<|begin_of_text|>" => bos_id = Some(id as u32),
                "<|end_of_text|>" => eos_id = Some(id as u32),
                _ => {}
            }
        }
        let bos_id = bos_id.ok_or_else(|| {
            VokraError::ModelLoad(
                "csm tokenizer: authenticated tokenizer has no <|begin_of_text|> token".into(),
            )
        })?;
        let eos_id = eos_id.ok_or_else(|| {
            VokraError::ModelLoad(
                "csm tokenizer: authenticated tokenizer has no <|end_of_text|> token".into(),
            )
        })?;

        let pre_tokenizer = object_field(&root, "pre_tokenizer")?;
        let split_regex = validate_pre_tokenizer(pre_tokenizer)?;
        validate_post_processor(&root, bos_id, eos_id)?;
        let byte_fallback = object_value(model_obj, "byte_fallback")
            .and_then(|v| match v {
                JsonValue::Bool(value) => Some(*value),
                _ => None,
            })
            .unwrap_or(false);
        if !byte_fallback {
            return Err(VokraError::ModelLoad(
                "csm tokenizer: fixed Llama BPE must enable byte_fallback".into(),
            ));
        }
        Ok(Self {
            vocab,
            merges,
            bos_id,
            eos_id,
            byte_fallback,
            split_regex,
        })
    }

    fn encode(&self, text: &str) -> Result<Vec<u32>> {
        if !self.split_regex {
            return Err(VokraError::ModelLoad(
                "csm tokenizer: unsupported pre-tokenizer topology".into(),
            ));
        }
        let mut ids = vec![self.bos_id];
        for piece in split_llama_regex(text)? {
            let mapped = bytes_to_unicode(&piece);
            let mut symbols: Vec<String> = mapped.chars().map(|c| c.to_string()).collect();
            if symbols.is_empty() {
                continue;
            }
            while symbols.len() > 1 {
                let mut best: Option<(String, String, usize)> = None;
                for index in 0..symbols.len() - 1 {
                    if let Some(&rank) = self
                        .merges
                        .get(&(symbols[index].clone(), symbols[index + 1].clone()))
                    {
                        if best
                            .as_ref()
                            .is_none_or(|(_, _, old_rank)| rank < *old_rank)
                        {
                            best = Some((symbols[index].clone(), symbols[index + 1].clone(), rank));
                        }
                    }
                }
                let Some((left, right, _)) = best else { break };
                merge_all_pair(&mut symbols, &left, &right);
            }
            for symbol in symbols {
                if let Some(&id) = self.vocab.get(&symbol) {
                    ids.push(id);
                } else if self.byte_fallback {
                    // A merged symbol is a visible-Unicode string. Its
                    // UTF-8 bytes are not the original input bytes, so a
                    // missing merged symbol is an authenticated-topology
                    // failure rather than a license to invent IDs.
                    return Err(VokraError::ModelLoad(format!(
                        "csm tokenizer: final BPE symbol {symbol:?} is absent"
                    )));
                } else {
                    return Err(VokraError::ModelLoad(format!(
                        "csm tokenizer: final BPE symbol {symbol:?} is absent"
                    )));
                }
            }
        }
        ids.push(self.eos_id);
        Ok(ids)
    }
}

/// GGUF-embedded candidate Llama-3.2 tokenizer parser.
///
/// This remains staged/unaccepted: `from_gguf` validates structure only. The
/// public CSM loader does not call it until snapshot revision/blob and
/// canonical ID parity evidence are reviewed.
pub struct GgufCsmTokenizer {
    bytes: Vec<u8>,
    vocab_size: usize,
    tokenizer: LlamaBpe,
}

impl std::fmt::Debug for GgufCsmTokenizer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GgufCsmTokenizer")
            .field("bytes.len", &self.bytes.len())
            .field("vocab_size", &self.vocab_size)
            .finish_non_exhaustive()
    }
}

impl GgufCsmTokenizer {
    /// Reads and authenticates the embedded `tokenizer.json`.
    pub fn from_gguf(file: &GgufFile, vocab_size: usize) -> Result<Self> {
        if vocab_size == 0 {
            return Err(VokraError::InvalidArgument(
                "csm tokenizer: vocab_size must be > 0".into(),
            ));
        }
        let arr = match file.get(KEY_TOKENIZER_MODEL) {
            Some(GgufMetadataValue::Array(a)) => a,
            Some(other) => {
                return Err(VokraError::ModelLoad(format!(
                    "csm tokenizer: `{KEY_TOKENIZER_MODEL}` is not an array (got {:?})",
                    other.value_type()
                )));
            }
            None => {
                return Err(VokraError::ModelLoad(format!(
                    "csm tokenizer: `{KEY_TOKENIZER_MODEL}` missing — complete authenticated tokenizer.json is required"
                )));
            }
        };
        let mut bytes = Vec::with_capacity(arr.values.len());
        for value in &arr.values {
            match value {
                GgufMetadataValue::U8(byte) => bytes.push(*byte),
                other => {
                    return Err(VokraError::ModelLoad(format!(
                        "csm tokenizer: `{KEY_TOKENIZER_MODEL}` has non-U8 element ({:?})",
                        other.value_type()
                    )));
                }
            }
        }
        if bytes.is_empty() {
            return Err(VokraError::ModelLoad(
                "csm tokenizer: embedded tokenizer.json is empty".into(),
            ));
        }
        let tokenizer = LlamaBpe::parse(&bytes, vocab_size)?;
        Ok(Self {
            bytes,
            vocab_size,
            tokenizer,
        })
    }

    /// Raw authenticated JSON, for parity evidence and provenance checks.
    #[must_use]
    pub fn raw_bytes(&self) -> &[u8] {
        &self.bytes
    }
}

impl CsmTextTokenizer for GgufCsmTokenizer {
    fn encode(&self, text: &str) -> Result<Vec<u32>> {
        self.tokenizer.encode(text)
    }

    fn vocab_size(&self) -> usize {
        self.vocab_size
    }
}

/// Explicit fixture tokenizer: UTF-8 bytes → `byte % vocab_size`.
#[derive(Debug, Clone)]
pub struct FixtureByteTokenizer {
    vocab_size: usize,
}

impl FixtureByteTokenizer {
    /// Builds the fixture tokenizer for a bounded id space.
    pub fn new(vocab_size: usize) -> Result<Self> {
        if vocab_size == 0 {
            return Err(VokraError::InvalidArgument(
                "csm fixture tokenizer: vocab_size must be > 0".into(),
            ));
        }
        Ok(Self { vocab_size })
    }
}

impl CsmTextTokenizer for FixtureByteTokenizer {
    fn encode(&self, text: &str) -> Result<Vec<u32>> {
        if text.is_empty() {
            return Err(VokraError::InvalidArgument(
                "csm fixture tokenizer: text must be non-empty".into(),
            ));
        }
        Ok(text
            .bytes()
            .map(|byte| u32::from(byte) % self.vocab_size as u32)
            .collect())
    }

    fn vocab_size(&self) -> usize {
        self.vocab_size
    }
}

fn object_field<'a>(root: &'a JsonValue, key: &str) -> Result<&'a JsonValue> {
    root.get(key).ok_or_else(|| {
        VokraError::ModelLoad(format!(
            "csm tokenizer: tokenizer.json field `{key}` missing"
        ))
    })
}

fn reject_duplicate_keys(value: &JsonValue) -> Result<()> {
    match value {
        JsonValue::Object(entries) => {
            let mut keys = HashSet::with_capacity(entries.len());
            for (key, child) in entries {
                if !keys.insert(key) {
                    return Err(VokraError::ModelLoad(format!(
                        "csm tokenizer: duplicate JSON object key {key:?}"
                    )));
                }
                reject_duplicate_keys(child)?;
            }
        }
        JsonValue::Array(items) => {
            for child in items {
                reject_duplicate_keys(child)?;
            }
        }
        _ => {}
    }
    Ok(())
}

fn object_value<'a>(object: &'a [(String, JsonValue)], key: &str) -> Option<&'a JsonValue> {
    object
        .iter()
        .find(|(name, _)| name == key)
        .map(|(_, value)| value)
}

fn string_field(root: &JsonValue, key: &str) -> Result<&str> {
    object_field(root, key)?.as_str().ok_or_else(|| {
        VokraError::ModelLoad(format!("csm tokenizer: field `{key}` must be a string"))
    })
}

fn validate_pre_tokenizer(value: &JsonValue) -> Result<bool> {
    let object = value.as_object().ok_or_else(|| {
        VokraError::ModelLoad("csm tokenizer: pre_tokenizer must be an object".into())
    })?;
    let kind = object_value(object, "type")
        .and_then(JsonValue::as_str)
        .unwrap_or("");
    if kind == "ByteLevel" {
        return Err(VokraError::ModelLoad(
            "csm tokenizer: fixed Llama pre_tokenizer requires Sequence(Split, ByteLevel)".into(),
        ));
    }
    if kind != "Sequence" {
        return Err(VokraError::ModelLoad(format!(
            "csm tokenizer: unsupported pre_tokenizer type {kind:?}"
        )));
    }
    let parts = object_value(object, "pretokenizers")
        .or_else(|| object_value(object, "pre_tokenizers"))
        .and_then(JsonValue::as_array)
        .ok_or_else(|| {
            VokraError::ModelLoad("csm tokenizer: pre_tokenizer Sequence has no members".into())
        })?;
    let mut split = false;
    let mut byte_level = false;
    let mut split_index = None;
    let mut byte_level_index = None;
    for (index, part) in parts.iter().enumerate() {
        let part_object = part.as_object().ok_or_else(|| {
            VokraError::ModelLoad("csm tokenizer: pre_tokenizer member is not an object".into())
        })?;
        match object_value(part_object, "type").and_then(JsonValue::as_str) {
            Some("ByteLevel") => {
                validate_byte_level_attributes(part_object)?;
                byte_level = true;
                byte_level_index = Some(index);
            }
            Some("Split") => {
                let pattern = object_value(part_object, "pattern").ok_or_else(|| {
                    VokraError::ModelLoad(
                        "csm tokenizer: Split pre-tokenizer has no pattern".into(),
                    )
                })?;
                let pattern = pattern.as_object().ok_or_else(|| {
                    VokraError::ModelLoad("csm tokenizer: Split pattern is not an object".into())
                })?;
                let regex = object_value(pattern, "Regex")
                    .and_then(JsonValue::as_str)
                    .unwrap_or("");
                // A different expression is rejected rather than
                // approximated. In particular, the optional prefix in the
                // second alternative is semantically significant.
                if regex == LLAMA3_SPLIT_REGEX {
                    split = true;
                    split_index = Some(index);
                } else {
                    return Err(VokraError::ModelLoad(
                        "csm tokenizer: Split regex is not the authenticated Llama-3 pattern"
                            .into(),
                    ));
                }
            }
            Some(other) => {
                return Err(VokraError::ModelLoad(format!(
                    "csm tokenizer: unsupported pre-tokenizer member {other:?}"
                )));
            }
            None => {
                return Err(VokraError::ModelLoad(
                    "csm tokenizer: pre-tokenizer member type missing".into(),
                ));
            }
        }
    }
    if !split || !byte_level || split_index != Some(0) || byte_level_index != Some(1) {
        return Err(VokraError::ModelLoad(
            "csm tokenizer: Llama pre-tokenizer must contain Split + ByteLevel".into(),
        ));
    }
    Ok(true)
}

fn validate_byte_level_attributes(object: &[(String, JsonValue)]) -> Result<()> {
    // These are the complete tokenizers ByteLevel attributes. Unknown keys or
    // omitted fields are rejected so a future topology cannot be silently
    // ignored by this zero-dependency implementation.
    let expected = ["type", "add_prefix_space", "trim_offsets", "use_regex"];
    if object.len() != expected.len()
        || expected
            .iter()
            .any(|key| !object.iter().any(|(actual, _)| actual == key))
    {
        return Err(VokraError::ModelLoad(
            "csm tokenizer: ByteLevel must expose its complete fixed field set".into(),
        ));
    }
    for (key, value) in object {
        if !matches!(
            key.as_str(),
            "type" | "add_prefix_space" | "trim_offsets" | "use_regex"
        ) {
            return Err(VokraError::ModelLoad(format!(
                "csm tokenizer: unsupported ByteLevel attribute {key:?}"
            )));
        }
        if key != "type" && !matches!(value, JsonValue::Bool(_)) {
            return Err(VokraError::ModelLoad(format!(
                "csm tokenizer: ByteLevel attribute {key:?} must be boolean"
            )));
        }
    }
    // Prefix insertion changes leading-whitespace token IDs and is not part
    // of the fixed Llama-3 contract handled by split_llama_regex.
    if object_value(object, "add_prefix_space") != Some(&JsonValue::Bool(false))
        || object_value(object, "trim_offsets") != Some(&JsonValue::Bool(true))
        || object_value(object, "use_regex") != Some(&JsonValue::Bool(true))
    {
        return Err(VokraError::ModelLoad(
            "csm tokenizer: ByteLevel values differ from the fixed Llama contract".into(),
        ));
    }
    Ok(())
}

fn validate_post_processor(root: &JsonValue, bos_id: u32, eos_id: u32) -> Result<()> {
    let processor = object_field(root, "post_processor")?;
    let object = processor.as_object().ok_or_else(|| {
        VokraError::ModelLoad("csm tokenizer: post_processor must be an object".into())
    })?;
    if object_value(object, "type").and_then(JsonValue::as_str) != Some("TemplateProcessing") {
        return Err(VokraError::ModelLoad(
            "csm tokenizer: post_processor must be TemplateProcessing".into(),
        ));
    }
    let single = object_value(object, "single")
        .and_then(JsonValue::as_array)
        .ok_or_else(|| {
            VokraError::ModelLoad("csm tokenizer: TemplateProcessing.single missing".into())
        })?;
    if single.len() != 3
        || post_processor_atom(&single[0], bos_id, eos_id) != Some(("bos", bos_id))
        || post_processor_atom(&single[single.len() - 1], bos_id, eos_id) != Some(("eos", eos_id))
        || post_processor_atom(&single[1], bos_id, eos_id) != Some(("sequence", 0))
    {
        return Err(VokraError::ModelLoad(
            "csm tokenizer: post_processor must be BOS + sequence + EOS".into(),
        ));
    }
    let special = object_value(object, "special_tokens")
        .and_then(JsonValue::as_object)
        .ok_or_else(|| {
            VokraError::ModelLoad("csm tokenizer: post_processor.special_tokens missing".into())
        })?;
    for (name, expected_id) in [("<|begin_of_text|>", bos_id), ("<|end_of_text|>", eos_id)] {
        let value = object_value(special, name).ok_or_else(|| {
            VokraError::ModelLoad(
                "csm tokenizer: post_processor special-token map is incomplete".into(),
            )
        })?;
        let token = value.as_object().ok_or_else(|| {
            VokraError::ModelLoad(
                "csm tokenizer: post_processor special-token entry must be an object".into(),
            )
        })?;
        if object_value(token, "id").and_then(JsonValue::as_str) != Some(name)
            || object_value(token, "ids")
                .and_then(JsonValue::as_array)
                .and_then(|ids| (ids.len() == 1).then(|| ids[0].as_u64()))
                .flatten()
                != Some(u64::from(expected_id))
        {
            return Err(VokraError::ModelLoad(format!(
                "csm tokenizer: post_processor special-token entry {name:?} is not bound to id {expected_id}"
            )));
        }
    }
    Ok(())
}

fn post_processor_atom(value: &JsonValue, bos_id: u32, eos_id: u32) -> Option<(&'static str, u32)> {
    if let Some(string) = value.as_str() {
        return match string {
            "<|begin_of_text|>" => Some(("bos", bos_id)),
            "<|end_of_text|>" => Some(("eos", eos_id)),
            "A" => Some(("sequence", 0)),
            _ => None,
        };
    }
    let object = value.as_object()?;
    if let Some(token) = object_value(object, "SpecialToken") {
        let token = token.as_object()?;
        let id = object_value(token, "ids")
            .and_then(JsonValue::as_array)
            .and_then(|ids| ids.first());
        let name = object_value(token, "id").and_then(JsonValue::as_str)?;
        let id = id
            .and_then(JsonValue::as_u64)
            .map(|id| id as u32)
            .or_else(|| match name {
                "<|begin_of_text|>" => Some(bos_id),
                "<|end_of_text|>" => Some(eos_id),
                _ => None,
            })?;
        return match name {
            "<|begin_of_text|>" => Some(("bos", id)),
            "<|end_of_text|>" => Some(("eos", id)),
            _ => None,
        };
    }
    let sequence = object_value(object, "Sequence")?.as_object()?;
    (object_value(sequence, "id").and_then(JsonValue::as_str) == Some("A"))
        .then_some(("sequence", 0))
}

/// GPT-2/ByteLevel's deterministic byte-to-visible-Unicode mapping.
fn bytes_to_unicode(input: &str) -> String {
    input.bytes().map(bytes_to_unicode_byte).collect()
}

fn bytes_to_unicode_byte(byte: u8) -> char {
    const DIRECT: &[(u8, u8)] = &[(b'!', b'~'), (0xA1, 0xAC), (0xAE, 0xFF)];
    if DIRECT.iter().any(|&(lo, hi)| (lo..=hi).contains(&byte)) {
        return byte as char;
    }
    let mut offset = 0u32;
    for candidate in 0..=u8::MAX {
        if DIRECT
            .iter()
            .any(|&(lo, hi)| (lo..=hi).contains(&candidate))
        {
            continue;
        }
        if candidate == byte {
            return char::from_u32(256 + offset).expect("byte encoder code point");
        }
        offset += 1;
    }
    unreachable!("all byte values are covered")
}

/// Scanner for the fixed Llama-3 regex, mirroring its ordered alternatives
/// without introducing a regex dependency into the runtime.
fn split_llama_regex(input: &str) -> Result<Vec<String>> {
    let mut out = Vec::new();
    let mut offset = 0;
    while offset < input.len() {
        let rest = &input[offset..];
        if let Some(len) = contraction_len(rest) {
            out.push(rest[..len].to_owned());
            offset += len;
            continue;
        }
        let chars: Vec<(usize, char)> = rest.char_indices().collect();
        let first = chars[0].1;
        let first_class = llama_class(first)?;
        if first_class == LlamaClass::Letter {
            let end = chars
                .iter()
                .take_while(|(_, c)| llama_class(*c).is_ok_and(|class| class == LlamaClass::Letter))
                .last()
                .map_or(first.len_utf8(), |(index, c)| *index + c.len_utf8());
            out.push(rest[..end].to_owned());
            offset += end;
            continue;
        }
        // `[^\r\n\p{L}\p{N}]?\p{L}+` permits one optional prefix
        // character, including an ASCII space.  Excluding `' '` here emits
        // a separate whitespace token and changes Llama-3 token IDs.
        if first_class != LlamaClass::Number && !matches!(first, '\r' | '\n') {
            if let Some((index, c)) = chars.get(1).copied() {
                if llama_class(c)? == LlamaClass::Letter {
                    let end = chars
                        .iter()
                        .skip(1)
                        .take_while(|(_, c)| {
                            llama_class(*c).is_ok_and(|class| class == LlamaClass::Letter)
                        })
                        .last()
                        .map_or(index + c.len_utf8(), |(pos, c)| *pos + c.len_utf8());
                    out.push(rest[..end].to_owned());
                    offset += end;
                    continue;
                }
            }
        }
        if first_class == LlamaClass::Number {
            let end = chars
                .iter()
                .take(3)
                .take_while(|(_, c)| llama_class(*c).is_ok_and(|class| class == LlamaClass::Number))
                .last()
                .map_or(first.len_utf8(), |(index, c)| *index + c.len_utf8());
            out.push(rest[..end].to_owned());
            offset += end;
            continue;
        }
        let mut punctuation_start = 0;
        if first == ' '
            && chars
                .get(1)
                .is_some_and(|(_, c)| llama_class(*c).ok() != Some(LlamaClass::Whitespace))
        {
            punctuation_start = first.len_utf8();
        }
        let mut end = punctuation_start;
        while end < rest.len() {
            let c = rest[end..].chars().next().expect("char boundary");
            let class = llama_class(c)?;
            if matches!(
                class,
                LlamaClass::Whitespace | LlamaClass::Letter | LlamaClass::Number
            ) {
                break;
            }
            end += c.len_utf8();
        }
        while end < rest.len() && matches!(rest[end..].chars().next(), Some('\r' | '\n')) {
            end += rest[end..].chars().next().expect("newline").len_utf8();
        }
        if end > punctuation_start {
            out.push(rest[..end].to_owned());
            offset += end;
            continue;
        }
        // `\s*[\r\n]+` is ordered before the generic whitespace arms. Keep
        // leading horizontal whitespace with a newline run, but do not
        // swallow whitespace that follows the newline (the next match owns
        // that suffix).
        if first_class == LlamaClass::Whitespace {
            let mut end = 0;
            while end < rest.len() {
                let c = rest[end..].chars().next().expect("char boundary");
                if matches!(c, '\r' | '\n') {
                    break;
                }
                if llama_class(c)? != LlamaClass::Whitespace {
                    break;
                }
                end += c.len_utf8();
            }
            let newline_start = end;
            while end < rest.len() {
                let c = rest[end..].chars().next().expect("char boundary");
                if !matches!(c, '\r' | '\n') {
                    break;
                }
                end += c.len_utf8();
            }
            if end > newline_start {
                out.push(rest[..end].to_owned());
                offset += end;
                continue;
            }
        }
        if first_class == LlamaClass::Whitespace {
            let mut run_end = 0;
            let mut widths = Vec::new();
            while run_end < rest.len() {
                let c = rest[run_end..].chars().next().expect("char boundary");
                if llama_class(c)? != LlamaClass::Whitespace {
                    break;
                }
                let width = c.len_utf8();
                widths.push(width);
                run_end += width;
            }
            // `\s+(?!\S)` backtracks one whitespace character when the run
            // is followed by a non-whitespace character. This leaves the
            // final optional prefix available to the following letter match:
            // `  hello` => `" "`, `" hello"`.
            let end = if run_end == rest.len() {
                run_end
            } else if widths.len() > 1 {
                run_end - widths[widths.len() - 1]
            } else {
                run_end
            };
            out.push(rest[..end].to_owned());
            offset += end;
            continue;
        }
        let len = first.len_utf8();
        out.push(rest[..len].to_owned());
        offset += len;
    }
    Ok(out)
}

fn merge_all_pair(symbols: &mut Vec<String>, left: &str, right: &str) {
    let mut merged = Vec::with_capacity(symbols.len());
    let mut index = 0;
    while index < symbols.len() {
        if index + 1 < symbols.len() && symbols[index] == left && symbols[index + 1] == right {
            let mut value = symbols[index].clone();
            value.push_str(&symbols[index + 1]);
            merged.push(value);
            index += 2;
        } else {
            merged.push(symbols[index].clone());
            index += 1;
        }
    }
    *symbols = merged;
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum LlamaClass {
    Letter,
    Number,
    Whitespace,
    Other,
}

fn llama_class(value: char) -> Result<LlamaClass> {
    // Rust's `char::is_alphabetic` includes Other_Alphabetic, while the
    // authenticated regex asks for Unicode General_Category `L`.  Without a
    // first-party Unicode category table, accepting non-ASCII classifications
    // would silently diverge from tokenizers. Keep that route fail-closed.
    if !value.is_ascii() && (value.is_alphabetic() || value.is_numeric() || value.is_whitespace()) {
        return Err(VokraError::ModelLoad(
            "csm tokenizer: non-ASCII Unicode category requires canonical tokenizer parity".into(),
        ));
    }
    Ok(if value.is_ascii_alphabetic() {
        LlamaClass::Letter
    } else if value.is_ascii_digit() {
        LlamaClass::Number
    } else if value.is_ascii_whitespace() {
        LlamaClass::Whitespace
    } else {
        LlamaClass::Other
    })
}

fn contraction_len(rest: &str) -> Option<usize> {
    ["'s", "'t", "'re", "'ve", "'m", "'ll", "'d"]
        .iter()
        .find(|candidate| {
            rest.get(..candidate.len())
                .is_some_and(|prefix| prefix.eq_ignore_ascii_case(candidate))
        })
        .map(|candidate| candidate.len())
}

#[cfg(test)]
mod tests {
    use super::*;
    use vokra_core::gguf::{GgufArray, GgufBuilder, GgufValueType};

    fn gguf_with_blob(blob: &[u8]) -> GgufFile {
        let mut b = GgufBuilder::new();
        b.add_string("vokra.model.arch", "csm");
        b.add_metadata(
            KEY_TOKENIZER_MODEL,
            GgufMetadataValue::Array(GgufArray {
                element_type: GgufValueType::U8,
                values: blob.iter().copied().map(GgufMetadataValue::U8).collect(),
            }),
        );
        GgufFile::parse(b.to_bytes().unwrap()).unwrap()
    }

    fn tiny_tokenizer_json() -> Vec<u8> {
        br#"{"version":"1.0","added_tokens":[{"id":8,"content":"<|begin_of_text|>"},{"id":9,"content":"<|end_of_text|>"}],"pre_tokenizer":{"type":"Sequence","pretokenizers":[{"type":"Split","pattern":{"Regex":"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]+[\\r\\n]*|\\s*[\\r\\n]+|\\s+(?!\\S)|\\s+"}},{"type":"ByteLevel","add_prefix_space":false,"trim_offsets":true,"use_regex":true}]},"post_processor":{"type":"TemplateProcessing","single":[{"SpecialToken":{"id":"<|begin_of_text|>","ids":[8]}},{"Sequence":{"id":"A"}},{"SpecialToken":{"id":"<|end_of_text|>","ids":[9]}}],"special_tokens":{"<|begin_of_text|>":{"id":"<|begin_of_text|>","ids":[8]},"<|end_of_text|>":{"id":"<|end_of_text|>","ids":[9]}}},"model":{"type":"BPE","byte_fallback":true,"vocab":{"h":0,"i":1,"hi":2,"\\u0120":3,"<|begin_of_text|>":8,"<|end_of_text|>":9},"merges":["h i"]}}"#.to_vec()
    }

    #[test]
    fn authenticated_blob_runs_bpe_and_template_processing() {
        let tok = GgufCsmTokenizer::from_gguf(&gguf_with_blob(&tiny_tokenizer_json()), 10).unwrap();
        assert_eq!(tok.encode("hi").unwrap(), vec![8, 2, 9]);
    }

    #[test]
    fn malformed_or_placeholder_blob_is_rejected() {
        let err = GgufCsmTokenizer::from_gguf(&gguf_with_blob(b"blob"), 100).unwrap_err();
        assert!(matches!(err, VokraError::ModelLoad(_)));
    }

    #[test]
    fn duplicate_json_keys_are_rejected_before_topology_lookup() {
        let mut blob = tiny_tokenizer_json();
        blob.splice(1..1, br#"\"version\":\"duplicate\","#.iter().copied());
        let err = GgufCsmTokenizer::from_gguf(&gguf_with_blob(&blob), 10).unwrap_err();
        assert!(matches!(err, VokraError::ModelLoad(_)));
    }

    #[test]
    fn fixture_tokenizer_is_explicit_and_bounded() {
        let tok = FixtureByteTokenizer::new(11).unwrap();
        let a = tok.encode("Vokra CSM").unwrap();
        assert_eq!(a, tok.encode("Vokra CSM").unwrap());
        assert!(a.iter().all(|&id| id < 11));
        assert!(tok.encode("").is_err());
        assert!(FixtureByteTokenizer::new(0).is_err());
    }

    #[test]
    fn llama_regex_preserves_ordered_alternatives() {
        assert_eq!(
            split_llama_regex("[0]I'm 123!").unwrap(),
            vec!["[", "0", "]I", "'m", " ", "123", "!"]
        );
    }

    #[test]
    fn llama_regex_keeps_optional_leading_space_with_letters() {
        assert_eq!(split_llama_regex(" hello").unwrap(), vec![" hello"]);
        assert_eq!(split_llama_regex("!hello").unwrap(), vec!["!hello"]);
        assert_eq!(split_llama_regex("  hello").unwrap(), vec![" ", " hello"]);
        assert_eq!(split_llama_regex(" \nhello").unwrap(), vec![" \n", "hello"]);
        assert_eq!(
            split_llama_regex(" \n\nhello").unwrap(),
            vec![" \n\n", "hello"]
        );
    }

    #[test]
    fn llama_regex_unicode_categories_fail_closed_without_a_unicode_table() {
        for text in ["é", "١", "\u{2003}"] {
            assert!(
                split_llama_regex(text).is_err(),
                "accepted unsupported {text:?}"
            );
        }
    }

    #[test]
    fn bpe_merges_all_non_overlapping_lowest_rank_pairs_in_one_pass() {
        let mut symbols = ["a", "b", "a", "b"]
            .into_iter()
            .map(str::to_owned)
            .collect();
        merge_all_pair(&mut symbols, "a", "b");
        assert_eq!(symbols, vec!["ab", "ab"]);

        let mut interaction = ["a", "b", "a", "b"]
            .into_iter()
            .map(str::to_owned)
            .collect();
        merge_all_pair(&mut interaction, "b", "a");
        assert_eq!(interaction, vec!["a", "ba", "b"]);

        let mut merges = HashMap::new();
        merges.insert(("a".to_owned(), "b".to_owned()), 1);
        merges.insert(("b".to_owned(), "a".to_owned()), 0);
        let tokenizer = LlamaBpe {
            vocab: [("a", 0), ("ba", 1), ("b", 2)]
                .into_iter()
                .map(|(key, value)| (key.to_owned(), value))
                .collect(),
            merges,
            bos_id: 3,
            eos_id: 4,
            byte_fallback: true,
            split_regex: true,
        };
        assert_eq!(tokenizer.encode("aba").unwrap(), vec![3, 0, 1, 4]);
    }
}
