# SPDX-License-Identifier: Apache-2.0
# !!! AUTO-GENERATED by bindings/python/scripts/gen-py-bindings.py — DO NOT EDIT. !!!
# Regenerate with `uv run --no-project --python 3.12 python bindings/python/scripts/gen-py-bindings.py`;
# CI enforces drift via `bindings/python/scripts/check-py-bindings.sh --check`.
#
# Source of truth: include/vokra.h (itself cbindgen output from `vokra-capi`).
# This file declares ctypes argtypes/restype so the pure-Python wrapper (T08+)
# can marshal calls into the prebuilt libvokra native library without any
# non-stdlib deps (NFR-DS-02).

from __future__ import annotations

import ctypes

# --- Enum constants (vokra_status_t) ---------------------------------------
VOKRA_OK = 0
VOKRA_ERROR_IO = 1
VOKRA_ERROR_MODEL_LOAD = 2
VOKRA_ERROR_UNSUPPORTED_OP = 3
VOKRA_ERROR_BACKEND_UNAVAILABLE = 4
VOKRA_ERROR_INVALID_ARGUMENT = 5
VOKRA_ERROR_GRAPH_VALIDATION = 6
VOKRA_ERROR_NOT_IMPLEMENTED = 7
VOKRA_ERROR_PANIC = 8
VOKRA_ERROR_OTHER = 9

# --- Enum constants (vokra_aec_status_t) ------------------------
VOKRA_AEC_CANCELLED = 0
VOKRA_AEC_PASS_THROUGH = 1
VOKRA_AEC_PARTIAL_REFERENCE = 2
VOKRA_AEC_RESET = 3

# --- Enum constants (vokra_event_kind_t) ------------------------
VOKRA_EVENT_UNKNOWN = 0
VOKRA_EVENT_SPEECH_PROB = 1
VOKRA_EVENT_TOKEN = 2

# --- Enum constants (vokra_backend_t) ------------------------
VOKRA_BACKEND_CPU = 0
VOKRA_BACKEND_METAL = 1
VOKRA_BACKEND_CUDA = 2
VOKRA_BACKEND_VULKAN = 3
VOKRA_BACKEND_WEBGPU = 4

# --- Structures ------------------------------------------------------------
class vokra_aec_config_t(ctypes.Structure):
    _fields_ = [
        ('sample_rate', ctypes.c_uint32),
        ('frame_size', ctypes.c_size_t),
        ('filter_length', ctypes.c_size_t),
        ('ref_queue_capacity_samples', ctypes.c_size_t),
    ]

class vokra_event_t(ctypes.Structure):
    _fields_ = [
        ('kind', ctypes.c_int),
        ('a', ctypes.c_uint32),
        ('b', ctypes.c_float),
    ]

# Opaque handles. Python never dereferences these pointers; only the
# native runtime owns their layouts.
vokra_aec_ref_writer_t = ctypes.c_void_p
vokra_aec_t = ctypes.c_void_p
vokra_feat_t = ctypes.c_void_p
vokra_s2s_duplex_t = ctypes.c_void_p
vokra_s2s_interrupt_t = ctypes.c_void_p
vokra_session_options_t = ctypes.c_void_p
vokra_session_t = ctypes.c_void_p
vokra_stream_t = ctypes.c_void_p
VokraSession = vokra_session_t
VokraStream = vokra_stream_t

# --- ctypes prototypes -----------------------------------------------------
# Populated by `bind(lib)` at import time from the loaded CDLL.

PROTOTYPES = {
    'vokra_aec_create': (
        ctypes.c_int,
        (ctypes.POINTER(vokra_aec_config_t), ctypes.POINTER(ctypes.c_void_p), ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_aec_ref_push': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.c_uint64, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_aec_process': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_uint64, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_aec_reset': (
        ctypes.c_int,
        (ctypes.c_void_p,),
    ),
    'vokra_aec_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_aec_ref_writer_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_asr_transcribe': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.c_int32, ctypes.POINTER(ctypes.c_char_p),),
    ),
    'vokra_string_free': (
        None,
        (ctypes.POINTER(ctypes.c_char),),
    ),
    'vokra_last_error': (
        ctypes.c_char_p,
        (),
    ),
    'vokra_feat_open': (
        ctypes.c_void_p,
        (ctypes.c_void_p,),
    ),
    'vokra_feat_frame_rate_mhz': (
        ctypes.c_int32,
        (ctypes.c_void_p,),
    ),
    'vokra_feat_dim': (
        ctypes.c_int32,
        (ctypes.c_void_p,),
    ),
    'vokra_feat_push_pcm': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t,),
    ),
    'vokra_feat_pull': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(ctypes.c_int64),),
    ),
    'vokra_feat_reset': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_feat_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_session_options_create': (
        ctypes.c_void_p,
        (),
    ),
    'vokra_session_options_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_session_options_set_backend': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.c_int32,),
    ),
    'vokra_backend_available': (
        ctypes.c_bool,
        (ctypes.c_int32,),
    ),
    'vokra_s2s_duplex_open': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.c_int32, ctypes.c_uint64, ctypes.c_int32, ctypes.c_uint64, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_s2s_frame_hop': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_s2s_sample_rate': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint32),),
    ),
    'vokra_s2s_push_mic': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.POINTER(ctypes.c_int32),),
    ),
    'vokra_s2s_pull_audio': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_s2s_text': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_char), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_s2s_interrupt_handle': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_s2s_interrupt': (
        ctypes.c_int,
        (ctypes.c_void_p,),
    ),
    'vokra_s2s_interrupt_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_s2s_duplex_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_model_attribution': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_char), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_session_create_from_file': (
        ctypes.c_int,
        (ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_session_create_from_bytes': (
        ctypes.c_int,
        (ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_session_create_from_file_with_options': (
        ctypes.c_int,
        (ctypes.c_char_p, ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_session_create_from_bytes_with_options': (
        ctypes.c_int,
        (ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t, ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_session_retain': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_session_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_version': (
        ctypes.c_char_p,
        (),
    ),
    'vokra_speaker_embed': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.c_int32, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_speaker_verify': (
        ctypes.c_int,
        (ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.c_float, ctypes.POINTER(ctypes.c_float), ctypes.POINTER(ctypes.c_bool),),
    ),
    'vokra_stream_open': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.c_int32, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_stream_push_pcm': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t,),
    ),
    'vokra_stream_poll': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_stream_poll_events': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(vokra_event_t), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_stream_interrupt': (
        ctypes.c_int,
        (ctypes.c_void_p,),
    ),
    'vokra_stream_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_tts_synthesize': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.c_char_p, ctypes.POINTER(ctypes.POINTER(ctypes.c_float)), ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(ctypes.c_int32),),
    ),
    'vokra_audio_free': (
        None,
        (ctypes.POINTER(ctypes.c_float), ctypes.c_size_t,),
    ),
}


def bind(lib: ctypes.CDLL) -> ctypes.CDLL:
    """Attach argtypes/restype to every exported vokra_* function on `lib`.

    Safe to call multiple times (idempotent). Raises AttributeError if the
    loaded library is missing a symbol the header declares — this signals a
    binding/library version skew and MUST fail loudly (FR-EX-08: no silent
    fallback).
    """
    for name, (restype, argtypes) in PROTOTYPES.items():
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = list(argtypes)
    return lib
