# SPDX-License-Identifier: Apache-2.0
# !!! AUTO-GENERATED by bindings/python/scripts/gen-py-bindings.py — DO NOT EDIT. !!!
# Regenerate with `python bindings/python/scripts/gen-py-bindings.py`;
# CI enforces drift via `bindings/python/scripts/check-py-bindings.sh --check`.
#
# Source of truth: include/vokra.h (itself cbindgen output from `vokra-capi`).
# This file declares ctypes argtypes/restype so the pure-Python wrapper (T08+)
# can marshal calls into the prebuilt libvokra native library without any
# non-stdlib deps (NFR-DS-02).

from __future__ import annotations

import ctypes

# --- Enum constants (vokra_status_t) ---------------------------------------
VOKRA_OK = 0
VOKRA_ERROR_IO = 1
VOKRA_ERROR_MODEL_LOAD = 2
VOKRA_ERROR_UNSUPPORTED_OP = 3
VOKRA_ERROR_BACKEND_UNAVAILABLE = 4
VOKRA_ERROR_INVALID_ARGUMENT = 5
VOKRA_ERROR_GRAPH_VALIDATION = 6
VOKRA_ERROR_NOT_IMPLEMENTED = 7
VOKRA_ERROR_PANIC = 8
VOKRA_ERROR_OTHER = 9

# --- Enum constants (vokra_event_kind_t) -----------------------------------
VOKRA_EVENT_UNKNOWN = 0
VOKRA_EVENT_SPEECH_PROB = 1
VOKRA_EVENT_TOKEN = 2

# --- Structures ------------------------------------------------------------
class vokra_event_t(ctypes.Structure):
    _fields_ = [
        ("kind", ctypes.c_int),
        ("a", ctypes.c_uint32),
        ("b", ctypes.c_float),
    ]

# Opaque handle typedefs (Python treats them as c_void_p; the runtime is
# the only entity that dereferences them).
VokraSession = ctypes.c_void_p
VokraStream = ctypes.c_void_p

# --- ctypes prototypes -----------------------------------------------------
# Populated by `bind(lib)` at import time from the loaded CDLL.

PROTOTYPES = {
    'vokra_asr_transcribe': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.c_int32, ctypes.POINTER(ctypes.c_char_p),),
    ),
    'vokra_string_free': (
        None,
        (ctypes.c_char_p,),
    ),
    'vokra_last_error': (
        ctypes.c_char_p,
        (),
    ),
    'vokra_session_create_from_file': (
        ctypes.c_int,
        (ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_session_retain': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_session_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_version': (
        ctypes.c_char_p,
        (),
    ),
    'vokra_stream_open': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.c_int32, ctypes.POINTER(ctypes.c_void_p),),
    ),
    'vokra_stream_push_pcm': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t,),
    ),
    'vokra_stream_poll': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_stream_poll_events': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.POINTER(vokra_event_t), ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t),),
    ),
    'vokra_stream_destroy': (
        None,
        (ctypes.c_void_p,),
    ),
    'vokra_tts_synthesize': (
        ctypes.c_int,
        (ctypes.c_void_p, ctypes.c_char_p, ctypes.POINTER(ctypes.POINTER(ctypes.c_float)), ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(ctypes.c_int32),),
    ),
    'vokra_audio_free': (
        None,
        (ctypes.POINTER(ctypes.c_float), ctypes.c_size_t,),
    ),
}


def bind(lib: ctypes.CDLL) -> ctypes.CDLL:
    """Attach argtypes/restype to every exported vokra_* function on `lib`.

    Safe to call multiple times (idempotent). Raises AttributeError if the
    loaded library is missing a symbol the header declares — this signals a
    binding/library version skew and MUST fail loudly (FR-EX-08: no silent
    fallback).
    """
    for name, (restype, argtypes) in PROTOTYPES.items():
        fn = getattr(lib, name)
        fn.restype = restype
        fn.argtypes = list(argtypes)
    return lib
