//! Moshi configuration resolved from the `vokra.moshi.*` GGUF chunk group
//! (M4-06-T03).
//!
//! Every value is **read from the GGUF** — nothing is hard-coded (CLAUDE.md
//! ハルシネーション厳禁; FR-LD-02 / FR-MD-02). The converter
//! (`vokra-convert::models::moshi`) derives the numeric hparams from the
//! upstream checkpoint tensor shapes (`kyutai/moshiko-pytorch-bf16`
//! `model.safetensors` — the T02 manifest fixture
//! `tests/parity/moshi/moshiko_tensor_manifest.json`) plus the
//! `kyutai-labs/moshi` `loaders.py` `_lm_kwargs` constants recorded in ADR
//! M4-06 §D2; the runtime only consumes them here.
//!
//! # Channel layout (lm.py, transcribed)
//!
//! One backbone step consumes `n_q_in + 1` token channels: channel 0 is
//! the **text** stream (inner monologue), channels `1..=dep_q` are the
//! model's **own** audio codebooks (generated by the depformer), channels
//! `dep_q+1..=n_q_in` are the **user/other** audio codebooks (Mimi-encoded
//! mic input). Each channel has a per-channel **delay** (`_lm_kwargs
//! ["delays"]`, 17 entries for the 7B model).
//!
//! # Audio rates live in the Mimi chunk
//!
//! `vokra.moshi.*` deliberately carries **no sample-rate / frame-rate
//! keys**: the Moshi LM operates purely in the token domain; the PCM
//! boundary is the shared Mimi module, whose `vokra.mimi.*` chunk group is
//! the single authority for 24 kHz / 12.5 Hz (ADR M4-06 §D3 — no
//! duplicated-key drift).
//!
//! # `0`-placeholder posture (cosyvoice2 / csm precedent)
//!
//! A key that is **absent** reads as `0` (or the documented upstream
//! default for ε / RoPE max_period); a key present with the wrong type is
//! a loud [`VokraError::InvalidArgument`] (FR-EX-08). Forward paths call
//! [`MoshiConfig::validate_for_forward`] first so a shape-only converter
//! GGUF fails loudly at first use — never a silent zero-shape forward.

use vokra_core::gguf::{GgufFile, GgufMetadataValue};
use vokra_core::{Result, VokraError};

// --- `vokra.moshi.*` metadata keys (ADR M4-06 §D3) --------------------------
//
// Duplicated verbatim in `vokra-convert::models::moshi` (the two crates only
// share `vokra-core`; a converter-side round-trip test catches drift — the
// csm / cosyvoice2 pattern).

pub(crate) const KEY_TM_N_LAYER: &str = "vokra.moshi.arch.temporal.n_layer";
pub(crate) const KEY_TM_D_MODEL: &str = "vokra.moshi.arch.temporal.d_model";
pub(crate) const KEY_TM_N_HEAD: &str = "vokra.moshi.arch.temporal.n_head";
pub(crate) const KEY_TM_FFN_HIDDEN: &str = "vokra.moshi.arch.temporal.ffn_hidden";

pub(crate) const KEY_DT_N_LAYER: &str = "vokra.moshi.arch.depth.n_layer";
pub(crate) const KEY_DT_D_MODEL: &str = "vokra.moshi.arch.depth.d_model";
pub(crate) const KEY_DT_N_HEAD: &str = "vokra.moshi.arch.depth.n_head";
pub(crate) const KEY_DT_FFN_HIDDEN: &str = "vokra.moshi.arch.depth.ffn_hidden";

pub(crate) const KEY_RMS_NORM_EPS: &str = "vokra.moshi.arch.rms_norm_eps";
pub(crate) const KEY_ROPE_MAX_PERIOD: &str = "vokra.moshi.arch.rope_max_period";
pub(crate) const KEY_CONTEXT: &str = "vokra.moshi.arch.context";
pub(crate) const KEY_MAX_CTX: &str = "vokra.moshi.arch.max_ctx";

pub(crate) const KEY_AUDIO_N_Q_IN: &str = "vokra.moshi.audio.n_q_in";
pub(crate) const KEY_AUDIO_DEP_Q: &str = "vokra.moshi.audio.dep_q";
pub(crate) const KEY_AUDIO_CARD: &str = "vokra.moshi.audio.card";

pub(crate) const KEY_TEXT_CARD: &str = "vokra.moshi.text.card";
pub(crate) const KEY_TEXT_PAD_ID: &str = "vokra.moshi.text.pad_id";
pub(crate) const KEY_TEXT_END_PAD_ID: &str = "vokra.moshi.text.end_pad_id";

pub(crate) const KEY_N_DELAYS: &str = "vokra.moshi.n_delays";
/// Indexed delay keys `vokra.moshi.delay.{i}` (the `vokra.mimi.seanet.
/// ratio.{i}` count-plus-indexed-keys precedent — no GGUF array plumbing).
pub(crate) const PREFIX_DELAY: &str = "vokra.moshi.delay.";

/// Safety-net RMSNorm ε used **only** when the GGUF omits the key. The
/// upstream norm is `rms_norm_f32` whose ε is **1e-8** (`kyutai-labs/moshi`
/// `transformer.py` `create_norm_fn`: `RMSNorm(dim, eps=1e-8, dtype=float)`
/// — ADR M4-06 §D2; note this differs from the CSM/Llama 1e-5).
pub const DEFAULT_MOSHI_RMS_NORM_EPS: f32 = 1e-8;

/// Safety-net RoPE max period used **only** when the GGUF omits the key
/// (`_lm_kwargs["max_period"] = 10000` — ADR M4-06 §D2).
pub const DEFAULT_MOSHI_ROPE_MAX_PERIOD: f32 = 10_000.0;

/// One transformer stack's hparams. Moshi attention is **MHA** (kv_repeat
/// = 1 — `in_proj_weight` is `3·d_model` rows in the T02 manifest), so
/// there is no GQA head split; `ffn_hidden` is the **gating hidden width**
/// (`ActivationGating`: `linear_in = [2·hidden, d]`, `linear_out =
/// [d, hidden]` — gating.py), *not* the nominal `dim_feedforward`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MoshiTransformerConfig {
    /// Transformer block count.
    pub n_layer: usize,
    /// Hidden width (`d`).
    pub d_model: usize,
    /// Attention heads (MHA: query = key = value heads).
    pub n_head: usize,
    /// SiLU-gating hidden width (see struct docs).
    pub ffn_hidden: usize,
}

impl MoshiTransformerConfig {
    /// Per-head width (`d_model / n_head`); `0` when `n_head == 0`
    /// (shape-only converter sentinel) so shape checks never panic.
    #[must_use]
    pub fn head_dim(&self) -> usize {
        self.d_model.checked_div(self.n_head).unwrap_or(0)
    }

    /// MHA algebraic constraint: heads divide the width, all non-zero.
    #[must_use]
    pub fn is_well_formed(&self) -> bool {
        self.n_head != 0 && self.d_model != 0 && self.d_model % self.n_head == 0
    }
}

/// The resolved Moshi hparam snapshot (`vokra.moshi.*` chunk group).
#[derive(Debug, Clone, PartialEq)]
pub struct MoshiConfig {
    /// Helium temporal backbone (32L / d4096 / 32H for the 7B checkpoint).
    pub temporal: MoshiTransformerConfig,
    /// Depformer (per-frame codebook-axis stack, **per-step weights**).
    pub depth: MoshiTransformerConfig,
    /// RMSNorm ε (both stacks — `rms_norm_f32`, 1e-8 upstream).
    pub rms_norm_eps: f32,
    /// RoPE max period (temporal backbone only; the depformer has no
    /// positional embedding — `depformer_pos_emb="none"`).
    pub rope_max_period: f32,
    /// Sliding attention window in frame positions (`context=3000`
    /// upstream): position `q` attends to keys with `q - k < context`.
    pub context: usize,
    /// KV reserve: positions past this are a loud error (FR-EX-08 — no
    /// silent wrap-around; upstream's RingKVCache releases memory past
    /// `context` but the *math* is the sliding-window mask, which this
    /// runtime applies exactly — ADR M4-06 §D1-(e)).
    pub max_ctx: usize,
    /// Total audio input streams (`n_q` = 16 upstream: `dep_q` own +
    /// `n_q - dep_q` user).
    pub n_q_in: usize,
    /// Own (generated) audio streams — the depformer step count.
    pub dep_q: usize,
    /// Per-codebook audio vocab (`card` = 2048 upstream; embedding tables
    /// carry `card + 1` rows, the extra row being the initial token).
    pub audio_card: usize,
    /// Text vocab (`text_card` = 32000 upstream; `text_emb` carries
    /// `text_card + 1` rows).
    pub text_card: usize,
    /// Text padding id (`existing_text_padding_id` = 3 upstream) — hidden
    /// from the inner-monologue display.
    pub text_pad_id: u32,
    /// End-of-padding id (`end_of_text_padding_id` = 0 upstream) — also
    /// hidden from the display.
    pub text_end_pad_id: u32,
    /// Per-channel delays, `len == n_q_in + 1`: index 0 = text, `1..=dep_q`
    /// = own audio, rest = user audio (`_lm_kwargs["delays"]`).
    pub delays: Vec<u32>,
}

impl MoshiConfig {
    /// Total token channels per step (`num_codebooks` upstream = text +
    /// audio streams).
    #[must_use]
    pub fn n_channels(&self) -> usize {
        self.n_q_in + 1
    }

    /// User/other audio streams the caller supplies per step
    /// (`needed_tokens = num_codebooks - dep_q - 1` — lm.py `_step`).
    #[must_use]
    pub fn n_user_streams(&self) -> usize {
        self.n_q_in.saturating_sub(self.dep_q)
    }

    /// The largest per-channel delay (warmup steps before the first
    /// output frame — `LMGen.max_delay`).
    #[must_use]
    pub fn max_delay(&self) -> u32 {
        self.delays.iter().copied().max().unwrap_or(0)
    }

    /// The audio initial token (`initial_token_id = card` — lm.py): the
    /// extra embedding row fed while a channel is still inside its delay.
    #[must_use]
    pub fn audio_initial_token(&self) -> u32 {
        self.audio_card as u32
    }

    /// The text initial token (`text_initial_token_id = text_card`).
    #[must_use]
    pub fn text_initial_token(&self) -> u32 {
        self.text_card as u32
    }

    /// Reads the Moshi hparams from a Moshi GGUF. Missing numeric keys
    /// read as `0` placeholders (ε / max_period take the documented
    /// upstream defaults); wrong-typed keys are loud errors (FR-EX-08).
    ///
    /// # Errors
    ///
    /// [`VokraError::InvalidArgument`] if any present key has the wrong
    /// metadata type or the indexed delay list is internally inconsistent.
    pub fn from_gguf(file: &GgufFile) -> Result<Self> {
        let n_delays = read_u32_or_zero(file, KEY_N_DELAYS)? as usize;
        let mut delays = Vec::with_capacity(n_delays);
        for i in 0..n_delays {
            let key = format!("{PREFIX_DELAY}{i}");
            match file.get(&key) {
                Some(GgufMetadataValue::U32(v)) => delays.push(*v),
                None => {
                    return Err(VokraError::InvalidArgument(format!(
                        "moshi config: `{KEY_N_DELAYS}` = {n_delays} but `{key}` is \
                         absent (indexed delay keys must be dense)"
                    )));
                }
                Some(other) => {
                    return Err(VokraError::InvalidArgument(format!(
                        "moshi config: `{key}` is not a UINT32 (got {:?})",
                        other.value_type()
                    )));
                }
            }
        }
        Ok(Self {
            temporal: MoshiTransformerConfig {
                n_layer: read_u32_or_zero(file, KEY_TM_N_LAYER)? as usize,
                d_model: read_u32_or_zero(file, KEY_TM_D_MODEL)? as usize,
                n_head: read_u32_or_zero(file, KEY_TM_N_HEAD)? as usize,
                ffn_hidden: read_u32_or_zero(file, KEY_TM_FFN_HIDDEN)? as usize,
            },
            depth: MoshiTransformerConfig {
                n_layer: read_u32_or_zero(file, KEY_DT_N_LAYER)? as usize,
                d_model: read_u32_or_zero(file, KEY_DT_D_MODEL)? as usize,
                n_head: read_u32_or_zero(file, KEY_DT_N_HEAD)? as usize,
                ffn_hidden: read_u32_or_zero(file, KEY_DT_FFN_HIDDEN)? as usize,
            },
            rms_norm_eps: read_f32_or(file, KEY_RMS_NORM_EPS, DEFAULT_MOSHI_RMS_NORM_EPS)?,
            rope_max_period: read_f32_or(file, KEY_ROPE_MAX_PERIOD, DEFAULT_MOSHI_ROPE_MAX_PERIOD)?,
            context: read_u32_or_zero(file, KEY_CONTEXT)? as usize,
            max_ctx: read_u32_or_zero(file, KEY_MAX_CTX)? as usize,
            n_q_in: read_u32_or_zero(file, KEY_AUDIO_N_Q_IN)? as usize,
            dep_q: read_u32_or_zero(file, KEY_AUDIO_DEP_Q)? as usize,
            audio_card: read_u32_or_zero(file, KEY_AUDIO_CARD)? as usize,
            text_card: read_u32_or_zero(file, KEY_TEXT_CARD)? as usize,
            text_pad_id: read_u32_or_zero(file, KEY_TEXT_PAD_ID)?,
            text_end_pad_id: read_u32_or_zero(file, KEY_TEXT_END_PAD_ID)?,
            delays,
        })
    }

    /// Rejects `0`-placeholder / ill-formed configs before any forward
    /// runs (FR-EX-08 — a shape-only converter GGUF fails loudly here,
    /// not deep inside a GEMM).
    ///
    /// # Errors
    ///
    /// [`VokraError::InvalidArgument`] naming the offending field.
    pub fn validate_for_forward(&self) -> Result<()> {
        for (stack, cfg) in [("temporal", &self.temporal), ("depth", &self.depth)] {
            if !cfg.is_well_formed() {
                return Err(VokraError::InvalidArgument(format!(
                    "moshi config: {stack} stack not MHA well-formed (n_layer={}, \
                     d_model={}, n_head={}, ffn_hidden={})",
                    cfg.n_layer, cfg.d_model, cfg.n_head, cfg.ffn_hidden
                )));
            }
            if cfg.n_layer == 0 || cfg.ffn_hidden == 0 {
                return Err(VokraError::InvalidArgument(format!(
                    "moshi config: {stack} stack carries a 0-placeholder (n_layer={}, \
                     ffn_hidden={}) — re-convert with real hparams (T03) or use \
                     MoshiConfig::tiny_for_tests",
                    cfg.n_layer, cfg.ffn_hidden
                )));
            }
        }
        if self.temporal.head_dim() % 2 != 0 {
            return Err(VokraError::InvalidArgument(format!(
                "moshi config: temporal head_dim {} must be even (RoPE pairs)",
                self.temporal.head_dim()
            )));
        }
        if self.context == 0 || self.max_ctx == 0 {
            return Err(VokraError::InvalidArgument(format!(
                "moshi config: context={} / max_ctx={} — both must be > 0 (no \
                 forward can bound its attention window / KV reserve)",
                self.context, self.max_ctx
            )));
        }
        if self.dep_q == 0 || self.n_q_in < self.dep_q {
            return Err(VokraError::InvalidArgument(format!(
                "moshi config: dep_q={} / n_q_in={} — need 1 <= dep_q <= n_q_in \
                 (own streams are a subset of the audio channels)",
                self.dep_q, self.n_q_in
            )));
        }
        if self.n_user_streams() == 0 {
            return Err(VokraError::InvalidArgument(format!(
                "moshi config: n_q_in={} == dep_q={} leaves no user stream — \
                 full-duplex needs at least one incoming audio channel",
                self.n_q_in, self.dep_q
            )));
        }
        if self.audio_card == 0 || self.text_card == 0 {
            return Err(VokraError::InvalidArgument(format!(
                "moshi config: zero-size vocab (audio_card={}, text_card={})",
                self.audio_card, self.text_card
            )));
        }
        if self.delays.len() != self.n_channels() {
            return Err(VokraError::InvalidArgument(format!(
                "moshi config: {} delays for {} channels (text + n_q_in — \
                 `_lm_kwargs[\"delays\"]` is per-channel)",
                self.delays.len(),
                self.n_channels()
            )));
        }
        if self.text_pad_id as usize >= self.text_card
            || self.text_end_pad_id as usize >= self.text_card
        {
            return Err(VokraError::InvalidArgument(format!(
                "moshi config: text pad ids ({}, {}) must be < text_card {}",
                self.text_pad_id, self.text_end_pad_id, self.text_card
            )));
        }
        Ok(())
    }

    /// Writes this config back as the `vokra.moshi.*` chunk group — the
    /// fixture-building mirror of [`Self::from_gguf`] (tests / host-only
    /// CLI smoke build tiny GGUFs through it; the offline converter
    /// duplicates the key strings per the cross-crate pattern and a
    /// converter-side round-trip test pins the two).
    pub fn write_gguf_metadata(&self, b: &mut vokra_core::gguf::GgufBuilder) {
        b.add_u32(KEY_TM_N_LAYER, self.temporal.n_layer as u32);
        b.add_u32(KEY_TM_D_MODEL, self.temporal.d_model as u32);
        b.add_u32(KEY_TM_N_HEAD, self.temporal.n_head as u32);
        b.add_u32(KEY_TM_FFN_HIDDEN, self.temporal.ffn_hidden as u32);
        b.add_u32(KEY_DT_N_LAYER, self.depth.n_layer as u32);
        b.add_u32(KEY_DT_D_MODEL, self.depth.d_model as u32);
        b.add_u32(KEY_DT_N_HEAD, self.depth.n_head as u32);
        b.add_u32(KEY_DT_FFN_HIDDEN, self.depth.ffn_hidden as u32);
        b.add_f32(KEY_RMS_NORM_EPS, self.rms_norm_eps);
        b.add_f32(KEY_ROPE_MAX_PERIOD, self.rope_max_period);
        b.add_u32(KEY_CONTEXT, self.context as u32);
        b.add_u32(KEY_MAX_CTX, self.max_ctx as u32);
        b.add_u32(KEY_AUDIO_N_Q_IN, self.n_q_in as u32);
        b.add_u32(KEY_AUDIO_DEP_Q, self.dep_q as u32);
        b.add_u32(KEY_AUDIO_CARD, self.audio_card as u32);
        b.add_u32(KEY_TEXT_CARD, self.text_card as u32);
        b.add_u32(KEY_TEXT_PAD_ID, self.text_pad_id);
        b.add_u32(KEY_TEXT_END_PAD_ID, self.text_end_pad_id);
        b.add_u32(KEY_N_DELAYS, self.delays.len() as u32);
        for (i, d) in self.delays.iter().enumerate() {
            b.add_u32(&format!("{PREFIX_DELAY}{i}"), *d);
        }
    }

    /// A miniature well-formed config for synthesized-weight tests. Dims
    /// are tiny so the whole duplex loop runs in milliseconds; the *shape
    /// relationships* mirror the 7B model (ADR M4-06 §D8): text + own +
    /// user channel split, the `[0, 0, 1.., 0, 1..]` delay structure with
    /// `max_delay = 1` preserved, even temporal head_dim, per-step
    /// depformer weights (`dep_q` steps).
    #[must_use]
    pub fn tiny_for_tests() -> Self {
        Self {
            temporal: MoshiTransformerConfig {
                n_layer: 2,
                d_model: 16,
                n_head: 4,
                ffn_hidden: 8,
            },
            depth: MoshiTransformerConfig {
                n_layer: 2,
                d_model: 8,
                n_head: 2,
                ffn_hidden: 6,
            },
            rms_norm_eps: DEFAULT_MOSHI_RMS_NORM_EPS,
            rope_max_period: DEFAULT_MOSHI_ROPE_MAX_PERIOD,
            context: 32,
            max_ctx: 32,
            n_q_in: 4,
            dep_q: 2,
            audio_card: 9,
            text_card: 13,
            text_pad_id: 3,
            text_end_pad_id: 0,
            // [text, own cb0, own cb1, user cb0, user cb1] — the 7B
            // structure `[0, 0, 1.., 0, 1..]` at dep_q = 2.
            delays: vec![0, 0, 1, 0, 1],
        }
    }
}

fn read_u32_or_zero(file: &GgufFile, key: &str) -> Result<u32> {
    match file.get(key) {
        Some(GgufMetadataValue::U32(v)) => Ok(*v),
        None => Ok(0),
        Some(other) => Err(VokraError::InvalidArgument(format!(
            "moshi config: `{key}` is not a UINT32 (got {:?})",
            other.value_type()
        ))),
    }
}

fn read_f32_or(file: &GgufFile, key: &str, default: f32) -> Result<f32> {
    match file.get(key) {
        Some(GgufMetadataValue::F32(v)) => Ok(*v),
        None => Ok(default),
        Some(other) => Err(VokraError::InvalidArgument(format!(
            "moshi config: `{key}` is not a FLOAT32 (got {:?})",
            other.value_type()
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use vokra_core::gguf::GgufBuilder;

    fn parse(b: &GgufBuilder) -> GgufFile {
        GgufFile::parse(b.to_bytes().expect("serialize")).expect("parse")
    }

    #[test]
    fn missing_keys_read_as_placeholders_and_documented_defaults() {
        let mut b = GgufBuilder::new();
        b.add_string("vokra.model.arch", "moshi");
        let cfg = MoshiConfig::from_gguf(&parse(&b)).expect("from_gguf");
        assert_eq!(cfg.temporal.n_layer, 0);
        assert_eq!(cfg.max_ctx, 0);
        assert_eq!(cfg.delays, Vec::<u32>::new());
        assert_eq!(cfg.rms_norm_eps, DEFAULT_MOSHI_RMS_NORM_EPS);
        assert_eq!(cfg.rope_max_period, DEFAULT_MOSHI_ROPE_MAX_PERIOD);
        // The placeholder config refuses to run (FR-EX-08).
        assert!(matches!(
            cfg.validate_for_forward(),
            Err(VokraError::InvalidArgument(_))
        ));
    }

    #[test]
    fn upstream_default_eps_is_1e_8_not_1e_5() {
        // rms_norm_f32 → eps = 1e-8 (transformer.py create_norm_fn) — the
        // CSM/Llama 1e-5 default must not leak into the Moshi path.
        assert_eq!(DEFAULT_MOSHI_RMS_NORM_EPS, 1e-8);
    }

    #[test]
    fn wrong_typed_key_is_loud() {
        let mut b = GgufBuilder::new();
        b.add_string(KEY_TM_N_LAYER, "x");
        assert!(matches!(
            MoshiConfig::from_gguf(&parse(&b)),
            Err(VokraError::InvalidArgument(_))
        ));
    }

    #[test]
    fn sparse_indexed_delays_are_rejected() {
        // n_delays = 2 but only delay.0 present → dense-index violation.
        let mut b = GgufBuilder::new();
        b.add_u32(KEY_N_DELAYS, 2);
        b.add_u32("vokra.moshi.delay.0", 0);
        let err = MoshiConfig::from_gguf(&parse(&b)).unwrap_err();
        assert!(err.to_string().contains("delay.1"), "names the hole: {err}");
    }

    #[test]
    fn round_trip_of_fully_populated_chunk_group() {
        let t = MoshiConfig::tiny_for_tests();
        let mut b = GgufBuilder::new();
        b.add_string("vokra.model.arch", "moshi");
        t.write_gguf_metadata(&mut b);
        let cfg = MoshiConfig::from_gguf(&parse(&b)).expect("from_gguf");
        assert_eq!(cfg, t);
        cfg.validate_for_forward().expect("tiny config well-formed");
    }

    #[test]
    fn channel_arithmetic_matches_lm_py() {
        // 7B shape: n_q=16, dep_q=8 → 17 channels, 8 user streams,
        // max_delay 1 (ADR M4-06 §D2). The tiny config preserves the
        // relationships at dep_q=2.
        let t = MoshiConfig::tiny_for_tests();
        assert_eq!(t.n_channels(), t.n_q_in + 1);
        assert_eq!(t.n_user_streams(), t.n_q_in - t.dep_q);
        assert_eq!(t.max_delay(), 1);
        assert_eq!(t.audio_initial_token(), t.audio_card as u32);
        assert_eq!(t.text_initial_token(), t.text_card as u32);
        assert_eq!(t.delays.len(), t.n_channels());
    }

    #[test]
    fn validation_rejects_ill_formed_shapes() {
        let base = MoshiConfig::tiny_for_tests();

        let mut c = base.clone();
        c.temporal.n_head = 3; // 16 % 3 != 0
        assert!(c.validate_for_forward().is_err());

        let mut c = base.clone();
        c.temporal.d_model = 12; // head_dim 3 — odd, RoPE pairs need even
        assert!(c.validate_for_forward().is_err());

        let mut c = base.clone();
        c.dep_q = 0;
        assert!(c.validate_for_forward().is_err());

        let mut c = base.clone();
        c.dep_q = c.n_q_in; // no user stream left
        c.delays = vec![0; c.n_q_in + 1];
        assert!(c.validate_for_forward().is_err());

        let mut c = base.clone();
        c.delays.pop(); // wrong per-channel delay count
        assert!(c.validate_for_forward().is_err());

        let mut c = base.clone();
        c.text_pad_id = c.text_card as u32; // pad id out of vocab
        assert!(c.validate_for_forward().is_err());

        let mut c = base.clone();
        c.context = 0;
        assert!(c.validate_for_forward().is_err());
    }
}
