#!/usr/bin/env bash
# fetch_license.sh — obtain the correct LICENSE text for a model being published.
#
# The right text depends on where the licence actually lives:
#   * some upstreams ship a LICENSE file (fetch it — it carries the specific
#     copyright line the licence requires be retained);
#   * some declare the licence only in HF model-card front-matter and ship no
#     LICENSE file (use the canonical SPDX text);
#   * CC-BY / CC-BY-SA point at the canonical Creative Commons legalcode.
#
# Redistribution obligation: MIT and BSD require the copyright notice travel
# with the work, Apache-2.0 requires the licence (and NOTICE if present),
# CC-BY requires attribution + the licence. Shipping the wrong text, or none,
# fails that — so this refuses rather than emit a placeholder.
#
# Usage:
#   fetch_license.sh --url  <raw-license-url>  <out-file>   # upstream ships one
#   fetch_license.sh --spdx <apache-2.0|mit|cc-by-4.0|cc-by-sa-4.0|agpl-3.0> <out-file>  # canonical
#   fetch_license.sh --self-test

set -euo pipefail
CURL="/usr/bin/curl"

canonical_url() {
  case "$1" in
    apache-2.0)  echo "https://www.apache.org/licenses/LICENSE-2.0.txt" ;;
    mit)         echo "https://raw.githubusercontent.com/spdx/license-list-data/main/text/MIT.txt" ;;
    cc-by-4.0)   echo "https://creativecommons.org/licenses/by/4.0/legalcode.txt" ;;
    cc-by-sa-4.0) echo "https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt" ;;
    cc-by-nc-4.0) echo "https://creativecommons.org/licenses/by-nc/4.0/legalcode.txt" ;;
    cc-by-nc-sa-4.0) echo "https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt" ;;
    agpl-3.0)    echo "https://www.gnu.org/licenses/agpl-3.0.txt" ;;
    bsd-2-clause) echo "https://raw.githubusercontent.com/spdx/license-list-data/main/text/BSD-2-Clause.txt" ;;
    bsd-3-clause) echo "https://raw.githubusercontent.com/spdx/license-list-data/main/text/BSD-3-Clause.txt" ;;
    cc0-1.0)      echo "https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt" ;;
    *) return 1 ;;
  esac
}

# Inline license text for SPDX ids without a stable plain-text canonical URL.
# openmdw-1.1 falls in this category: openmdw.ai/license/1-1/ serves HTML only,
# and the Linux Foundation has not published a canonical plain-text mirror.
# The verbatim text below is transcribed from openmdw.ai/license/1-1/
# (CC-directly fetched 2026-07-30). Redistribution obligation §D requires
# a copy of the agreement to travel with the Model Materials — inlining the
# text here is the simplest way to satisfy that discipline without a
# canonical URL.
inline_license_text() {
  case "$1" in
    openmdw-1.1)
      cat <<'OPENMDW_EOF'
OpenMDW License Agreement, version 1.1 (OpenMDW-1.1)

By exercising rights granted to you under this agreement, you accept and agree to its terms.

As used in this agreement, "Model Materials" means the materials provided to you under this agreement, consisting of: (1) one or more machine learning models (including architecture and parameters); and (2) all related artifacts (including associated data, documentation and software) that are provided to you hereunder.

Subject to your compliance with this agreement, permission is hereby granted, free of charge, to deal in the Model Materials without restriction, including under all copyright, patent, database, and trade secret rights included or embodied therein.

If you distribute any portion of the Model Materials, you shall retain in your distribution (1) a copy of this agreement, and (2) all copyright notices and other notices of origin included in the Model Materials that are applicable to your distribution.

If you file, maintain, or voluntarily participate in a lawsuit against any person or entity asserting that the Model Materials directly or indirectly infringe any patent or copyright, then all rights and grants made to you hereunder are terminated, unless that lawsuit was in response to a corresponding lawsuit first brought against you.

This agreement does not impose any restrictions or obligations with respect to any use, modification, or sharing of any outputs generated by using the Model Materials.

THE MODEL MATERIALS ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONINFRINGEMENT, ACCURACY, OR THE ABSENCE OF LATENT OR OTHER DEFECTS OR ERRORS, WHETHER OR NOT DISCOVERABLE, ALL TO THE GREATEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW.

YOU ARE SOLELY RESPONSIBLE FOR (1) CLEARING RIGHTS OF OTHER PERSONS THAT MAY APPLY TO THE MODEL MATERIALS OR ANY USE THEREOF, INCLUDING WITHOUT LIMITATION ANY PERSON'S COPYRIGHTS OR OTHER RIGHTS INCLUDED OR EMBODIED IN THE MODEL MATERIALS; (2) OBTAINING ANY NECESSARY CONSENTS, PERMISSIONS OR OTHER RIGHTS REQUIRED FOR ANY USE OF THE MODEL MATERIALS; OR (3) PERFORMING ANY DUE DILIGENCE OR UNDERTAKING ANY OTHER INVESTIGATIONS INTO THE MODEL MATERIALS OR ANYTHING INCORPORATED OR EMBODIED THEREIN.

IN NO EVENT SHALL THE PROVIDERS OF THE MODEL MATERIALS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE MODEL MATERIALS, THE USE THEREOF OR OTHER DEALINGS THEREIN.

Copyright The Linux Foundation and its contributors.
OPENMDW_EOF
      ;;
    *) return 1 ;;
  esac
}

if [[ "${1:-}" == "--self-test" ]]; then
  # Canonical Apache-2.0 must fetch and look like Apache-2.0.
  tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
  if "$0" --spdx apache-2.0 "$tmp" >/dev/null 2>&1 && grep -qi "Apache License" "$tmp"; then
    echo "fetch_license self-test: OK"; exit 0
  fi
  echo "fetch_license self-test: FAIL (could not fetch canonical Apache-2.0)" >&2
  exit 1
fi

mode="$1"; val="$2"; out="$3"

case "$mode" in
  --url)
    code="$("$CURL" -sL -o "$out" -w '%{http_code}' "$val")"
    [[ "$code" == "200" ]] || { echo "fetch_license: $val returned HTTP $code" >&2; exit 2; }
    ;;
  --spdx)
    spdx="$(printf '%s' "$val" | tr '[:upper:]' '[:lower:]')"
    if url="$(canonical_url "$spdx")"; then
      code="$("$CURL" -sL -o "$out" -w '%{http_code}' "$url")"
      [[ "$code" == "200" ]] || { echo "fetch_license: canonical $spdx ($url) HTTP $code" >&2; exit 2; }
    elif inline_license_text "$spdx" > "$out" 2>/dev/null && [[ -s "$out" ]]; then
      : # inline text written — HTTP-fetch not required.
    else
      echo "fetch_license: no canonical URL or inline text known for SPDX '$spdx'. Pass --url with the upstream LICENSE instead." >&2
      exit 3
    fi
    ;;
  *) echo "fetch_license: mode must be --url or --spdx" >&2; exit 2 ;;
esac

[[ -s "$out" ]] || { echo "fetch_license: wrote an empty file" >&2; exit 4; }
echo "fetch_license: wrote $(wc -l < "$out" | tr -d ' ') lines to $out"
