//! Real-weight Charsiu CPU/reference and Apple Metal parity.
//!
//! The Apple worker supplies a VAST-produced reference directory.  The
//! directory is authenticated by the shell worker before this test runs; the
//! reference itself is generated by the pinned official Transformers model,
//! not by Vokra code.

use std::env;
use std::fs;
use std::path::Path;

use vokra_core::BackendKind;
use vokra_models::align::charsiu::Charsiu;

const CPU_REFERENCE_ATOL: f32 = 0.0002;
// Existing repository GPU parity contract (`.agents/skills/numerical-parity`
// § GPU backend parity) uses FP32 atol=0.01 for GPU/reference and GPU/CPU.
const METAL_ATOL: f32 = 0.01;

fn f32_file(path: &Path) -> Vec<f32> {
    let bytes = fs::read(path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    assert_eq!(bytes.len() % 4, 0, "{} is not f32-aligned", path.display());
    bytes
        .chunks_exact(4)
        .map(|chunk| f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
        .collect()
}

fn max_abs(actual: &[f32], expected: &[f32]) -> (f32, usize) {
    assert_eq!(actual.len(), expected.len());
    actual
        .iter()
        .zip(expected)
        .enumerate()
        .map(|(index, (left, right))| ((left - right).abs(), index))
        .fold((0.0, 0), |best, candidate| {
            if candidate.0 > best.0 {
                candidate
            } else {
                best
            }
        })
}

#[test]
#[ignore = "real-weight Apple CPU/Metal parity; run through apple-silicon-charsiu.sh"]
fn charsiu_apple_cpu_metal_matches_reference() {
    let gguf = env::var_os("VOKRA_CHARSIU_GGUF").expect("VOKRA_CHARSIU_GGUF is required");
    let reference = env::var_os("VOKRA_CHARSIU_REFERENCE_DIR")
        .expect("VOKRA_CHARSIU_REFERENCE_DIR is required");
    let gguf_path = Path::new(&gguf);
    let reference_path = Path::new(&reference);
    let pcm = f32_file(&reference_path.join("pcm_400.f32.bin"));
    let expected = f32_file(&reference_path.join("logits_1x42.f32.bin"));
    assert_eq!(pcm.len(), 400);
    assert_eq!(expected.len(), 42);
    assert!(pcm.iter().all(|value| value.is_finite()));
    assert!(expected.iter().all(|value| value.is_finite()));

    let cpu = Charsiu::from_gguf_with_backend(gguf_path, BackendKind::Cpu)
        .expect("bind Charsiu with explicit CPU backend");
    let metal = Charsiu::from_gguf_with_backend(gguf_path, BackendKind::Metal)
        .expect("bind Charsiu with explicit Metal backend; no CPU fallback is permitted");
    assert_eq!(cpu.backend(), BackendKind::Cpu);
    assert_eq!(metal.backend(), BackendKind::Metal);

    let (cpu_logits, cpu_frames) = cpu.logits(&pcm, 16_000).expect("run Charsiu CPU forward");
    let (metal_logits, metal_frames) = metal
        .logits(&pcm, 16_000)
        .expect("run Charsiu Metal forward");
    assert_eq!(cpu_frames, 1);
    assert_eq!(metal_frames, cpu_frames);

    let (cpu_reference_max, cpu_reference_index) = max_abs(&cpu_logits, &expected);
    let (metal_reference_max, metal_reference_index) = max_abs(&metal_logits, &expected);
    let (metal_cpu_max, metal_cpu_index) = max_abs(&metal_logits, &cpu_logits);
    eprintln!(
        "CHARSIU_APPLE_CPU_REFERENCE_METRICS frames={cpu_frames} logits={} max_abs={cpu_reference_max:.9} index={cpu_reference_index} atol={CPU_REFERENCE_ATOL:.9}",
        cpu_logits.len()
    );
    eprintln!(
        "CHARSIU_APPLE_METAL_REFERENCE_METRICS frames={metal_frames} logits={} max_abs={metal_reference_max:.9} index={metal_reference_index} atol={METAL_ATOL:.9}",
        metal_logits.len()
    );
    eprintln!(
        "CHARSIU_APPLE_METAL_CPU_METRICS frames={metal_frames} logits={} max_abs={metal_cpu_max:.9} index={metal_cpu_index} atol={METAL_ATOL:.9}",
        metal_logits.len()
    );
    assert!(
        cpu_reference_max <= CPU_REFERENCE_ATOL,
        "Charsiu CPU/reference max_abs={cpu_reference_max:.9e} exceeds {CPU_REFERENCE_ATOL:.9e}"
    );
    assert!(
        metal_reference_max <= METAL_ATOL,
        "Charsiu Metal/reference max_abs={metal_reference_max:.9e} exceeds {METAL_ATOL:.9e}"
    );
    assert!(
        metal_cpu_max <= METAL_ATOL,
        "Charsiu Metal/CPU max_abs={metal_cpu_max:.9e} exceeds {METAL_ATOL:.9e}"
    );
    eprintln!(
        "CHARSIU_APPLE_PARITY PASS frames={cpu_frames} cpu_reference_atol={CPU_REFERENCE_ATOL:.9} metal_atol={METAL_ATOL:.9} reference=transformers.Wav2Vec2ForCTC route=explicit_cpu_and_metal no_fallback=true publication=NO_UPLOAD"
    );
}
