//! Kokoro-82M numerical parity vs the upstream reference (M2-07-T11).
//!
//! Fixtures live in `tests/parity/kokoro/` and are regenerated by
//! `tools/parity/dump_kokoro_reference.py`. All tensors dumped by the reference
//! script must match the native forward output at FP32 `atol = 0.01`
//! (NFR-QL-01).
//!
//! The full forward requires the converted **GGUF**, which is too large to
//! commit, so every test that touches [`KokoroTts`] is gated on the
//! `VOKRA_KOKORO_GGUF` environment variable and skips cleanly when it is
//! unset (e.g. in CI). The fixture-only tests (manifest read-back, shape /
//! length checks) run everywhere.
//!
//! # `mode = placeholder` vs `mode = full`
//!
//! The reference dumper currently ships `mode = placeholder` fixtures (seed-
//! derived, shape-correct tensors) because a from-scratch NumPy reference of
//! Kokoro's full forward is a separate WP. In placeholder mode, this harness
//! runs only **shape / length checks** — the byte-level parity assertion is
//! skipped with a clearly-labelled `eprintln!`. When the dumper is upgraded
//! to `mode = full` (a real NumPy re-forward), byte-level parity kicks in
//! automatically with no test-code change.

#![allow(clippy::items_after_statements)]

use std::collections::HashMap;
use std::path::{Path, PathBuf};

const ATOL: f32 = 0.01;

/// Fixture dir for kokoro (repo-root-relative `tests/parity/kokoro/`).
fn fixtures_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR = <repo>/crates/vokra-models.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("parity")
        .join("kokoro")
}

fn read_f32(name: &str) -> Vec<f32> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 4, 0, "{name}: not a whole number of f32");
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn read_i64(name: &str) -> Vec<i64> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 8, 0, "{name}: not a whole number of i64");
    bytes
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes([c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7]]))
        .collect()
}

fn manifest() -> HashMap<String, String> {
    let text = std::fs::read_to_string(fixtures_dir().join("manifest.txt")).expect("manifest");
    let mut m = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            m.insert(k.trim().to_owned(), v.trim().to_owned());
        }
    }
    m
}

fn man_usize(m: &HashMap<String, String>, k: &str) -> usize {
    m.get(k)
        .unwrap_or_else(|| panic!("manifest missing key {k}"))
        .parse()
        .unwrap_or_else(|_| panic!("manifest {k} not usize"))
}

/// Element-wise closeness with a diagnostic on the worst offender (identical
/// convention to `parity_whisper.rs`).
#[allow(dead_code)]
fn assert_close(got: &[f32], expected: &[f32], ctx: &str) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{ctx}: length {} != expected {}",
        got.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0usize;
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        let d = (g - e).abs();
        if d > worst {
            worst = d;
            worst_i = i;
        }
    }
    eprintln!(
        "[parity] {ctx}: max |Δ| = {worst:.3e} over {} elems (atol {ATOL})",
        got.len()
    );
    assert!(
        worst <= ATOL,
        "{ctx}: max |Δ| = {worst} at index {worst_i} (got {} vs {}) exceeds atol {ATOL}",
        got[worst_i],
        expected[worst_i]
    );
}

/// Skip cleanly when the fixture dir is absent (fresh checkout without the
/// dumper being run yet). This keeps CI green even before the fixtures land.
fn fixtures_present() -> bool {
    fixtures_dir().is_dir() && fixtures_dir().join("manifest.txt").is_file()
}

// -----------------------------------------------------------------------------
// Fixture-only tests (no GGUF required, run on every PR)
// -----------------------------------------------------------------------------

/// Manifest → known-shape cross-check. Guarantees the dumper's shape contract
/// (what the Rust side depends on) is preserved across regenerations. Runs
/// wherever the fixture is present.
#[test]
fn manifest_shapes_are_self_consistent() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}. Run tools/parity/dump_kokoro_reference.py.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();

    // Every dimensional key the harness relies on must be present.
    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let dec_frames = man_usize(&m, "dec_frames");
    let hidden_dim = man_usize(&m, "hidden_dim");
    let style_dim = man_usize(&m, "style_dim");
    let mel_channels = man_usize(&m, "mel_channels");
    let pcm_len = man_usize(&m, "pcm_len");
    let prosody_channels = man_usize(&m, "prosody_channels");

    // Dumper contract: NUM_PHONEMES / ENC_POS / DEC_FRAMES / PCM_LEN /
    // PROSODY_CHANNELS are Python-side constants; they must stay positive.
    assert!(num_phonemes > 0, "num_phonemes > 0");
    assert!(enc_pos > 0, "enc_pos > 0");
    assert!(dec_frames > 0, "dec_frames > 0");
    assert!(pcm_len > 0, "pcm_len > 0");
    assert!(hidden_dim > 0, "hidden_dim > 0");
    assert!(style_dim > 0, "style_dim > 0");
    assert!(mel_channels > 0, "mel_channels > 0");
    assert_eq!(prosody_channels, 2, "prosody = (duration, F0/energy)");
}

/// Binary length ↔ manifest cross-check. Catches a partially-written or
/// mismatched fixture set before any parity comparison runs.
#[test]
fn fixture_binaries_match_manifest_lengths() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let dec_frames = man_usize(&m, "dec_frames");
    let hidden_dim = man_usize(&m, "hidden_dim");
    let style_dim = man_usize(&m, "style_dim");
    let mel_channels = man_usize(&m, "mel_channels");
    let pcm_len = man_usize(&m, "pcm_len");
    let prosody_channels = man_usize(&m, "prosody_channels");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes, "phoneme_ids.i64 length");
    for (i, id) in ids.iter().enumerate() {
        assert!(*id >= 0, "phoneme_ids[{i}] = {id} < 0");
    }

    let style = read_f32("style.f32");
    assert_eq!(style.len(), style_dim, "style.f32 length");

    let enc = read_f32("text_encoder.f32");
    assert_eq!(enc.len(), enc_pos * hidden_dim, "text_encoder.f32 length");

    let pros = read_f32("prosody.f32");
    assert_eq!(pros.len(), enc_pos * prosody_channels, "prosody.f32 length");

    let mel = read_f32("mel_pre_istft.f32");
    assert_eq!(
        mel.len(),
        dec_frames * mel_channels,
        "mel_pre_istft.f32 length"
    );

    let pcm = read_f32("pcm.f32");
    assert_eq!(pcm.len(), pcm_len, "pcm.f32 length");
}

/// Manifest mode marker. In `placeholder`, byte-level parity is intentionally
/// skipped by the gated tests below; in `full`, they run. This test just
/// documents which mode the current fixture set encodes, visible with
/// `--nocapture`.
#[test]
fn manifest_declares_mode() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let mode = m
        .get("mode")
        .cloned()
        .unwrap_or_else(|| "placeholder".to_owned());
    eprintln!("[parity_kokoro] fixture mode = {mode}");
    assert!(
        matches!(mode.as_str(), "placeholder" | "full"),
        "mode must be `placeholder` or `full`, got {mode:?}"
    );
}

// -----------------------------------------------------------------------------
// GGUF-gated tests (skip cleanly without `VOKRA_KOKORO_GGUF`)
// -----------------------------------------------------------------------------

/// Loads a converted Kokoro voice GGUF referenced by `VOKRA_KOKORO_GGUF`, or
/// `None` to skip. Also skips when the fixture dir is missing (we need the
/// manifest / phoneme ids / style to drive a forward).
fn load_gguf_path() -> Option<std::ffi::OsString> {
    if !fixtures_present() {
        return None;
    }
    std::env::var_os("VOKRA_KOKORO_GGUF")
}

/// End-to-end shape parity: the native `synthesize_phonemes` output shape
/// (post-iSTFT PCM) must be consistent with the manifest's `sample_rate`,
/// `num_phonemes`, and the reference dumper's per-phoneme frame budget. Byte-
/// level parity requires `mode = full` (skipped otherwise, with a note).
#[test]
fn e2e_forward_matches_reference_shape() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!(
            "[parity_kokoro] SKIP: set VOKRA_KOKORO_GGUF to a converted Kokoro voice \
             GGUF to run the end-to-end forward parity."
        );
        return;
    };
    let m = manifest();
    let num_phonemes = man_usize(&m, "num_phonemes");
    let style_dim = man_usize(&m, "style_dim");
    let sample_rate = man_usize(&m, "sample_rate");
    let mode = m
        .get("mode")
        .cloned()
        .unwrap_or_else(|| "placeholder".to_owned());

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);
    let style = read_f32("style.f32");
    assert_eq!(style.len(), style_dim);

    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!(
            "load VOKRA_KOKORO_GGUF = {gguf:?}: {e}. Convert via \
             `vokra-cli convert --model kokoro-82m ...` first."
        )
    });

    // The native forward returns `SynthesizedAudio { samples, sample_rate }`.
    // The parity contract here is:
    //   * shape / length matches the reference dumper's `pcm.f32`, and
    //   * (mode = full only) byte-level closeness at ATOL.
    let ref_pcm = read_f32("pcm.f32");
    assert!(!ref_pcm.is_empty());

    let audio = tts
        .synthesize_phonemes(&ids, None, Some(&style), 0.0, 1.0)
        .expect("kokoro forward");

    // Sample-rate cross-check: dumper's manifest must agree with the loaded
    // voice's declared sample rate (FR-EX-08: a silent mismatch would mean
    // the fixture is for a *different* voice than the GGUF under test).
    assert_eq!(
        audio.sample_rate as usize, sample_rate,
        "native sample rate {} Hz != manifest {} Hz",
        audio.sample_rate, sample_rate,
    );

    // Shape check: the reference dump caps PCM at `pcm_len`, and the native
    // forward's actual length must not be *less* than that (dumper caps, not
    // truncates the native output). If more, the check compares the leading
    // slice.
    assert!(
        audio.samples.len() >= ref_pcm.len(),
        "native PCM length {} < reference {}",
        audio.samples.len(),
        ref_pcm.len()
    );
    eprintln!(
        "[parity_kokoro] shape OK: native {} samples, reference {} samples, sr {sample_rate} Hz",
        audio.samples.len(),
        ref_pcm.len()
    );

    if mode == "placeholder" {
        eprintln!(
            "[parity_kokoro] SKIP byte-level parity: manifest mode = placeholder. \
             Regenerate fixtures with a `mode = full` dumper to enable."
        );
        return;
    }

    assert_close(&audio.samples[..ref_pcm.len()], &ref_pcm, "kokoro pcm");
}
