//! Independent real-checkpoint parity for `facebook/wav2vec2-base-960h`.
//!
//! The committed fixture is generated by
//! `tools/parity/wav2vec2_ctc_dump_reference.py`, which runs the pinned
//! official Transformers model. The 361 MiB public GGUF is intentionally not
//! committed; set `VOKRA_WAV2VEC2_BASE_GGUF` to run the real-checkpoint leg.

use std::path::Path;

use vokra_models::wav2vec2_ctc::Wav2Vec2Ctc;

const PCM_BYTES: &[u8] = include_bytes!("fixtures/wav2vec2_ctc/pcm.f32.bin");
const ENCODER_BYTES: &[u8] = include_bytes!("fixtures/wav2vec2_ctc/encoder.f32.bin");
const LOGITS_BYTES: &[u8] = include_bytes!("fixtures/wav2vec2_ctc/logits.f32.bin");
const TOKEN_BYTES: &[u8] = include_bytes!("fixtures/wav2vec2_ctc/tokens.u32.bin");
const TEXT: &str = include_str!("fixtures/wav2vec2_ctc/text.txt");

// Registered before comparing the native implementation with the fixture.
// A failure is investigated; these bounds are not widened to fit an observed
// result.
const FP32_MAX_ABS_BOUND: f32 = 0.01;
const FP32_MEAN_ABS_BOUND: f32 = 0.001;

fn decode_f32(bytes: &[u8]) -> Vec<f32> {
    assert_eq!(bytes.len() % 4, 0, "f32 fixture is truncated");
    bytes
        .chunks_exact(4)
        .map(|chunk| f32::from_le_bytes(chunk.try_into().unwrap()))
        .collect()
}

fn decode_u32(bytes: &[u8]) -> Vec<u32> {
    assert_eq!(bytes.len() % 4, 0, "u32 fixture is truncated");
    bytes
        .chunks_exact(4)
        .map(|chunk| u32::from_le_bytes(chunk.try_into().unwrap()))
        .collect()
}

fn compare(label: &str, actual: &[f32], expected: &[f32]) {
    assert_eq!(actual.len(), expected.len(), "{label} length");
    let (max_index, max_abs) = actual
        .iter()
        .zip(expected)
        .enumerate()
        .map(|(index, (left, right))| (index, (left - right).abs()))
        .max_by(|left, right| left.1.total_cmp(&right.1))
        .expect("non-empty parity tensor");
    let mean_abs = actual
        .iter()
        .zip(expected)
        .map(|(left, right)| (left - right).abs())
        .sum::<f32>()
        / actual.len() as f32;
    eprintln!(
        "Wav2Vec2 {label}: max_abs={max_abs:.9e} at {max_index} (actual={:.9e}, \
         reference={:.9e}), mean_abs={mean_abs:.9e}",
        actual[max_index], expected[max_index]
    );
    assert!(
        max_abs <= FP32_MAX_ABS_BOUND,
        "{label} max_abs={max_abs:.9e} exceeds {FP32_MAX_ABS_BOUND:.9e}"
    );
    assert!(
        mean_abs <= FP32_MEAN_ABS_BOUND,
        "{label} mean_abs={mean_abs:.9e} exceeds {FP32_MEAN_ABS_BOUND:.9e}"
    );
}

#[test]
fn committed_reference_has_pinned_shape_and_finite_values() {
    let pcm = decode_f32(PCM_BYTES);
    let encoder = decode_f32(ENCODER_BYTES);
    let logits = decode_f32(LOGITS_BYTES);
    assert_eq!(pcm.len(), 32_000);
    assert_eq!(encoder.len(), 99 * 768);
    assert_eq!(logits.len(), 99 * 32);
    assert_eq!(decode_u32(TOKEN_BYTES).len(), 25);
    assert_eq!(TEXT.trim_end(), "FELL MY FELLOW AMERICANS");
    assert!(
        pcm.iter()
            .chain(&encoder)
            .chain(&logits)
            .all(|v| v.is_finite()),
        "reference fixture must contain only finite values"
    );
}

#[test]
fn public_base_gguf_matches_official_encoder_logits_tokens_and_text() {
    let Some(path) = std::env::var_os("VOKRA_WAV2VEC2_BASE_GGUF") else {
        eprintln!(
            "[parity_wav2vec2_ctc_real] SKIP: set VOKRA_WAV2VEC2_BASE_GGUF to \
             the public vokra/wav2vec2-base-960h GGUF"
        );
        return;
    };
    let model = Wav2Vec2Ctc::from_gguf(Path::new(&path)).expect("bind public Wav2Vec2 GGUF");
    assert_eq!(model.config().model_id, "wav2vec2-base-960h");
    assert!(!model.legacy_metadata_repaired());

    let pcm = decode_f32(PCM_BYTES);
    let expected_encoder = decode_f32(ENCODER_BYTES);
    let expected_logits = decode_f32(LOGITS_BYTES);
    let expected_tokens = decode_u32(TOKEN_BYTES);
    let expected_text = TEXT.trim_end();

    let (encoder, frames) = model.encode_features(&pcm).expect("native CPU encoder");
    assert_eq!(frames, 99);
    compare("CPU encoder vs official", &encoder, &expected_encoder);

    let (logits, logits_frames) = model.logits(&pcm).expect("native CPU CTC logits");
    assert_eq!(logits_frames, frames);
    compare("CPU logits vs official", &logits, &expected_logits);
    assert_eq!(
        model.transcribe_tokens(&pcm).expect("native CPU CTC ids"),
        expected_tokens,
        "collapsed CTC token ids"
    );
    assert_eq!(
        model.transcribe_text(&pcm).expect("native CPU CTC text"),
        expected_text,
        "official CTC vocabulary text"
    );

    #[cfg(all(feature = "metal", target_os = "macos"))]
    {
        use vokra_core::BackendKind;

        let metal = Wav2Vec2Ctc::from_gguf(Path::new(&path))
            .expect("bind public Wav2Vec2 GGUF for Metal")
            .with_backend(BackendKind::Metal);
        let (metal_encoder, metal_frames) =
            metal.encode_features(&pcm).expect("native Metal encoder");
        assert_eq!(metal_frames, frames);
        compare("Metal encoder vs CPU", &metal_encoder, &encoder);
        let (metal_logits, metal_logits_frames) = metal.logits(&pcm).expect("Metal CTC logits");
        assert_eq!(metal_logits_frames, frames);
        compare("Metal logits vs CPU", &metal_logits, &logits);
        assert_eq!(
            metal.transcribe_tokens(&pcm).expect("Metal CTC ids"),
            expected_tokens,
            "Metal collapsed CTC token ids"
        );
    }
}
