//! Voxtral (Mistral) numerical parity vs the upstream reference
//! (M3-10-T19 / T20).
//!
//! # Fixture layout
//!
//! Fixtures live in `tests/parity/voxtral/` and are regenerated by
//! `tools/parity/dump_voxtral_reference.py` (fp32 + eager upstream
//! `transformers.models.voxtral` tower/projector + the checkpoint's Llama
//! text decoder streamed layer-at-a-time — bitwise-proven against
//! `LlamaModel` by the dumper's mandatory self-check — on the real
//! `mistralai/Voxtral-Mini-3B-2507` BF16 shards and the committed
//! `tests/fixtures/audio/jfk-30s.wav`). The committed set is BOUNDED
//! (whisper fixture-size precedent; full-size Voxtral tensors are ~7.7 MB
//! each — the full-size taps stay uncommitted behind
//! `voxtral_tower_parity.rs`'s `VOKRA_VOXTRAL_REF_DIR` gate):
//!
//! | file | shape |
//! |---|---|
//! | `input_pcm.f32` | `[n_samples]` raw 16 kHz mono (unpadded) |
//! | `log_mel.f32.bin` | `[n_mels, mel_frames]` first mel frames |
//! | `audio_encoder_out.f32.bin` | `[enc_pos, d_audio]` first encoder rows |
//! | `soft_prefix.f32.bin` | `[prefix_rows, d_text]` first projector rows |
//! | `text_decoder_step_out.f32.bin` | `[vocab_size]` last-prompt-position logits |
//! | `asr_tokens.i64.bin` | greedy transcription ids (EOS included) |
//! | `manifest.txt` | shapes / prompt ids / greedy ids / provenance |
//!
//! # Gate posture (M3-10-T20)
//!
//! - **Fixture-only tests** run wherever the fixture is present (committed →
//!   every PR): manifest ↔ binary cross-checks, cheap. Absent fixture →
//!   clean skip with a diagnostic, never a fabricated pass.
//! - **Real-checkpoint tests** are additionally gated on
//!   `VOKRA_VOXTRAL_GGUF` (a converted real GGUF, ~9.4 GB — never
//!   committed) and skip when unset, same posture as `parity_whisper.rs`.
//!   The decoder leg decodes the 3B text weights to f32 (~16 GB — macOS
//!   compression/swap territory on 16 GB machines): run it solo, e.g.
//!   `VOKRA_VOXTRAL_GGUF=… cargo test --release -p vokra-models --test
//!   parity_voxtral -- --test-threads=1 --nocapture`.
//!
//! # Honest atol derivation (2026-07-19 measured run, M1 iMac)
//!
//! The GGUF stores the upstream BF16 weights verbatim (BF16 → f32 widening
//! is exact) and the reference runs in fp32 over the same widened weights,
//! so deltas measure accumulation-order divergence only, growing with depth
//! (32 tower blocks; +30 decoder blocks for the logits tap). Unlike
//! `voxtral_tower_parity.rs` (which feeds both sides the SAME upstream mel),
//! these legs run Vokra's OWN mel front-end, so the measured deltas include
//! front-end drift propagated through the full stack — the honest e2e
//! number. Each `ATOL_*` is the measured max |Δ| rounded up ×~2 (the
//! project's honest-parity convention — never tuned to force a pass; see
//! `feedback-honest-parity-atol`). Measured values are recorded on each
//! constant.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use vokra_core::BackendKind;
use vokra_models::voxtral::{
    AudioAdapter, AudioEncoder, TextDecoder, TextDecoderSession, VOXTRAL_HOT_OPS, VoxtralConfig,
    audio_encoder,
};

/// Vokra's own log-mel front-end vs the upstream `WhisperFeatureExtractor`
/// mel (first `mel_frames` frames). Measured TBD-MEL (2026-07-19).
const ATOL_MEL: f32 = 5e-5;
/// Encoder final hidden, first `enc_pos` rows, from OWN mel. Measured
/// TBD-ENC (values span ±19 after the final LN).
const ATOL_ENC: f32 = 1.5e-3;
/// Post-projector soft prefix, first `prefix_rows` rows, from OWN mel.
/// Measured TBD-PREFIX (the projector re-normalizes into ±2.8).
const ATOL_PREFIX: f32 = 6e-5;
/// Decoder logits at the last transcription-prompt position, OWN mel + OWN
/// tower + OWN projector + 30 decoder layers deep — the deepest committed
/// tap. Measured TBD-LOGITS.
const ATOL_LOGITS: f32 = 1e-2;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("parity")
        .join("voxtral")
}

fn fixtures_present() -> bool {
    fixtures_dir().is_dir() && fixtures_dir().join("manifest.txt").is_file()
}

fn manifest() -> HashMap<String, String> {
    let text = std::fs::read_to_string(fixtures_dir().join("manifest.txt")).expect("manifest");
    let mut m = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            m.insert(k.trim().to_owned(), v.trim().to_owned());
        }
    }
    m
}

fn man_usize(m: &HashMap<String, String>, k: &str) -> usize {
    m.get(k)
        .unwrap_or_else(|| panic!("manifest missing key {k}"))
        .parse()
        .unwrap_or_else(|_| panic!("manifest {k} not usize"))
}

fn man_u32s(m: &HashMap<String, String>, k: &str) -> Vec<u32> {
    m.get(k)
        .unwrap_or_else(|| panic!("manifest missing key {k}"))
        .split_whitespace()
        .map(|t| {
            t.parse()
                .unwrap_or_else(|_| panic!("manifest {k}: bad u32 {t:?}"))
        })
        .collect()
}

fn read_f32(name: &str) -> Vec<f32> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 4, 0, "{name}: not a whole number of f32");
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

/// Reads the little-endian i64 greedy-token blob as `u32` ids (every real
/// token id fits; an out-of-range record is a corrupt fixture → panic).
fn read_tokens_i64(name: &str) -> Vec<u32> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 8, 0, "{name}: not a whole number of i64");
    bytes
        .chunks_exact(8)
        .map(|c| {
            let v = i64::from_le_bytes(c.try_into().unwrap());
            u32::try_from(v).unwrap_or_else(|_| panic!("{name}: id {v} out of u32 range"))
        })
        .collect()
}

/// Element-wise closeness with a diagnostic on the worst offender. The
/// `[parity_voxtral]` line reports the measured margin (visible with
/// `--nocapture`) so atol headroom stays measurable, not just pass/fail.
fn assert_close(got: &[f32], expected: &[f32], ctx: &str, atol: f32) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{ctx}: length {} != expected {}",
        got.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0usize;
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        assert!(g.is_finite(), "{ctx}: non-finite runtime value at {i}");
        let d = (g - e).abs();
        if d > worst {
            worst = d;
            worst_i = i;
        }
    }
    eprintln!(
        "[parity_voxtral] {ctx}: max |Δ| = {worst:.3e} over {} elems (atol {atol:.1e})",
        got.len()
    );
    assert!(
        worst <= atol,
        "{ctx}: max |Δ| = {worst} at index {worst_i} (got {} vs {}) exceeds atol {atol} — \
         do NOT loosen this bound to pass; localize the divergence",
        got[worst_i],
        expected[worst_i]
    );
}

// -----------------------------------------------------------------------------
// Fixture-only tests (no GGUF required, run on every PR when fixture present)
// -----------------------------------------------------------------------------

/// Manifest → known-shape cross-check, including the slice/full-dimension
/// couplings the dumper guarantees.
#[test]
fn manifest_shapes_are_self_consistent() {
    if !fixtures_present() {
        eprintln!(
            "[parity_voxtral] SKIP: no fixture dir at {:?}. Run tools/parity/dump_voxtral_reference.py.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let n_mels = man_usize(&m, "n_mels");
    let mel_frames = man_usize(&m, "mel_frames");
    let n_frames = man_usize(&m, "n_frames");
    let enc_pos = man_usize(&m, "enc_pos");
    let n_ctx = man_usize(&m, "n_ctx");
    let d_audio = man_usize(&m, "d_audio");
    let frame_stack = man_usize(&m, "frame_stack");
    let prefix_rows = man_usize(&m, "prefix_rows");
    let n_audio_tokens = man_usize(&m, "n_audio_tokens");
    let d_text = man_usize(&m, "d_text");
    let vocab_size = man_usize(&m, "vocab_size");

    assert!(n_mels > 0 && d_audio > 0 && d_text > 0 && vocab_size > 0);
    assert!(
        mel_frames > 0 && mel_frames <= n_frames,
        "mel slice must fit the full frame count"
    );
    assert!(
        enc_pos > 0 && enc_pos <= n_ctx,
        "encoder slice must fit n_ctx"
    );
    // Conv stem halves the mel frames into encoder positions.
    assert_eq!(n_frames, 2 * n_ctx, "n_frames = 2·n_ctx (conv stride)");
    // The soft-prefix slice is the frame-stack of the encoder slice.
    assert_eq!(
        enc_pos,
        prefix_rows * frame_stack,
        "enc_pos = prefix_rows·frame_stack"
    );
    // The prompt's [AUDIO] run is the frame-stack of the full encoder.
    assert_eq!(
        n_audio_tokens,
        n_ctx / frame_stack,
        "n_audio_tokens = n_ctx / frame_stack"
    );
    // Prompt segments exist and greedy is non-empty and EOS-terminated.
    let pre = man_u32s(&m, "pre_audio");
    let post = man_u32s(&m, "post_audio");
    let greedy = man_u32s(&m, "greedy_tokens");
    let eos: u32 = man_u32s(&m, "eos")[0];
    assert!(!pre.is_empty() && !post.is_empty(), "prompt segments");
    assert!(!greedy.is_empty(), "greedy tokens");
    assert_eq!(
        *greedy.last().unwrap(),
        eos,
        "committed greedy sequence must be EOS-terminated"
    );
}

/// Binary length ↔ manifest cross-check for every committed blob, plus the
/// asr_tokens ↔ manifest greedy-id identity.
#[test]
fn fixture_binaries_match_manifest_lengths() {
    if !fixtures_present() {
        eprintln!(
            "[parity_voxtral] SKIP: no fixture dir at {:?}.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let n_mels = man_usize(&m, "n_mels");
    let mel_frames = man_usize(&m, "mel_frames");
    let enc_pos = man_usize(&m, "enc_pos");
    let d_audio = man_usize(&m, "d_audio");
    let prefix_rows = man_usize(&m, "prefix_rows");
    let d_text = man_usize(&m, "d_text");
    let vocab_size = man_usize(&m, "vocab_size");
    let n_samples = man_usize(&m, "n_samples");

    assert_eq!(read_f32("input_pcm.f32").len(), n_samples, "input_pcm");
    assert_eq!(
        read_f32("log_mel.f32.bin").len(),
        n_mels * mel_frames,
        "log_mel length"
    );
    assert_eq!(
        read_f32("audio_encoder_out.f32.bin").len(),
        enc_pos * d_audio,
        "audio_encoder_out length"
    );
    assert_eq!(
        read_f32("soft_prefix.f32.bin").len(),
        prefix_rows * d_text,
        "soft_prefix length"
    );
    assert_eq!(
        read_f32("text_decoder_step_out.f32.bin").len(),
        vocab_size,
        "text_decoder_step_out length"
    );
    assert_eq!(
        read_tokens_i64("asr_tokens.i64.bin"),
        man_u32s(&m, "greedy_tokens"),
        "asr_tokens.i64.bin must be exactly the manifest greedy ids"
    );
}

// -----------------------------------------------------------------------------
// GGUF-gated tests (real Voxtral checkpoint, skip when env unset)
// -----------------------------------------------------------------------------

/// Load the Voxtral GGUF path from `VOKRA_VOXTRAL_GGUF`, or skip.
fn require_voxtral_gguf() -> Option<PathBuf> {
    std::env::var_os("VOKRA_VOXTRAL_GGUF").map(PathBuf::from)
}

/// Shared tower path for both gated legs: own mel from the committed PCM →
/// full 32-layer tower → ×frame_stack projector. Returns
/// `(own_mel, encoder_hidden, encoder_n_ctx, soft_prefix)`.
fn run_own_tower(
    file: &vokra_core::gguf::GgufFile,
    cfg: &VoxtralConfig,
    n_frames: usize,
) -> (Vec<f32>, Vec<f32>, usize, Vec<f32>) {
    let pcm = read_f32("input_pcm.f32");
    let mel = vokra_models::whisper::mel::log_mel(&pcm, cfg.audio.n_mels);
    assert_eq!(
        mel.len(),
        cfg.audio.n_mels * n_frames,
        "own mel must cover the full {n_frames}-frame window"
    );

    let encoder = AudioEncoder::load(file, cfg).expect("bind the 32-layer tower");
    assert_eq!(encoder.n_layer(), cfg.audio.n_layer, "full stack bound");
    let adapter = AudioAdapter::from_gguf(file).expect("bind the projector");
    assert!(
        adapter.is_active(),
        "real GGUF must carry an active adapter"
    );

    let compute = vokra_models::compute::Compute::for_backend(BackendKind::Cpu, VOXTRAL_HOT_OPS)
        .expect("cpu compute");
    let (out, _taps) =
        audio_encoder::forward_with_layer_taps(&compute, cfg, &encoder, &mel, n_frames, &[])
            .expect("tower forward");
    let prefix = adapter
        .apply(&compute, &out.hidden, out.n_ctx, out.hidden_dim)
        .expect("projector forward");
    (mel, out.hidden, out.n_ctx, prefix)
}

/// Own mel + tower + projector vs the committed bounded slices (the
/// committed-fixture flavor of `voxtral_tower_parity.rs`, e2e from the PCM).
#[test]
fn tower_projector_and_own_mel_match_committed_fixtures() {
    let Some(gguf) = require_voxtral_gguf() else {
        eprintln!(
            "[parity_voxtral] SKIP tower leg: set VOKRA_VOXTRAL_GGUF to a converted real \
             Voxtral GGUF to enable."
        );
        return;
    };
    if !fixtures_present() {
        eprintln!("[parity_voxtral] SKIP tower leg: no fixture dir.");
        return;
    }
    let m = manifest();
    let file = vokra_mmap::open_gguf(&gguf).expect("mmap-parse the Voxtral GGUF");
    let cfg = VoxtralConfig::from_gguf(&file).expect("read vokra.voxtral.* hparams");

    // The manifest and the GGUF must describe the same architecture.
    assert_eq!(cfg.audio.n_mels, man_usize(&m, "n_mels"), "n_mels");
    assert_eq!(cfg.audio.hidden_dim, man_usize(&m, "d_audio"), "d_audio");
    assert_eq!(cfg.audio.n_ctx, man_usize(&m, "n_ctx"), "n_ctx");
    assert_eq!(cfg.text.hidden_dim, man_usize(&m, "d_text"), "d_text");
    assert_eq!(
        cfg.text.vocab_size,
        man_usize(&m, "vocab_size"),
        "vocab_size"
    );

    let n_frames = man_usize(&m, "n_frames");
    let mel_frames = man_usize(&m, "mel_frames");
    let enc_pos = man_usize(&m, "enc_pos");
    let prefix_rows = man_usize(&m, "prefix_rows");
    let (mel, hidden, n_ctx, prefix) = run_own_tower(&file, &cfg, n_frames);

    // Front-end: first mel_frames of every mel row (row-major [n_mels, n_frames]).
    let reference = read_f32("log_mel.f32.bin");
    let mut got = Vec::with_capacity(cfg.audio.n_mels * mel_frames);
    for row in 0..cfg.audio.n_mels {
        got.extend_from_slice(&mel[row * n_frames..row * n_frames + mel_frames]);
    }
    assert_close(&got, &reference, "own_log_mel (slice)", ATOL_MEL);

    // Tower: first enc_pos encoder rows.
    assert_eq!(n_ctx, man_usize(&m, "n_ctx"), "encoder n_ctx");
    assert_close(
        &hidden[..enc_pos * cfg.audio.hidden_dim],
        &read_f32("audio_encoder_out.f32.bin"),
        "audio_encoder_out (slice)",
        ATOL_ENC,
    );

    // Projector: first prefix_rows soft-prefix rows.
    assert_eq!(
        prefix.len(),
        man_usize(&m, "n_audio_tokens") * cfg.text.hidden_dim,
        "soft prefix rows"
    );
    assert_close(
        &prefix[..prefix_rows * cfg.text.hidden_dim],
        &read_f32("soft_prefix.f32.bin"),
        "soft_prefix (slice)",
        ATOL_PREFIX,
    );
}

/// Full transcription-prompt replay (pre ids → soft prefix → post ids)
/// through the real 3B text decoder: last-position logits vs the committed
/// reference, then the greedy continuation vs the committed ids — the
/// committed-fixture ASR e2e (M3-10-T19/T20).
///
/// HEAVY: decodes the text weights to f32 (~16 GB — swap territory on 16 GB
/// machines); run solo with `--test-threads=1`. One test carries both the
/// step-logits and greedy checks so the decoder is loaded exactly once.
#[test]
fn decoder_step_logits_and_greedy_match_committed_fixtures() {
    let Some(gguf) = require_voxtral_gguf() else {
        eprintln!(
            "[parity_voxtral] SKIP decoder leg: set VOKRA_VOXTRAL_GGUF to a converted real \
             Voxtral GGUF to enable (HEAVY: ~16 GB decoded f32 weights)."
        );
        return;
    };
    if !fixtures_present() {
        eprintln!("[parity_voxtral] SKIP decoder leg: no fixture dir.");
        return;
    }
    let m = manifest();
    let file = vokra_mmap::open_gguf(&gguf).expect("mmap-parse the Voxtral GGUF");
    let cfg = VoxtralConfig::from_gguf(&file).expect("read vokra.voxtral.* hparams");

    let n_frames = man_usize(&m, "n_frames");
    let (_mel, _hidden, _n_ctx, prefix) = run_own_tower(&file, &cfg, n_frames);
    let n_audio_tokens = man_usize(&m, "n_audio_tokens");
    assert_eq!(
        prefix.len(),
        n_audio_tokens * cfg.text.hidden_dim,
        "soft prefix rows"
    );

    let pre = man_u32s(&m, "pre_audio");
    let post = man_u32s(&m, "post_audio");
    let eos = man_u32s(&m, "eos")[0];
    let max_new = man_usize(&m, "max_new");
    let expected_logits = read_f32("text_decoder_step_out.f32.bin");
    let expected_tokens = read_tokens_i64("asr_tokens.i64.bin");

    let decoder = TextDecoder::load(&file, &cfg).expect("bind the real GQA text decoder");
    let mut session = TextDecoderSession::cpu(&cfg, &decoder).expect("cpu decoder session");

    // Replay the exact transcription-request prompt layout the reference
    // used: pre ids, the [AUDIO] run replaced by the soft-prefix rows, post
    // ids (masked_scatter semantics).
    session.step_into(&pre).expect("pre-audio ids");
    session
        .step_into_with_embed_prefix(&prefix, n_audio_tokens)
        .expect("audio soft prefix");
    session.step_into(&post).expect("post-audio ids");

    assert_close(
        session.last_logits_row(),
        &expected_logits,
        "text_decoder_step_out (last prompt position)",
        ATOL_LOGITS,
    );

    // Greedy continuation — must reproduce the reference ids EXACTLY (argmax
    // decisions dwarf sub-atol per-logit differences; any drift is a bug).
    let mut generated: Vec<u32> = Vec::new();
    loop {
        let next = argmax(session.last_logits_row());
        generated.push(next);
        if next == eos || generated.len() >= max_new {
            break;
        }
        session.step_into(&[next]).expect("greedy step");
    }
    assert_eq!(
        generated, expected_tokens,
        "greedy transcription ids must match the upstream reference exactly"
    );
    eprintln!(
        "[parity_voxtral] greedy: {} ids match the upstream reference exactly (EOS-terminated: {})",
        generated.len(),
        generated.last() == Some(&eos)
    );
}

fn argmax(v: &[f32]) -> u32 {
    let mut best = 0usize;
    let mut best_v = f32::NEG_INFINITY;
    for (i, &x) in v.iter().enumerate() {
        if x > best_v {
            best_v = x;
            best = i;
        }
    }
    u32::try_from(best).expect("vocab fits u32")
}
