//! Xiph RNNoise v0.2 numerical parity harness — env-gated (denoise
//! tier, 2026-08-09 loud-partial forwards wave).
//!
//! Sibling of `parity_rmvpe.rs` / `parity_openwakeword.rs` /
//! `parity_dnsmos.rs`: every test that needs the RNNoise v0.2 GGUF is
//! gated on the [`GGUF_ENV`] environment variable and skips cleanly when
//! unset (never a fabricated pass, memory
//! `[[project-real-weight-eval]]` pattern). Once opted in, every failure
//! is hard: a missing / malformed / wrong-shaped fixture is a loud
//! panic (FR-EX-08).
//!
//! # Fixture recipe (owner-side)
//!
//! Upstream v0.2 embeds 36 trained arrays in `src/rnnoise_data.c` inside
//! the official release tarball. Bridge it to safetensors with the strict
//! `tools/parity/rnnoise_prepare_checkpoint.py` parser, then convert to GGUF:
//!
//! ```text
//! # 1. Fetch upstream v0.2 release tarball from
//! #    github.com/xiph/rnnoise/releases/tag/v0.2
//! # 2. Flatten to safetensors (offline, in a uv-managed venv):
//! uv run python tools/parity/rnnoise_prepare_checkpoint.py \
//!     --input  ~/rnnoise-v0.2/rnnoise-0.2.tar.gz \
//!     --output ~/rnnoise-v02.safetensors
//! # 3. Convert to GGUF:
//! vokra-cli convert --model rnnoise-v0.2 \
//!     --input  ~/rnnoise-v02.safetensors \
//!     --output ~/rnnoise-v02.gguf
//! # 4. Point the parity harness at it:
//! export VOKRA_RNNOISE_V02_REAL_GGUF=~/rnnoise-v02.gguf
//! cargo test -p vokra-models --test parity_rnnoise_v02 -- --nocapture
//! # The still-pending waveform/pitch tier uses a separate explicit opt-in:
//! # export VOKRA_RNNOISE_V02_PITCH_REFERENCE=~/rnnoise-v02-pitch.csv
//! ```
//!
//! # Numeric parity contract
//!
//! The network check consumes four sequential 65-feature frames and compares
//! 32 gains plus VAD against a fixture generated by compiling
//! `rnnoise_v02_network_reference.c` with the unmodified Xiph v0.2 sources.
//! The network bound is `2e-5` max absolute error. The waveform fixture is
//! generated by `rnnoise_v02_waveform_reference.c`, which calls Xiph's public
//! `rnnoise_process_frame` over 16 deterministic frames. It independently
//! covers the high-pass, 32-band/65-feature frontend, pitch downsample and
//! `remove_doubling`, real network, delayed-spectrum gains, and OLA synthesis.
//! Xiph's scalar KISS FFT and Vokra's native real FFT use different butterfly
//! factorizations. Their frontend features differ by about `2e-5`; the trained
//! recurrent network amplifies that into the measured waveform bounds below.

use std::env;
use std::path::Path;

use vokra_core::engines::DenoiseEngine;
use vokra_models::rnnoise::{
    FRAME_SIZE, N_BANDS as V02_N_BANDS, N_FEATURES as V02_N_FEATURES, RnnoiseNetworkState,
    RnnoiseV02, SAMPLE_RATE,
};

/// Env var the owner sets to point the gated harness at a real RNNoise
/// v0.2 GGUF. Absent = skip cleanly (never a fabricated pass). Present =
/// binding: every downstream check hard-fails on any error.
const GGUF_ENV: &str = "VOKRA_RNNOISE_V02_REAL_GGUF";

// ---------------------------------------------------------------------------
// GATED — real RNNoise v0.2 GGUF fixture required
// ---------------------------------------------------------------------------

/// GATED: opens a real RNNoise v0.2 GGUF and verifies the runtime binder and
/// stateful neural forward against the unmodified Xiph C implementation.
///
/// Skips cleanly when [`GGUF_ENV`] is unset. Once set, all failures
/// are hard: a missing / malformed / wrong-arch fixture fails loudly.
///
#[test]
fn parity_rnnoise_v02_gguf_smoke() {
    let Some(gguf_path) = env::var(GGUF_ENV).ok() else {
        eprintln!(
            "{GGUF_ENV} unset — skipping rnnoise v0.2 GGUF parity smoke; \
             this is a clean skip (never a fabricated pass). See the \
             module docs for the fixture recipe."
        );
        return;
    };

    let path = Path::new(&gguf_path);
    assert!(
        path.exists(),
        "opted in with {GGUF_ENV} but path {gguf_path} does not exist — \
         hard fail (FR-EX-08)"
    );

    let model = RnnoiseV02::open(path).expect("bind canonical RNNoise v0.2 GGUF");
    let mut state = RnnoiseNetworkState::default();
    let fixture = include_str!("../../../tools/parity/fixtures/rnnoise_v02_network.csv");
    let mut max_abs = 0.0f32;
    let mut frames = 0usize;
    for (frame_index, line) in fixture.lines().enumerate() {
        let values: Vec<f32> = line
            .split(',')
            .map(|value| value.parse::<f32>().expect("fixture f32"))
            .collect();
        assert_eq!(
            values.len(),
            V02_N_FEATURES + V02_N_BANDS + 1,
            "fixture frame {frame_index} width"
        );
        let features: [f32; V02_N_FEATURES] =
            values[..V02_N_FEATURES].try_into().expect("65 features");
        let actual = model
            .forward_features(&mut state, &features)
            .expect("stateful RNNoise network forward");
        for band in 0..V02_N_BANDS {
            max_abs = max_abs.max((actual.gains[band] - values[V02_N_FEATURES + band]).abs());
        }
        max_abs =
            max_abs.max((actual.vad_probability - values[V02_N_FEATURES + V02_N_BANDS]).abs());
        frames += 1;
    }
    assert_eq!(frames, 4);
    eprintln!("RNNoise v0.2 network parity: frames={frames}, max_abs={max_abs:e}");
    assert!(
        max_abs <= 2e-5,
        "RNNoise network max |Δ| {max_abs:e} exceeds independent Xiph C bound 2e-5"
    );
}

#[cfg(all(feature = "metal", any(target_os = "macos", target_os = "ios")))]
#[test]
fn parity_rnnoise_v02_cpu_metal_matches_xiph_network() {
    let Some(gguf_path) = env::var(GGUF_ENV).ok() else {
        eprintln!("{GGUF_ENV} unset — skipping RNNoise CPU/Metal parity");
        return;
    };
    let path = Path::new(&gguf_path);
    let cpu = RnnoiseV02::open(path).expect("bind RNNoise CPU");
    let metal = RnnoiseV02::open(path)
        .expect("bind RNNoise Metal")
        .with_backend(vokra_core::BackendKind::Metal);
    assert_eq!(cpu.backend(), vokra_core::BackendKind::Cpu);
    assert_eq!(metal.backend(), vokra_core::BackendKind::Metal);

    let fixture = include_str!("../../../tools/parity/fixtures/rnnoise_v02_network.csv");
    let mut cpu_state = RnnoiseNetworkState::default();
    let mut metal_state = RnnoiseNetworkState::default();
    let mut cpu_reference_max = 0.0f32;
    let mut metal_reference_max = 0.0f32;
    let mut cpu_metal_max = 0.0f32;
    for line in fixture.lines() {
        let values: Vec<f32> = line
            .split(',')
            .map(|value| value.parse::<f32>().expect("fixture f32"))
            .collect();
        let features: [f32; V02_N_FEATURES] =
            values[..V02_N_FEATURES].try_into().expect("65 features");
        let cpu_output = cpu.forward_features(&mut cpu_state, &features).unwrap();
        let metal_output = metal.forward_features(&mut metal_state, &features).unwrap();
        for band in 0..V02_N_BANDS {
            let expected = values[V02_N_FEATURES + band];
            cpu_reference_max = cpu_reference_max.max((cpu_output.gains[band] - expected).abs());
            metal_reference_max =
                metal_reference_max.max((metal_output.gains[band] - expected).abs());
            cpu_metal_max =
                cpu_metal_max.max((metal_output.gains[band] - cpu_output.gains[band]).abs());
        }
        let expected_vad = values[V02_N_FEATURES + V02_N_BANDS];
        cpu_reference_max =
            cpu_reference_max.max((cpu_output.vad_probability - expected_vad).abs());
        metal_reference_max =
            metal_reference_max.max((metal_output.vad_probability - expected_vad).abs());
        cpu_metal_max =
            cpu_metal_max.max((metal_output.vad_probability - cpu_output.vad_probability).abs());
    }
    eprintln!(
        "RNNoise CPU/Metal network parity: cpu_ref={cpu_reference_max:e}, \
         metal_ref={metal_reference_max:e}, cpu_metal={cpu_metal_max:e}"
    );
    assert!(cpu_reference_max <= 2e-5);
    // Same fixed FP32 Metal recurrent-network gate used by the other VAD
    // backends. The independent Xiph CPU gate above remains two orders of
    // magnitude tighter, so this cannot replace or weaken source parity.
    assert!(metal_reference_max <= 1e-2);
    assert!(cpu_metal_max <= 1e-2);

    let mut cpu_stream = cpu.stream();
    let mut metal_stream = metal.stream();
    let mut rng = 0x6d2b79f5u32;
    let mut pcm_max = 0.0f32;
    let mut vad_max = 0.0f32;
    for frame_index in 0..16 {
        let input = std::array::from_fn(|index| waveform_sample(&mut rng, frame_index, index));
        let cpu_frame = cpu_stream.process_frame(&input).unwrap();
        let metal_frame = metal_stream.process_frame(&input).unwrap();
        vad_max = vad_max.max((metal_frame.vad_probability - cpu_frame.vad_probability).abs());
        for (&metal_sample, &cpu_sample) in metal_frame.pcm.iter().zip(&cpu_frame.pcm) {
            pcm_max = pcm_max.max((metal_sample - cpu_sample).abs());
        }
    }
    eprintln!("RNNoise CPU/Metal waveform parity: pcm={pcm_max:e}, vad={vad_max:e}");
    assert!(pcm_max <= 1e-2);
    assert!(vad_max <= 1e-2);
}

#[test]
fn parity_rnnoise_v02_waveform_matches_xiph_process_frame() {
    let Some(gguf_path) = env::var(GGUF_ENV).ok() else {
        eprintln!(
            "{GGUF_ENV} unset — skipping rnnoise v0.2 waveform parity; \
             clean skip (never a fabricated pass)."
        );
        return;
    };
    let model = RnnoiseV02::open(&gguf_path).expect("bind canonical RNNoise v0.2 GGUF");
    let mut stream = model.stream();
    let mut rng = 0x6d2b79f5u32;
    let fixture = include_str!("../../../tools/parity/fixtures/rnnoise_v02_waveform.csv");
    let mut max_pcm_abs = 0.0f32;
    let mut max_vad_abs = 0.0f32;
    let mut frames = 0usize;
    for line in fixture.lines() {
        let expected: Vec<f32> = line
            .split(',')
            .map(|value| value.parse::<f32>().expect("waveform fixture f32"))
            .collect();
        assert_eq!(expected.len(), 18);
        let frame_index = expected[0] as usize;
        assert_eq!(frame_index, frames);
        let input = std::array::from_fn(|index| waveform_sample(&mut rng, frame_index, index));
        let actual = stream
            .process_frame(&input)
            .expect("RNNoise waveform frame");
        max_vad_abs = max_vad_abs.max((actual.vad_probability - expected[1]).abs());
        for tap_index in 0..16 {
            let pcm_index = (tap_index * 73 + 19) % FRAME_SIZE;
            max_pcm_abs = max_pcm_abs.max((actual.pcm[pcm_index] - expected[2 + tap_index]).abs());
        }
        frames += 1;
    }
    eprintln!(
        "RNNoise v0.2 waveform parity: frames={frames}, max_pcm_abs={max_pcm_abs:e}, max_vad_abs={max_vad_abs:e}"
    );
    assert_eq!(frames, 16);
    // Measured against the unmodified portable Xiph v0.2 C path:
    // PCM 7.196754e-3, VAD 3.1113923e-3.  The network-only fixture above
    // remains at 2e-5; these wider end-to-end bounds isolate the expected FFT
    // butterfly/order sensitivity rather than hiding neural-weight drift.
    assert!(
        max_pcm_abs <= 1e-2,
        "RNNoise waveform max |PCM Δ| {max_pcm_abs:e} exceeds independent Xiph C bound 1e-2"
    );
    assert!(
        max_vad_abs <= 5e-3,
        "RNNoise waveform max |VAD Δ| {max_vad_abs:e} exceeds independent Xiph C bound 5e-3"
    );

    let mut boxed = model.open_stream(SAMPLE_RATE).expect("48 kHz stream");
    assert!(model.open_stream(16_000).is_err(), "no silent resample");
    let input: Vec<f32> = (0..FRAME_SIZE * 2)
        .map(|index| waveform_sample(&mut rng, 16 + index / FRAME_SIZE, index % FRAME_SIZE))
        .collect();
    let first = boxed.push_pcm(&input).expect("chunked stream");
    boxed.reset();
    let second = boxed.push_pcm(&input).expect("reset stream");
    assert_eq!(
        first, second,
        "reset must reproduce a fresh stream bit-for-bit"
    );
}

fn waveform_sample(state: &mut u32, frame: usize, index: usize) -> f32 {
    let global = frame * FRAME_SIZE + index;
    let phase = global % 240;
    let triangle = if phase < 120 {
        phase as i32 - 60
    } else {
        180 - phase as i32
    };
    let carrier = if global % 16 < 8 { 10_000 } else { -10_000 };
    *state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
    let noise = ((*state >> 16) & 0xffff) as i32 - 32_768;
    if frame == 0 {
        0.0
    } else if frame < 10 {
        (triangle * 320 + carrier + noise / 16) as f32 / 32_768.0
    } else {
        (noise / 2) as f32 / 32_768.0
    }
}
