//! Kokoro-82M numerical parity vs the TRUE upstream reference.
//!
//! Fixtures live in `tests/parity/kokoro/` and are regenerated by
//! `tools/parity/dump_kokoro_reference.py` — since the 2026-07-16 P1
//! fidelity fix that script hooks the REAL upstream `kokoro` pip package
//! (`KModel.forward_with_tokens`), never a re-implementation. (The
//! pre-2026-07-16 dumper was a same-author mirror of the Rust code; its
//! 9/9 "pass" was self-consistency while the synthesized audio was
//! unintelligible — round-trip WER 1.0. See the dumper header.)
//!
//! Default tolerance is FP32 `atol = 0.01` (NFR-QL-01); the three decoder
//! tensors carry measured-and-documented per-tensor bounds (see
//! [`DECODER_MAG_ATOL`]) plus mean-delta gates.
//!
//! The full forward requires the converted **GGUF**, which is too large to
//! commit, so every test that touches [`KokoroTts`] is gated on the
//! `VOKRA_KOKORO_GGUF` environment variable and skips cleanly when it is
//! unset (e.g. in CI). The fixture-only tests (manifest read-back, shape /
//! length checks) run everywhere.
//!
//! # `mode = placeholder` vs `mode = full` (per module)
//!
//! The dumper writes a global `mode = full` marker plus per-module keys
//! `<module>_mode ∈ {placeholder, full}` for `text_encoder`, `bert`,
//! `prosody`, `decoder`. Each gated test below reads only the marker for
//! the module it exercises:
//!
//! * `<module>_mode = placeholder` — shape / length checks only; byte-level
//!   parity is intentionally skipped with a `eprintln!`.
//! * `<module>_mode = full` — byte-level parity vs the reference tensor.
//!   Skipped cleanly when `VOKRA_KOKORO_GGUF` is unset (no Rust forward to
//!   compare against without a real voice GGUF).

#![allow(clippy::items_after_statements)]

use std::collections::HashMap;
use std::path::{Path, PathBuf};

const ATOL: f32 = 0.01;

// ---------------------------------------------------------------------------
// Decoder per-tensor bounds — measured against the TRUE upstream package
// ---------------------------------------------------------------------------
//
// # Why the decoder tensors are not on the default `ATOL` — measured +
// architectural reasoning (honest-parity rule: bound = measured × ~2,
// never tuned-to-green)
//
// The decoder's NSF source path computes `har = [|STFT(s)| ; angle(STFT(s))]`
// from the harmonic source signal and feeds BOTH halves to trained convs
// (upstream `istftnet.py:299-305`). The `angle` half is **discontinuous**:
// atan2 has a branch cut at ±π, and at near-zero-magnitude bins (fixture
// median |z| at flip sites ≈ 1e-5) ANY ulp-level drift in the source signal
// flips the angle by 2π. The Rust source signal tracks upstream to
// `max |Δ| ≈ 1.2e-4` (sin of 10³–10⁴-rad f32 phase arguments across two
// independent libm/FFT stacks — a few ULP of the argument), which still
// flips a handful of near-cut bins; the trained convs then propagate those
// O(2π) feature spikes into bounded logit deltas.
//
// Measured on the fixture input with REFERENCE contours (2026-07-16, M1,
// deterministic-dither fixtures):
//
//   mag   max |Δ| = 2.51e-1   mean |Δ| = 1.26e-2
//   phase max |Δ| = 1.49e-1   mean |Δ| = 5.74e-3
//   pcm   max |Δ| = 1.92e-2   mean |Δ| = 5.51e-4
//
// Bounds are set at ~2× measured. A max-only gate at these levels would be
// weak, so each tensor ALSO carries a mean-|Δ| gate at ~2× the measured
// mean — a systematic error (wrong slope, wrong AdaIN convention, missing
// source path …) moves the mean by orders of magnitude and trips it, while
// the sparse branch-cut spikes do not. Every observed value is printed to
// stderr regardless of PASS / FAIL.
//
// If the source-signal drift is ever driven to bit-exactness (requires
// replicating torch's exact interpolate/cumsum/sin op ordering AND its FFT
// rounding), these bounds should be re-measured and tightened.
//
// OPEN: the first Linux CI run of this suite (2026-07-19) FAILED the pcm max
// gate at 4.34e-2 vs 0.04, while M1 measures 1.92e-2 (deterministic: same
// value and same index across three runs). The bound was NOT widened. The
// measurement is recorded here so whoever investigates starts with it:
//
//                      M1 (NEON)                  Linux CI (x86)
//   pcm buckets   [14994, 13542, 5616, 48, 0, 0]  [17778, 12643, 3694, 85, 0, 0]
//   pcm mean       5.51e-4                         4.31e-4
//   pcm max        1.92e-2 (idx 18663)             4.34e-2 (idx 14645)
//   mag / phase    within bounds                   within bounds
//
// Linux is more accurate in bulk (lower mean, more mass in the smallest
// bucket) and differs only in a handful of spikes, which LOOKS like the
// documented branch-cut mechanism — near-zero-magnitude NSF bins landing
// either side of atan2's cut depending on libm/FFT rounding, so which bin
// spikes is platform-dependent.
//
// That is a hypothesis, not a diagnosis, and it was not enough to justify
// relaxing the gate: (1) there is exactly ONE x86 observation; (2) M5-14
// added AVX2/AVX-512 packed GEMM micro-kernels that have been differentially
// tested against a scalar oracle but never exercised on real x86 hardware in
// this decoder path, so "platform outlier" and "localized kernel error" are
// not yet distinguishable from aggregate statistics; (3) the max gate is
// precisely the one that catches localized corruption (the mean gate catches
// systematic drift), so widening it is the wrong direction of caution on the
// model whose whole failure mode was a parity suite that passed while the
// audio was unintelligible.
//
// 2026-07-19 INVESTIGATION (M1 only — no x86 hardware; Rosetta 2 reports no
// AVX2, so it cannot exercise those kernels). (A) is REFUTED for `pcm`, a
// third mechanism is identified, and (B) is bounded but not closed:
//
// (A) is NOT the pcm mechanism. Mapping both worst bins back through the
//     iSTFT (`center=true` ⇒ sample i ← frames ⌈(i−9)/5⌉..=⌊(i+10)/5⌋) and
//     reading the LINEAR magnitude `exp(x_mag)` there:
//       * M1 worst 18663 → frames 3731..3734, ref |z| ∈ [2.06e-1, 1.82e0],
//         0/44 cells below 1e-3;
//       * x86 worst 14645 → frames 2928..2931, ref |z| ∈ [5.63e-1, 3.53e0],
//         0/44 below 1e-3 — a LOUD region; on M1 |Δ| there is 4.86e-3
//         (rank 359 / 34 200).
//     Globally there is no co-location: min NSF |z| over the contributing
//     frames has median 6.25e-4 for the top-200 pcm deltas vs 7.07e-4 for 200
//     random samples (population 7.30e-4), and samples that DO contain a
//     |z| < 1e-4 NSF bin carry a LOWER max |Δpcm| (1.43e-2) than those that do
//     not (1.92e-2). Branch cuts DO explain the `mag` / `phase` maxima — idx
//     47695 sits at x_mag = −23.8, i.e. |z| ≈ 4.5e-11 — but such cells are
//     inaudible and contribute nothing to pcm. The block above conflated the
//     two tensors; only its mag/phase half survives.
//
// (C) NEW, and the dominant shape: the pcm error tracks SIGNAL AMPLITUDE.
//     Rank corr(|Δ|, local envelope) = 0.82; mean |Δ| climbs monotonically
//     across amplitude deciles from 6.4e-11 to 1.9e-3 (seven orders) while the
//     mean RELATIVE error stays flat at ~1.0–1.3e-2; 87.5 % of the 48 samples
//     above 1e-2 sit in the top amplitude decile. The max is therefore not a
//     spike but the top of a dense plateau (6 samples within 0.9×, 55 within
//     0.5×, 367 within 0.25×), so the argmax INDEX moving between platforms
//     carries little information on its own.
//
// (B) bounded, not closed. `VOKRA_CPU_ISA=scalar` on M1 — which disables the
//     packed GEMM and the NEON transcendental kernels — moves pcm by at most
//     1.53e-6 and does not move the max cell (1.919603e-2 vs 1.919626e-2,
//     both at 18663); `gen_har_source` / `gen_har_spec` stay bit-identical.
//     Every GEMM this decoder issues takes the packed route (traced), so that
//     path IS numerically live here, and the WHOLE SIMD-vs-scalar effect is
//     ~1.5e-6. For (B) to explain x86, its micro-kernel would have to inject
//     ≈2.4e-2 at one cell — ~16 000× the entire NEON SIMD effect, which no
//     correct summation ORDER can produce. "Different rounding in a correct
//     kernel" is therefore untenable, leaving only an actual fault, which
//     stays possible because `gemm_driver::run` reaches only the ACTIVE ISA's
//     micro-kernel — no ARM host can execute the AVX2 / AVX-512 tiles.
//     `vokra-backend-cpu/tests/gemm_packed_parity.rs::
//     packed_matches_both_oracles_at_kokoro_decoder_shapes` closes that on any
//     x86 runner: it drives this decoder's exact traced shapes — including
//     n = 6841, which crosses seven NC=1024 slabs and leaves a ragged
//     697 = 43·16+9 final slab the old grid (max n = 2049, ≤ 2 slabs) never
//     reached — against the legacy kernel (bit-identical) and the scalar
//     oracle.
//
// STILL OPEN: whether x86's 4.34e-2 is a legitimate re-draw of the same
// amplitude-tracking field or a real micro-kernel fault. Note precisely what
// needs explaining: x86 has a LOWER mean (4.31e-4) yet more mass above 1e-2
// (85 vs 48) — better in bulk, heavier in the tail. [`explain_worst_pcm`]
// below now prints, on the FAILURE PATH ONLY, everything needed to settle
// this from a single Linux log. Two further uncontrolled variables to check
// on that run: the CI GGUF is converted on the runner rather than committed,
// and the reference fixtures were dumped once, on M1. This suite is not a
// required check, so it blocks nothing while that is pending.

/// Decoder magnitude-logit max-|Δ| bound (measured 2.51e-1 — see above).
const DECODER_MAG_ATOL: f32 = 0.5;
/// Decoder magnitude-logit mean-|Δ| bound (measured 1.26e-2).
const DECODER_MAG_MEAN_ATOL: f32 = 0.025;
/// Decoder phase-logit max-|Δ| bound (measured 1.49e-1).
const DECODER_PHASE_ATOL: f32 = 0.3;
/// Decoder phase-logit mean-|Δ| bound (measured 5.74e-3).
const DECODER_PHASE_MEAN_ATOL: f32 = 0.012;
/// Decoder PCM max-|Δ| bound (measured 1.92e-2).
const DECODER_PCM_ATOL: f32 = 0.04;
/// Decoder PCM mean-|Δ| bound (measured 5.51e-4).
const DECODER_PCM_MEAN_ATOL: f32 = 0.0012;

/// Linear-magnitude threshold below which a final-spectrum bin is "near zero",
/// so its phase is numerically meaningless and an atan2 branch-cut flip there
/// cannot move the audio.
///
/// `x_mag` is a **log** magnitude — the iSTFT head forms `|z| = exp(x_mag)` —
/// which is why a large `|Δ x_mag|` can be irrelevant: the fixture's worst
/// magnitude cell sits at `x_mag = -23.8`, i.e. `|z| ≈ 4.5e-11`. Measured over
/// the committed reference (2026-07-19, M1), the linear distribution is
/// bimodal and its knee is here — p25 = 1.3e-3, median = 2.1e-1, p95 = 1.4.
/// So 1e-3 separates the ~25 % genuinely-silent bins from those carrying the
/// waveform, which makes the near-zero test in [`explain_worst_pcm`]
/// discriminating rather than vacuous.
const NEAR_ZERO_LINEAR_MAG: f32 = 1e-3;

// NOTE — `prosody_f0` history: the pre-2026-07-16 fixture set carried a
// `PROSODY_F0_ATOL = 0.05` override justified by an "F0_proj ~9×
// amplification × BiLSTM 3e-3 hidden bound" analysis. Against the TRUE
// upstream reference the measured deltas are `hidden = 8.5e-5`,
// `f0 = 3.0e-3`, `n = 5.1e-5` — comfortably inside the default `ATOL =
// 0.01` (3.3× headroom). The old 3e-3 "hidden bound" was dominated by the
// flawed same-author reference, not by the BiLSTM summation order, so the
// override is REMOVED rather than kept as dead tolerance.

/// Fixture dir for kokoro (repo-root-relative `tests/parity/kokoro/`).
fn fixtures_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR = <repo>/crates/vokra-models.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("parity")
        .join("kokoro")
}

fn read_f32(name: &str) -> Vec<f32> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 4, 0, "{name}: not a whole number of f32");
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn read_i64(name: &str) -> Vec<i64> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 8, 0, "{name}: not a whole number of i64");
    bytes
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes([c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7]]))
        .collect()
}

fn manifest() -> HashMap<String, String> {
    let text = std::fs::read_to_string(fixtures_dir().join("manifest.txt")).expect("manifest");
    let mut m = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            m.insert(k.trim().to_owned(), v.trim().to_owned());
        }
    }
    m
}

fn man_usize(m: &HashMap<String, String>, k: &str) -> usize {
    m.get(k)
        .unwrap_or_else(|| panic!("manifest missing key {k}"))
        .parse()
        .unwrap_or_else(|_| panic!("manifest {k} not usize"))
}

/// Element-wise closeness with a diagnostic on the worst offender (identical
/// convention to `parity_whisper.rs`).
#[allow(dead_code)]
fn assert_close(got: &[f32], expected: &[f32], ctx: &str) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{ctx}: length {} != expected {}",
        got.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0usize;
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        let d = (g - e).abs();
        if d > worst {
            worst = d;
            worst_i = i;
        }
    }
    eprintln!(
        "[parity] {ctx}: max |Δ| = {worst:.3e} over {} elems (atol {ATOL})",
        got.len()
    );
    assert!(
        worst <= ATOL,
        "{ctx}: max |Δ| = {worst} at index {worst_i} (got {} vs {}) exceeds atol {ATOL}",
        got[worst_i],
        expected[worst_i]
    );
}

/// Skip cleanly when the fixture dir is absent (fresh checkout without the
/// dumper being run yet). This keeps CI green even before the fixtures land.
fn fixtures_present() -> bool {
    fixtures_dir().is_dir() && fixtures_dir().join("manifest.txt").is_file()
}

// -----------------------------------------------------------------------------
// Fixture-only tests (no GGUF required, run on every PR)
// -----------------------------------------------------------------------------

/// Manifest → known-shape cross-check. Guarantees the dumper's shape contract
/// (what the Rust side depends on) is preserved across regenerations. Runs
/// wherever the fixture is present.
#[test]
fn manifest_shapes_are_self_consistent() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}. Run tools/parity/dump_kokoro_reference.py.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();

    // Every dimensional key the harness relies on must be present.
    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let dec_frames = man_usize(&m, "dec_frames");
    let hidden_dim = man_usize(&m, "hidden_dim");
    let style_dim = man_usize(&m, "style_dim");
    let mel_channels = man_usize(&m, "mel_channels");
    let pcm_len = man_usize(&m, "pcm_len");
    let prosody_channels = man_usize(&m, "prosody_channels");

    // Dumper contract: NUM_PHONEMES / ENC_POS / DEC_FRAMES / PCM_LEN /
    // PROSODY_CHANNELS are Python-side constants; they must stay positive.
    assert!(num_phonemes > 0, "num_phonemes > 0");
    assert!(enc_pos > 0, "enc_pos > 0");
    assert!(dec_frames > 0, "dec_frames > 0");
    assert!(pcm_len > 0, "pcm_len > 0");
    assert!(hidden_dim > 0, "hidden_dim > 0");
    assert!(style_dim > 0, "style_dim > 0");
    assert!(mel_channels > 0, "mel_channels > 0");
    assert_eq!(prosody_channels, 2, "prosody = (duration, F0/energy)");
}

/// Binary length ↔ manifest cross-check. Catches a partially-written or
/// mismatched fixture set before any parity comparison runs.
#[test]
fn fixture_binaries_match_manifest_lengths() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let dec_frames = man_usize(&m, "dec_frames");
    let hidden_dim = man_usize(&m, "hidden_dim");
    let style_dim = man_usize(&m, "style_dim");
    let mel_channels = man_usize(&m, "mel_channels");
    let pcm_len = man_usize(&m, "pcm_len");
    let prosody_channels = man_usize(&m, "prosody_channels");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes, "phoneme_ids.i64 length");
    for (i, id) in ids.iter().enumerate() {
        assert!(*id >= 0, "phoneme_ids[{i}] = {id} < 0");
    }

    let style = read_f32("style.f32");
    assert_eq!(style.len(), style_dim, "style.f32 length");

    let enc = read_f32("text_encoder.f32");
    assert_eq!(enc.len(), enc_pos * hidden_dim, "text_encoder.f32 length");

    let pros = read_f32("prosody.f32");
    assert_eq!(pros.len(), enc_pos * prosody_channels, "prosody.f32 length");

    let mel = read_f32("mel_pre_istft.f32");
    assert_eq!(
        mel.len(),
        dec_frames * mel_channels,
        "mel_pre_istft.f32 length"
    );

    let pcm = read_f32("pcm.f32");
    assert_eq!(pcm.len(), pcm_len, "pcm.f32 length");
}

/// Manifest mode marker. In `placeholder`, byte-level parity is intentionally
/// skipped by the gated tests below; in `full`, per-module keys
/// (`<module>_mode`) decide byte-parity per module. This test just documents
/// which mode the current fixture set encodes, visible with `--nocapture`.
#[test]
fn manifest_declares_mode() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let mode = m
        .get("mode")
        .cloned()
        .unwrap_or_else(|| "placeholder".to_owned());
    let te = module_mode(&m, "text_encoder_mode");
    let bert = module_mode(&m, "bert_mode");
    let pros = module_mode(&m, "prosody_mode");
    let dec = module_mode(&m, "decoder_mode");
    eprintln!(
        "[parity_kokoro] fixture mode = {mode}; per-module modes: \
         text_encoder = {te}, bert = {bert}, prosody = {pros}, decoder = {dec}"
    );
    assert!(
        matches!(mode.as_str(), "placeholder" | "full"),
        "mode must be `placeholder` or `full`, got {mode:?}"
    );
    for (name, val) in [
        ("text_encoder_mode", te.as_str()),
        ("bert_mode", bert.as_str()),
        ("prosody_mode", pros.as_str()),
        ("decoder_mode", dec.as_str()),
    ] {
        assert!(
            matches!(val, "placeholder" | "full"),
            "{name} must be `placeholder` or `full`, got {val:?}"
        );
    }
}

/// Reads a per-module mode marker (`<module>_mode`) from the manifest, falling
/// back to the global `mode` for backward compatibility with older fixtures
/// that only carried the global marker. Absent entirely → `"placeholder"`
/// (safest default: never claim a byte-parity that wasn't actually generated).
fn module_mode(m: &HashMap<String, String>, key: &str) -> String {
    if let Some(v) = m.get(key) {
        return v.clone();
    }
    m.get("mode")
        .cloned()
        .unwrap_or_else(|| "placeholder".to_owned())
}

// -----------------------------------------------------------------------------
// GGUF-gated tests (skip cleanly without `VOKRA_KOKORO_GGUF`)
// -----------------------------------------------------------------------------

/// Loads a converted Kokoro voice GGUF referenced by `VOKRA_KOKORO_GGUF`, or
/// `None` to skip. Also skips when the fixture dir is missing (we need the
/// manifest / phoneme ids / style to drive a forward).
fn load_gguf_path() -> Option<std::ffi::OsString> {
    if !fixtures_present() {
        return None;
    }
    std::env::var_os("VOKRA_KOKORO_GGUF")
}

/// End-to-end shape parity: the native `synthesize_phonemes` output shape
/// (post-iSTFT PCM) must be consistent with the manifest's `sample_rate`,
/// `num_phonemes`, and the reference dumper's per-phoneme frame budget. Byte-
/// level PCM parity requires `decoder_mode = full` (skipped otherwise).
#[test]
fn e2e_forward_matches_reference_shape() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!(
            "[parity_kokoro] SKIP: set VOKRA_KOKORO_GGUF to a converted Kokoro voice \
             GGUF to run the end-to-end forward parity."
        );
        return;
    };
    let m = manifest();
    let num_phonemes = man_usize(&m, "num_phonemes");
    let style_dim = man_usize(&m, "style_dim");
    let sample_rate = man_usize(&m, "sample_rate");
    let decoder_mode = module_mode(&m, "decoder_mode");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);
    let style = read_f32("style.f32");
    assert_eq!(style.len(), style_dim);

    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!(
            "load VOKRA_KOKORO_GGUF = {gguf:?}: {e}. Convert via \
             `vokra-cli convert --model kokoro-82m ...` first."
        )
    });

    // The native forward returns `SynthesizedAudio { samples, sample_rate }`.
    // The parity contract here is:
    //   * shape / length matches the reference dumper's `pcm.f32`, and
    //   * (decoder_mode = full only) byte-level closeness at ATOL.
    let ref_pcm = read_f32("pcm.f32");
    assert!(!ref_pcm.is_empty());

    let audio = tts
        .synthesize_phonemes(&ids, None, Some(&style), 0.0, 1.0)
        .expect("kokoro forward");

    // Sample-rate cross-check: dumper's manifest must agree with the loaded
    // voice's declared sample rate (FR-EX-08: a silent mismatch would mean
    // the fixture is for a *different* voice than the GGUF under test).
    assert_eq!(
        audio.sample_rate as usize, sample_rate,
        "native sample rate {} Hz != manifest {} Hz",
        audio.sample_rate, sample_rate,
    );

    // Shape check: the reference dump caps PCM at `pcm_len`, and the native
    // forward's actual length must not be *less* than that (dumper caps, not
    // truncates the native output). If more, the check compares the leading
    // slice.
    assert!(
        audio.samples.len() >= ref_pcm.len(),
        "native PCM length {} < reference {}",
        audio.samples.len(),
        ref_pcm.len()
    );
    eprintln!(
        "[parity_kokoro] shape OK: native {} samples, reference {} samples, sr {sample_rate} Hz",
        audio.samples.len(),
        ref_pcm.len()
    );

    if decoder_mode == "placeholder" {
        eprintln!(
            "[parity_kokoro] SKIP byte-level pcm parity: decoder_mode = placeholder. \
             Regenerate fixtures with a decoder NumPy re-forward to enable."
        );
        return;
    }

    // When `decoder_mode = full`, `decoder_pcm.f32` is the authoritative
    // reference PCM (per-frame from the PyTorch re-forward, `decoder_pcm_len`
    // samples). The legacy `pcm.f32` (16 000 samples, seed-derived noise) is a
    // placeholder that predates the decoder mode-full upgrade; leaving it
    // wired here would compare the native full-forward output against unrelated
    // noise. The dedicated `decoder_forward_bit_parity` test consumes
    // `decoder_pcm.f32` end-to-end. Skip the legacy comparison so the e2e test
    // remains an honest shape / sample-rate check when the decoder is real.
    eprintln!(
        "[parity_kokoro] SKIP legacy pcm.f32 byte comparison: decoder_mode = full → \
         `decoder_pcm.f32` is the authoritative reference; \
         see `decoder_forward_bit_parity` for the actual byte-level test."
    );
}

// -----------------------------------------------------------------------------
// Per-module byte-level parity tests (T17, gated on `<module>_mode = full`)
// -----------------------------------------------------------------------------
//
// These invoke the internal component forwards (text_encoder, bert) through
// the public `KokoroTts::from_path` load path + a purpose-built accessor. All
// skip cleanly when `VOKRA_KOKORO_GGUF` is unset (no Rust forward to compare).
// They also skip cleanly when the module's `<module>_mode = placeholder`.

/// The text_encoder Rust forward at `atol = 0.01` vs the reference dumped in
/// `text_encoder.f32`. Enabled when `text_encoder_mode = full`.
#[test]
fn text_encoder_forward_bit_parity() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!("[parity_kokoro] SKIP: VOKRA_KOKORO_GGUF unset.");
        return;
    };
    let m = manifest();
    let te_mode = module_mode(&m, "text_encoder_mode");
    if te_mode != "full" {
        eprintln!("[parity_kokoro] SKIP text_encoder byte parity: text_encoder_mode = {te_mode}");
        return;
    }

    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let hidden_dim = man_usize(&m, "hidden_dim");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);

    let expected = read_f32("text_encoder.f32");
    assert_eq!(
        expected.len(),
        enc_pos * hidden_dim,
        "text_encoder.f32 shape = [enc_pos, hidden_dim]"
    );

    // Drive the Rust text_encoder forward via the tester bridge on `KokoroTts`.
    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!("load VOKRA_KOKORO_GGUF = {gguf:?}: {e}");
    });
    let full = tts
        .text_encoder_forward_for_parity(&ids)
        .expect("text_encoder forward");
    // Full output is [t, hidden_dim] row-major; compare its first ENC_POS rows.
    let head_len = enc_pos * hidden_dim;
    assert!(
        full.len() >= head_len,
        "native text_encoder output {} shorter than expected head {head_len}",
        full.len()
    );
    assert_close(&full[..head_len], &expected, "kokoro text_encoder head");
}

/// The prosody Rust forward at `atol = 0.01` vs the reference dumped in
/// `prosody_{durations,f0,n,hidden}.*`. Enabled when `prosody_mode = full`.
///
/// The T14 prosody predictor consumes the bert output (or, on a voice without
/// the PL-BERT branch, the text-encoder output) + a style vector and returns
/// `(durations[T], f0[2·T_frames], n[2·T_frames], hidden[d_model, T_frames])`.
/// Both the reference and the Rust forward:
/// 1. run the same text encoder + bert forward on the fixture's phoneme_ids;
/// 2. transpose to channel-major and feed to the prosody predictor;
/// 3. use the fixture's `style.f32` as the style override.
///
/// The comparison order matters: `durations` are integer and must match
/// exactly (a mismatch there would silently propagate a T_frames delta,
/// invalidating f0/n/hidden shape comparisons). If durations match, the
/// downstream tensors are compared byte-for-byte at `atol = 0.01`.
#[test]
fn prosody_forward_bit_parity() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!("[parity_kokoro] SKIP: VOKRA_KOKORO_GGUF unset.");
        return;
    };
    let m = manifest();
    let prosody_mode = module_mode(&m, "prosody_mode");
    if prosody_mode != "full" {
        eprintln!("[parity_kokoro] SKIP prosody byte parity: prosody_mode = {prosody_mode}");
        return;
    }

    let num_phonemes = man_usize(&m, "num_phonemes");
    let style_dim = man_usize(&m, "style_dim");
    let t_frames_expected = man_usize(&m, "prosody_t_frames");
    let d_model_expected = man_usize(&m, "prosody_d_model");
    let f0_len_expected = man_usize(&m, "prosody_f0_len");
    let n_len_expected = man_usize(&m, "prosody_n_len");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);
    let style = read_f32("style.f32");
    assert_eq!(style.len(), style_dim);

    // Read the reference tensors.
    let ref_durations = read_i64("prosody_durations.i64");
    assert_eq!(
        ref_durations.len(),
        num_phonemes,
        "prosody_durations.i64 length"
    );
    let ref_t_frames: i64 = ref_durations.iter().sum();
    assert_eq!(
        ref_t_frames as usize, t_frames_expected,
        "manifest prosody_t_frames disagrees with sum(prosody_durations)",
    );
    let ref_f0 = read_f32("prosody_f0.f32");
    assert_eq!(ref_f0.len(), f0_len_expected, "prosody_f0.f32 length");
    let ref_n = read_f32("prosody_n.f32");
    assert_eq!(ref_n.len(), n_len_expected, "prosody_n.f32 length");
    let ref_hidden = read_f32("prosody_hidden.f32");
    assert_eq!(
        ref_hidden.len(),
        d_model_expected * t_frames_expected,
        "prosody_hidden.f32 length (channel-major [d_model, T_frames])",
    );

    // Drive the Rust prosody forward.
    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!("load VOKRA_KOKORO_GGUF = {gguf:?}: {e}");
    });
    let (native_durations, native_f0, native_n, native_hidden, native_t_frames) = tts
        .prosody_forward_for_parity(&ids, &style)
        .expect("prosody forward — voice must carry the T14 predictor.module.* branch");

    // Durations: integer equality (a mismatch here invalidates every downstream
    // shape). Report full arrays on failure so a per-phoneme drift is
    // diagnosable.
    if native_durations != ref_durations {
        panic!(
            "prosody durations differ:\n  native = {:?}\n  ref    = {:?}",
            native_durations, ref_durations
        );
    }
    assert_eq!(
        native_t_frames, t_frames_expected,
        "native t_frames {} != manifest {}",
        native_t_frames, t_frames_expected
    );

    // Downstream tensors — compute max |Δ| per tensor first (all three, not
    // just the first to fail) so a divergence report is complete before the
    // atol check panics. Fail at the end iff any tensor exceeds atol; the
    // per-tensor prints let the caller triage which layer diverged.
    let (f0_max, f0_i) = worst_delta(&native_f0, &ref_f0);
    let (n_max, n_i) = worst_delta(&native_n, &ref_n);
    let (h_max, h_i) = worst_delta(&native_hidden, &ref_hidden);
    eprintln!(
        "[parity] kokoro prosody per-tensor max |Δ|:\n  \
         f0     max = {f0_max:.3e} at idx {f0_i} ({} vs {})\n  \
         n      max = {n_max:.3e} at idx {n_i} ({} vs {})\n  \
         hidden max = {h_max:.3e} at idx {h_i} ({} vs {})\n  \
         (atol = {ATOL})",
        native_f0[f0_i],
        ref_f0[f0_i],
        native_n[n_i],
        ref_n[n_i],
        native_hidden[h_i],
        ref_hidden[h_i],
    );

    let mut failed = Vec::new();
    // All prosody tensors gate on the default `ATOL = 0.01`: measured vs the
    // TRUE upstream reference (2026-07-16): f0 = 3.0e-3, n = 5.1e-5,
    // hidden = 8.5e-5. (The pre-fix `PROSODY_F0_ATOL = 0.05` override is
    // obsolete — see the const-block NOTE at the top of this file.) Every
    // observed delta is reported to stderr above.
    if f0_max > ATOL {
        failed.push(("f0", f0_max, f0_i));
    }
    if n_max > ATOL {
        failed.push(("n", n_max, n_i));
    }
    if h_max > ATOL {
        failed.push(("hidden", h_max, h_i));
    }
    assert!(
        failed.is_empty(),
        "prosody tensors exceed atol = {ATOL}: {:?}",
        failed
    );
}

/// Compute (max |Δ|, index) between `got` and `expected`, panicking if their
/// lengths differ. Diagnostic-only sibling of [`assert_close`] used when we
/// want all per-tensor deltas printed before the assertion trips.
#[allow(dead_code)]
fn worst_delta(got: &[f32], expected: &[f32]) -> (f32, usize) {
    assert_eq!(
        got.len(),
        expected.len(),
        "worst_delta: length {} != expected {}",
        got.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0usize;
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        let d = (g - e).abs();
        if d > worst {
            worst = d;
            worst_i = i;
        }
    }
    (worst, worst_i)
}

/// The bert Rust forward at `atol = 0.01` vs the reference dumped in
/// `bert.f32`. Enabled when `bert_mode = full`; requires the voice GGUF to
/// carry the PL-BERT branch (the canary tensor
/// `bert.module.embeddings.word_embeddings.weight`).
#[test]
fn bert_forward_bit_parity() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!("[parity_kokoro] SKIP: VOKRA_KOKORO_GGUF unset.");
        return;
    };
    let m = manifest();
    let bert_mode = module_mode(&m, "bert_mode");
    if bert_mode != "full" {
        eprintln!("[parity_kokoro] SKIP bert byte parity: bert_mode = {bert_mode}");
        return;
    }

    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let bert_out_dim = man_usize(&m, "bert_out_dim");
    assert!(
        bert_out_dim > 0,
        "bert_out_dim = 0 → dumper wrote no bert.f32; \
         bert_mode = full is a manifest bug"
    );

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);

    let expected = read_f32("bert.f32");
    assert_eq!(
        expected.len(),
        enc_pos * bert_out_dim,
        "bert.f32 shape = [enc_pos, bert_out_dim]"
    );

    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!("load VOKRA_KOKORO_GGUF = {gguf:?}: {e}");
    });
    let full = tts
        .bert_forward_for_parity(&ids)
        .expect("bert forward — voice must carry the PL-BERT branch (canary tensor present)");
    let head_len = enc_pos * bert_out_dim;
    assert!(
        full.len() >= head_len,
        "native bert output {} shorter than expected head {head_len}",
        full.len()
    );
    assert_close(&full[..head_len], &expected, "kokoro bert head");
}

/// The decoder Rust forward vs the reference dumped in
/// `decoder_pre_istft_{mag,phase}.f32` + `decoder_pcm.f32`, gated on the
/// measured per-tensor max+mean bounds ([`DECODER_MAG_ATOL`] block).
/// Enabled when `decoder_mode = full`.
///
/// The decoder is Kokoro's iSTFTNet head: encode block + 4 decode blocks
/// (last one upsampling, output_padding=1) + HiFi-GAN generator (2 stages ×
/// 3 MRF kernels + NSF harmonic source) + iSTFT lowering. The reference
/// tensors are hooked activations of the TRUE upstream `kokoro` package
/// (see `tools/parity/dump_kokoro_reference.py`), with the SineGen RNG
/// neutralized identically on both sides.
///
/// # Module isolation — why the decoder gets REFERENCE contours
///
/// The decoder consumes the prosody predictor's durations + F0/N. Driving it
/// with the RUST prosody outputs would compound the (honest, bounded)
/// prosody deltas through the NSF source path, which is **discontinuous** in
/// F0: the harmonic-source STFT's `angle` feature has an atan2 branch cut at
/// near-zero-magnitude bins, so f0 max |Δ| ≈ 3e-3 flips ~1.2k bins by 2π and
/// blows the decoder logits to max |Δ| ≈ 2 — a property of the composition,
/// not of the decoder math. This test therefore feeds the FIXTURE durations
/// / F0 / N (`decoder_forward_with_reference_contours`), gating the decoder
/// tensors on identical inputs; the composed pipeline is covered by the
/// full-pipeline accessor (`decoder_forward_for_parity`, exercised by the
/// e2e acceptance: whisper round-trip WER + mel-L1).
///
/// Reports per-tensor max |Δ| before asserting so a divergence report is
/// complete even when multiple tensors exceed atol (parity contract:
/// **no fabricated pass** — silent CPU fallback forbidden, over-atol = FAIL).
#[test]
fn decoder_forward_bit_parity() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!("[parity_kokoro] SKIP: VOKRA_KOKORO_GGUF unset.");
        return;
    };
    let m = manifest();
    let decoder_mode = module_mode(&m, "decoder_mode");
    if decoder_mode != "full" {
        eprintln!("[parity_kokoro] SKIP decoder byte parity: decoder_mode = {decoder_mode}");
        return;
    }

    let num_phonemes = man_usize(&m, "num_phonemes");
    let style_dim = man_usize(&m, "style_dim");
    let decoder_n_half = man_usize(&m, "decoder_n_half");
    let decoder_t_gen = man_usize(&m, "decoder_t_gen");
    let decoder_pcm_len = man_usize(&m, "decoder_pcm_len");
    let istft_n_fft = man_usize(&m, "istft_n_fft");
    let istft_hop = man_usize(&m, "istft_hop");
    let istft_win_length = man_usize(&m, "istft_win_length");
    let t_frames_expected = man_usize(&m, "prosody_t_frames");

    // Sanity: iSTFT triple from the dumper must match Kokoro-82M's constants.
    // A mismatch would mean the reference was dumped against a differently
    // configured decoder — refuse to compare (FR-EX-08 — no silent skew).
    assert_eq!(istft_n_fft, 20, "kokoro iSTFT n_fft must be 20");
    assert_eq!(istft_hop, 5, "kokoro iSTFT hop must be 5");
    assert_eq!(istft_win_length, 20, "kokoro iSTFT win_length must be 20");
    assert_eq!(decoder_n_half, istft_n_fft / 2 + 1, "n_half = n_fft/2 + 1");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);
    let style = read_f32("style.f32");
    assert_eq!(style.len(), style_dim);

    // Reference prosody outputs — the decoder's isolated-module inputs.
    let ref_durations = read_i64("prosody_durations.i64");
    let durations: Vec<usize> = ref_durations.iter().map(|&d| d as usize).collect();
    assert_eq!(durations.iter().sum::<usize>(), t_frames_expected);
    let ref_f0 = read_f32("prosody_f0.f32");
    let ref_n = read_f32("prosody_n.f32");
    assert_eq!(ref_f0.len(), 2 * t_frames_expected, "prosody_f0.f32 length");
    assert_eq!(ref_n.len(), 2 * t_frames_expected, "prosody_n.f32 length");

    // Reference tensors.
    let ref_mag = read_f32("decoder_pre_istft_mag.f32");
    assert_eq!(
        ref_mag.len(),
        decoder_n_half * decoder_t_gen,
        "decoder_pre_istft_mag.f32 shape = [n_half · t_gen]"
    );
    let ref_phase = read_f32("decoder_pre_istft_phase.f32");
    assert_eq!(
        ref_phase.len(),
        decoder_n_half * decoder_t_gen,
        "decoder_pre_istft_phase.f32 shape = [n_half · t_gen]"
    );
    let ref_pcm = read_f32("decoder_pcm.f32");
    assert_eq!(ref_pcm.len(), decoder_pcm_len, "decoder_pcm.f32 length");

    // Drive the Rust decoder forward on the reference contours.
    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!("load VOKRA_KOKORO_GGUF = {gguf:?}: {e}");
    });
    let (native_mag, native_phase, native_pcm) = tts
        .decoder_forward_with_reference_contours(&ids, &style, &durations, &ref_f0, &ref_n)
        .expect("decoder forward — voice must carry the decoder.module.* branch");

    assert_eq!(
        native_mag.len(),
        ref_mag.len(),
        "native decoder mag len {} != reference {}",
        native_mag.len(),
        ref_mag.len(),
    );
    assert_eq!(
        native_phase.len(),
        ref_phase.len(),
        "native decoder phase len {} != reference {}",
        native_phase.len(),
        ref_phase.len(),
    );
    assert_eq!(
        native_pcm.len(),
        ref_pcm.len(),
        "native decoder pcm len {} != reference {}",
        native_pcm.len(),
        ref_pcm.len(),
    );

    // Compute worst deltas across all three tensors. Ignore positions where
    // both sides are non-finite (the synthetic seed-derived phoneme sequence
    // + unit-norm style vector produces some overflow at the iSTFT because
    // ``mag = exp(x_mag)`` is unbounded; both Rust and reference should hit
    // the same overflow at the same positions, so a "both non-finite" cell
    // is not a parity failure).
    let (mag_max, mag_i, mag_finite, mag_total) = finite_worst_delta(&native_mag, &ref_mag);
    let (phase_max, phase_i, phase_finite, phase_total) =
        finite_worst_delta(&native_phase, &ref_phase);
    let (pcm_max, pcm_i, pcm_finite, pcm_total) = finite_worst_delta(&native_pcm, &ref_pcm);

    // Histogram diagnostic: count how many elements fall in each delta bucket.
    let mag_hist = delta_histogram(&native_mag, &ref_mag);
    let phase_hist = delta_histogram(&native_phase, &ref_phase);
    let pcm_hist = delta_histogram(&native_pcm, &ref_pcm);
    eprintln!(
        "[parity] kokoro decoder delta histogram (|Δ| buckets: <1e-4, <1e-3, <1e-2, <1e-1, <1, ≥1):\n  \
         mag    = {mag_hist:?}\n  \
         phase  = {phase_hist:?}\n  \
         pcm    = {pcm_hist:?}"
    );

    // Dump native to scratchpad for offline diff so the follow-up can look at
    // where the error concentrates (boundary vs distributed).
    if let Ok(dir) = std::env::var("VOKRA_KOKORO_PARITY_DUMP") {
        let d = std::path::Path::new(&dir);
        std::fs::create_dir_all(d).ok();
        write_f32_dump(&d.join("native_decoder_pre_istft_mag.f32"), &native_mag);
        write_f32_dump(&d.join("native_decoder_pre_istft_phase.f32"), &native_phase);
        write_f32_dump(&d.join("native_decoder_pcm.f32"), &native_pcm);
        eprintln!("[parity] wrote native decoder tensors to {}", d.display());
    }

    let mag_mean = finite_mean_delta(&native_mag, &ref_mag);
    let phase_mean = finite_mean_delta(&native_phase, &ref_phase);
    let pcm_mean = finite_mean_delta(&native_pcm, &ref_pcm);
    eprintln!(
        "[parity] kokoro decoder per-tensor |Δ| (finite-only):\n  \
         mag    max = {mag_max:.3e} at idx {mag_i} ({} vs {}); mean = {mag_mean:.3e}; finite {}/{}\n  \
         phase  max = {phase_max:.3e} at idx {phase_i} ({} vs {}); mean = {phase_mean:.3e}; finite {}/{}\n  \
         pcm    max = {pcm_max:.3e} at idx {pcm_i} ({} vs {}); mean = {pcm_mean:.3e}; finite {}/{}\n  \
         (bounds: mag max/mean {DECODER_MAG_ATOL}/{DECODER_MAG_MEAN_ATOL}, \
         phase {DECODER_PHASE_ATOL}/{DECODER_PHASE_MEAN_ATOL}, \
         pcm {DECODER_PCM_ATOL}/{DECODER_PCM_MEAN_ATOL})",
        native_mag[mag_i],
        ref_mag[mag_i],
        mag_finite,
        mag_total,
        native_phase[phase_i],
        ref_phase[phase_i],
        phase_finite,
        phase_total,
        native_pcm[pcm_i],
        ref_pcm[pcm_i],
        pcm_finite,
        pcm_total,
    );

    // Dual gates per tensor: measured-and-documented max-|Δ| bound (branch-
    // cut spikes, see the const block at the top of this file) + a mean-|Δ|
    // bound that catches systematic drift the sparse spikes cannot mask.
    let mut failed: Vec<(&str, f32)> = Vec::new();
    if mag_max > DECODER_MAG_ATOL {
        failed.push(("mag max", mag_max));
    }
    if mag_mean > DECODER_MAG_MEAN_ATOL {
        failed.push(("mag mean", mag_mean));
    }
    if phase_max > DECODER_PHASE_ATOL {
        failed.push(("phase max", phase_max));
    }
    if phase_mean > DECODER_PHASE_MEAN_ATOL {
        failed.push(("phase mean", phase_mean));
    }
    if pcm_max > DECODER_PCM_ATOL {
        failed.push(("pcm max", pcm_max));
    }
    if pcm_mean > DECODER_PCM_MEAN_ATOL {
        failed.push(("pcm mean", pcm_mean));
    }
    // FAILURE PATH ONLY: never runs while every gate passes, and cannot
    // change pass/fail — it only widens what a red run reports, so the next
    // platform failure is diagnosable from its own log (see the OPEN block).
    if !failed.is_empty() {
        eprintln!(
            "{}",
            explain_worst_pcm(
                &native_pcm,
                &ref_pcm,
                &native_mag,
                &ref_mag,
                &native_phase,
                &ref_phase,
                decoder_n_half,
                decoder_t_gen,
                istft_n_fft,
                istft_hop,
                pcm_i,
            )
        );
    }
    assert!(
        failed.is_empty(),
        "decoder tensors exceed their per-tensor bounds \
         (mag {DECODER_MAG_ATOL}/{DECODER_MAG_MEAN_ATOL}, \
         phase {DECODER_PHASE_ATOL}/{DECODER_PHASE_MEAN_ATOL}, \
         pcm {DECODER_PCM_ATOL}/{DECODER_PCM_MEAN_ATOL}): {:?}",
        failed
    );
}

/// Mean |Δ| over finite pairs — companion of [`finite_worst_delta`].
#[allow(dead_code)]
fn finite_mean_delta(got: &[f32], expected: &[f32]) -> f32 {
    assert_eq!(got.len(), expected.len());
    let mut sum = 0.0f64;
    let mut n = 0usize;
    for (g, e) in got.iter().zip(expected) {
        if g.is_finite() && e.is_finite() {
            sum += f64::from((g - e).abs());
            n += 1;
        }
    }
    if n == 0 { 0.0 } else { (sum / n as f64) as f32 }
}

/// Bucketized delta histogram: counts of finite-pair elements whose
/// ``|got − expected|`` falls in ``<1e-4, <1e-3, <1e-2, <1e-1, <1, ≥1``.
/// Diagnostic-only sibling of [`finite_worst_delta`] used to distinguish a
/// boundary-only vs distributed divergence.
#[allow(dead_code)]
fn delta_histogram(got: &[f32], expected: &[f32]) -> [usize; 6] {
    assert_eq!(got.len(), expected.len());
    let mut buckets = [0usize; 6];
    for (g, e) in got.iter().zip(expected) {
        if !g.is_finite() || !e.is_finite() {
            continue;
        }
        let d = (g - e).abs();
        let bucket = if d < 1e-4 {
            0
        } else if d < 1e-3 {
            1
        } else if d < 1e-2 {
            2
        } else if d < 1e-1 {
            3
        } else if d < 1.0 {
            4
        } else {
            5
        };
        buckets[bucket] += 1;
    }
    buckets
}

/// **Failure-path-only** explanation of the worst PCM sample.
///
/// A `pcm max` gate that fails without saying *why* costs a full CI round
/// trip — the 2026-07-19 Linux failure (see the OPEN block at the top of this
/// file) produced exactly one number and no way to tell a benign platform
/// outlier from a localized kernel fault. This prints, for the worst bin, the
/// facts that separate the competing explanations:
///
/// 1. **Where it came from.** The PCM index mapped back to the iSTFT frames
///    that produced it. `center = true`, so sample `i` is untrimmed position
///    `p = i + n_fft/2`, and frame `f` writes `[f·hop, f·hop + n_fft)` — four
///    overlapping frames at Kokoro's `n_fft = 20 / hop = 5`, each contributing
///    all `n_half` bins.
/// 2. **Reference and native magnitude AND phase there**, in *linear*
///    magnitude (`exp(x_mag)`, see [`NEAR_ZERO_LINEAR_MAG`]) — plus an
///    explicit near-zero verdict, which is what the documented atan2
///    branch-cut mechanism predicts.
/// 3. **Amplitude context.** The error field tracks signal amplitude (M1:
///    rank-corr 0.82 against the local envelope, mean relative error flat at
///    ~1.1e-2 across amplitude deciles), so an absolute max at a loud sample
///    can be ordinary relative error rather than a spike.
/// 4. **Plateau shape.** Whether the max is a lone outlier or the top of a
///    dense plateau. On M1 it is a plateau: 6 samples within 0.9×, 55 within
///    0.5×, 367 within 0.25× — so which sample wins the argmax is close to a
///    coin flip, and the argmax moving between platforms means little on its
///    own. A *lone* spike with relative error far above p99 is the signature
///    that would instead implicate a kernel.
///
/// Costs a few linear passes plus one sort of the PCM-length delta vector,
/// only when a gate has already failed. Allocates one `String`; reads only
/// slices the caller already holds; changes no pass/fail semantics.
#[allow(dead_code, clippy::too_many_arguments)]
fn explain_worst_pcm(
    native_pcm: &[f32],
    ref_pcm: &[f32],
    native_mag: &[f32],
    ref_mag: &[f32],
    native_phase: &[f32],
    ref_phase: &[f32],
    n_half: usize,
    t_gen: usize,
    n_fft: usize,
    hop: usize,
    worst_i: usize,
) -> String {
    use std::fmt::Write as _;

    /// Half-width of the local-amplitude envelope, in samples.
    const ENV_HALF: usize = 10;

    let mut s = String::with_capacity(4096);
    let delta = (native_pcm[worst_i] - ref_pcm[worst_i]).abs();
    let _ = writeln!(
        s,
        "\n[parity] ==== worst-pcm explanation (FAILURE PATH ONLY) ====\n  \
         pcm[{worst_i}] native {:+.6} vs ref {:+.6} — |Δ| = {delta:.4e}",
        native_pcm[worst_i], ref_pcm[worst_i],
    );

    // ---- 1. index -> iSTFT frames -------------------------------------
    let p = worst_i + n_fft / 2;
    let lo = p.saturating_sub(n_fft - 1).div_ceil(hop);
    let hi = (p / hop).min(t_gen - 1);
    let _ = writeln!(
        s,
        "  iSTFT geometry: n_fft={n_fft} hop={hop} center=true → untrimmed p = i + {} = {p}\n  \
         contributing frames {lo}..={hi} ({} frames × {n_half} bins = {} cells)",
        n_fft / 2,
        hi + 1 - lo,
        (hi + 1 - lo) * n_half,
    );

    // ---- 2. per-frame spectral state + the single worst cell ----------
    let at = |t: &[f32], bin: usize, f: usize| t[bin * t_gen + f];
    let mut min_lin = f32::INFINITY;
    let mut worst_cell = (lo, 0usize, 0.0f32); // (frame, bin, |Δz| linear)
    for f in lo..=hi {
        let (mut lin_lo, mut lin_hi) = (f32::INFINITY, 0.0f32);
        let (mut dmag, mut dph) = (0.0f32, 0.0f32);
        for b in 0..n_half {
            let (rl, nl) = (at(ref_mag, b, f).exp(), at(native_mag, b, f).exp());
            lin_lo = lin_lo.min(rl);
            lin_hi = lin_hi.max(rl);
            min_lin = min_lin.min(rl);
            dmag = dmag.max((at(native_mag, b, f) - at(ref_mag, b, f)).abs());
            dph = dph.max((at(native_phase, b, f) - at(ref_phase, b, f)).abs());
            if (nl - rl).abs() > worst_cell.2 {
                worst_cell = (f, b, (nl - rl).abs());
            }
        }
        let _ = writeln!(
            s,
            "    frame {f}: ref |z| [{lin_lo:.3e}, {lin_hi:.3e}]  \
             max|Δ log-mag| {dmag:.3e}  max|Δ phase| {dph:.3e}"
        );
    }
    let (wf, wb, wd) = worst_cell;
    let _ = writeln!(
        s,
        "  largest single-bin linear |Δz| over those frames: frame {wf} bin {wb} → {wd:.3e}\n    \
         |z|   ref {:.6e}  native {:.6e}\n    \
         phase ref {:+.6}      native {:+.6}   (stored logit; head applies sin())",
        at(ref_mag, wb, wf).exp(),
        at(native_mag, wb, wf).exp(),
        at(ref_phase, wb, wf),
        at(native_phase, wb, wf),
    );

    // ---- 3. near-zero verdict ------------------------------------------
    let below = (lo..=hi)
        .flat_map(|f| (0..n_half).map(move |b| (f, b)))
        .filter(|&(f, b)| at(ref_mag, b, f).exp() < NEAR_ZERO_LINEAR_MAG)
        .count();
    let _ = writeln!(
        s,
        "  NEAR-ZERO CHECK (linear |z| < {NEAR_ZERO_LINEAR_MAG:.1e}; ~25 % of ALL bins are):\n    \
         min ref |z| over contributing cells = {min_lin:.3e}; below threshold: {below}/{}\n    \
         → {}",
        (hi + 1 - lo) * n_half,
        if below == 0 {
            "NOT a near-zero site — the atan2 branch-cut mechanism does NOT explain this bin"
        } else {
            "near-zero bins present — branch-cut flip is a live explanation here"
        },
    );

    // ---- 4. amplitude context + plateau shape --------------------------
    let env_at = |i: usize| {
        let a = i.saturating_sub(ENV_HALF);
        let b = (i + ENV_HALF).min(ref_pcm.len());
        ref_pcm[a..b].iter().fold(0.0f32, |m, v| m.max(v.abs()))
    };
    let env = env_at(worst_i);
    let mut rels: Vec<f32> = (0..ref_pcm.len())
        .map(|i| (native_pcm[i] - ref_pcm[i]).abs() / env_at(i).max(1e-9))
        .collect();
    rels.sort_by(f32::total_cmp);
    let pick = |q: f64| rels[((rels.len() - 1) as f64 * q) as usize];
    let _ = writeln!(
        s,
        "  AMPLITUDE CONTEXT:\n    \
         |ref pcm| here {:.4e}; local envelope (±{ENV_HALF}) {env:.4e}\n    \
         relative error here = |Δ|/envelope = {:.3e}\n    \
         population relative error: median {:.3e}  p99 {:.3e}  max {:.3e}",
        ref_pcm[worst_i].abs(),
        delta / env.max(1e-9),
        pick(0.50),
        pick(0.99),
        rels[rels.len() - 1],
    );

    let cnt = |frac: f32| {
        native_pcm
            .iter()
            .zip(ref_pcm)
            .filter(|(n, r)| (*n - *r).abs() >= frac * delta)
            .count()
    };
    let _ = writeln!(
        s,
        "  PLATEAU SHAPE (lone spike, or top of a broad plateau?):\n    \
         samples ≥0.90×max {}  ≥0.75× {}  ≥0.50× {}  ≥0.25× {}   (M1 ref: 6 / 12 / 55 / 367)",
        cnt(0.90),
        cnt(0.75),
        cnt(0.50),
        cnt(0.25),
    );

    let _ = writeln!(
        s,
        "  HOW TO READ THIS:\n    \
         near-zero site + few plateau peers      → atan2 branch cut, benign, platform-dependent\n    \
         high |z| + dense plateau + rel ≈ p99    → ordinary amplitude-tracking relative error\n    \
         high |z| + LONE spike + rel ≫ p99       → localized kernel fault: investigate the GEMM\n    \
         (`VOKRA_KOKORO_PARITY_DUMP=<dir>` also writes every generator stage tap,\n     \
         including `native_gen_har_spec.f32` = [2·n_half, t_gen] NSF |z| ; angle.)\n  \
         ========================================================"
    );
    s
}

/// Diagnostic helper: dump a f32 slice to path.
#[allow(dead_code)]
fn write_f32_dump(path: &std::path::Path, data: &[f32]) {
    let mut bytes = Vec::with_capacity(data.len() * 4);
    for v in data {
        bytes.extend_from_slice(&v.to_le_bytes());
    }
    std::fs::write(path, bytes).ok();
}

/// Same signature as [`worst_delta`] but skips positions where either side is
/// non-finite (NaN / Inf) — mirrors the parity comparator used for the
/// decoder, whose iSTFT can hit ``exp(x_mag) → inf`` when driven by the
/// synthetic seed-derived inputs. A cell where either side is non-finite is
/// counted as "not-compared". Returns
/// ``(max_delta, worst_index, finite_count, total)``.
#[allow(dead_code)]
fn finite_worst_delta(got: &[f32], expected: &[f32]) -> (f32, usize, usize, usize) {
    assert_eq!(
        got.len(),
        expected.len(),
        "finite_worst_delta: length {} != expected {}",
        got.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0usize;
    let mut finite = 0usize;
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        if !g.is_finite() || !e.is_finite() {
            continue;
        }
        finite += 1;
        let d = (g - e).abs();
        if d > worst {
            worst = d;
            worst_i = i;
        }
    }
    (worst, worst_i, finite, got.len())
}
