//! Voxtral (Mistral) numerical parity vs the upstream reference
//! (M3-10-T19 / T20).
//!
//! # Fixture layout (M3-10 foundation)
//!
//! Fixtures live in `tests/parity/voxtral/` and are regenerated by
//! `tools/parity/dump_voxtral_reference.py` (a follow-up ticket — the
//! dumper is not yet committed). The fixture set mirrors Whisper /
//! Kokoro:
//!
//! - `manifest.txt` — key=value pairs describing input shapes.
//! - `log_mel.f32.bin` — reference log-mel input `[n_mels, n_frames]`.
//! - `audio_encoder_out.f32.bin` — expected encoder hidden state
//!   `[n_ctx, d_audio]`.
//! - `text_decoder_step_out.f32.bin` — expected decoder-step logits
//!   `[vocab_size]` at the first sampling step.
//! - `asr_tokens.i64.bin` — expected greedy transcription token id
//!   sequence.
//!
//! # Gate posture (M3-10-T20)
//!
//! - **Fixture-only tests** (this file, no `VOKRA_VOXTRAL_GGUF` env var)
//!   run wherever the fixture is present: they cross-check the
//!   manifest ↔ binary lengths and are cheap. If the fixture is
//!   absent (fresh checkout / dumper not run yet) they skip cleanly
//!   with a diagnostic — never a fabricated pass.
//! - **Real-checkpoint tests** are gated on `VOKRA_VOXTRAL_GGUF` and
//!   skip when unset (same posture as `parity_whisper.rs` and
//!   `parity_kokoro.rs`). The foundation ticket does not commit any
//!   real-checkpoint fixture (the GGUF is too large to ship, and the
//!   real forward is deferred to T13+); this file lays out the
//!   contract for the follow-up.

#![allow(clippy::items_after_statements)]

use std::collections::HashMap;
use std::path::{Path, PathBuf};

const ATOL: f32 = 0.01;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("parity")
        .join("voxtral")
}

fn fixtures_present() -> bool {
    fixtures_dir().is_dir() && fixtures_dir().join("manifest.txt").is_file()
}

fn manifest() -> HashMap<String, String> {
    let text = std::fs::read_to_string(fixtures_dir().join("manifest.txt")).expect("manifest");
    let mut m = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            m.insert(k.trim().to_owned(), v.trim().to_owned());
        }
    }
    m
}

fn man_usize(m: &HashMap<String, String>, k: &str) -> usize {
    m.get(k)
        .unwrap_or_else(|| panic!("manifest missing key {k}"))
        .parse()
        .unwrap_or_else(|_| panic!("manifest {k} not usize"))
}

fn read_f32(name: &str) -> Vec<f32> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 4, 0, "{name}: not a whole number of f32");
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

/// Element-wise closeness with a diagnostic on the worst offender.
#[allow(dead_code)]
fn assert_close(got: &[f32], expected: &[f32], ctx: &str) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{ctx}: length {} != expected {}",
        got.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0usize;
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        let d = (g - e).abs();
        if d > worst {
            worst = d;
            worst_i = i;
        }
    }
    eprintln!(
        "[parity_voxtral] {ctx}: max |Δ| = {worst:.3e} over {} elems (atol {ATOL})",
        got.len()
    );
    assert!(
        worst <= ATOL,
        "{ctx}: max |Δ| = {worst} at index {worst_i} (got {} vs {}) exceeds atol {ATOL}",
        got[worst_i],
        expected[worst_i]
    );
}

// -----------------------------------------------------------------------------
// Fixture-only tests (no GGUF required, run on every PR when fixture present)
// -----------------------------------------------------------------------------

/// Manifest → known-shape cross-check.
#[test]
fn manifest_shapes_are_self_consistent() {
    if !fixtures_present() {
        eprintln!(
            "[parity_voxtral] SKIP: no fixture dir at {:?}. Run tools/parity/dump_voxtral_reference.py once it lands.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    // Contract: the dumper writes every dimensional key the harness relies
    // on. Foundation-only — the fixture set may grow with T19+.
    let n_mels = man_usize(&m, "n_mels");
    let n_frames = man_usize(&m, "n_frames");
    let n_ctx = man_usize(&m, "n_ctx");
    let d_audio = man_usize(&m, "d_audio");
    let vocab_size = man_usize(&m, "vocab_size");
    assert!(n_mels > 0, "n_mels > 0");
    assert!(n_frames > 0, "n_frames > 0");
    assert!(n_ctx > 0, "n_ctx > 0");
    assert!(d_audio > 0, "d_audio > 0");
    assert!(vocab_size > 0, "vocab_size > 0");
}

/// Binary length ↔ manifest cross-check.
#[test]
fn fixture_binaries_match_manifest_lengths() {
    if !fixtures_present() {
        eprintln!(
            "[parity_voxtral] SKIP: no fixture dir at {:?}.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let n_mels = man_usize(&m, "n_mels");
    let n_frames = man_usize(&m, "n_frames");
    let n_ctx = man_usize(&m, "n_ctx");
    let d_audio = man_usize(&m, "d_audio");
    let vocab_size = man_usize(&m, "vocab_size");

    // log_mel.f32.bin: n_mels × n_frames.
    if fixtures_dir().join("log_mel.f32.bin").is_file() {
        let x = read_f32("log_mel.f32.bin");
        assert_eq!(x.len(), n_mels * n_frames, "log_mel length");
    }
    // audio_encoder_out.f32.bin: n_ctx × d_audio.
    if fixtures_dir().join("audio_encoder_out.f32.bin").is_file() {
        let x = read_f32("audio_encoder_out.f32.bin");
        assert_eq!(x.len(), n_ctx * d_audio, "audio_encoder_out length");
    }
    // text_decoder_step_out.f32.bin: vocab_size (single step logits).
    if fixtures_dir()
        .join("text_decoder_step_out.f32.bin")
        .is_file()
    {
        let x = read_f32("text_decoder_step_out.f32.bin");
        assert_eq!(x.len(), vocab_size, "text_decoder_step_out length");
    }
}

// -----------------------------------------------------------------------------
// GGUF-gated tests (real Voxtral checkpoint, skip when env unset)
// -----------------------------------------------------------------------------

/// Load the Voxtral GGUF path from `VOKRA_VOXTRAL_GGUF`, or skip.
fn require_voxtral_gguf() -> Option<PathBuf> {
    std::env::var_os("VOKRA_VOXTRAL_GGUF").map(PathBuf::from)
}

#[test]
fn audio_encoder_parity_smoke() {
    // Real forward wired once a downloaded Voxtral checkpoint is
    // available. Foundation-only posture: gate on the env var and the
    // fixture; skip cleanly otherwise. Do not fabricate a pass.
    let Some(gguf) = require_voxtral_gguf() else {
        eprintln!(
            "[parity_voxtral] SKIP audio_encoder_parity_smoke: set VOKRA_VOXTRAL_GGUF to a \
             converted Voxtral GGUF to enable this test."
        );
        return;
    };
    if !fixtures_present() {
        eprintln!("[parity_voxtral] SKIP audio_encoder_parity_smoke: no fixture dir.");
        return;
    }
    // Only proceed if the fixture binary is present too.
    if !fixtures_dir().join("audio_encoder_out.f32.bin").is_file()
        || !fixtures_dir().join("log_mel.f32.bin").is_file()
    {
        eprintln!(
            "[parity_voxtral] SKIP audio_encoder_parity_smoke: audio_encoder_out.f32.bin / \
             log_mel.f32.bin not present."
        );
        return;
    }

    // The REAL tower parity harness lives in `voxtral_tower_parity.rs`
    // (M4-residual cc-07: full 32-layer forward + upstream tap dumps,
    // env-gated on VOKRA_VOXTRAL_REF_DIR). This fixture-file flavor stays a
    // placeholder for a future *committed* fixture set — we surface an
    // explicit marker so a CI ticket cannot mistake an unforeseen green
    // here for real parity.
    eprintln!(
        "[parity_voxtral] audio_encoder_parity_smoke: GGUF {} + fixtures present — the live \
         tower parity harness is tests/voxtral_tower_parity.rs (set VOKRA_VOXTRAL_REF_DIR); \
         this committed-fixture flavor is still a placeholder. Skipping without failing.",
        gguf.display()
    );
}

#[test]
fn text_decoder_step_parity_smoke() {
    let Some(gguf) = require_voxtral_gguf() else {
        eprintln!("[parity_voxtral] SKIP text_decoder_step_parity_smoke: set VOKRA_VOXTRAL_GGUF.");
        return;
    };
    if !fixtures_present()
        || !fixtures_dir()
            .join("text_decoder_step_out.f32.bin")
            .is_file()
    {
        eprintln!("[parity_voxtral] SKIP text_decoder_step_parity_smoke: fixtures absent.");
        return;
    }
    eprintln!(
        "[parity_voxtral] TODO text_decoder_step_parity_smoke: {} + fixture ready, harness \
         lands with M3-10-T19+.",
        gguf.display()
    );
}

#[test]
fn asr_greedy_token_parity_smoke() {
    let Some(gguf) = require_voxtral_gguf() else {
        eprintln!("[parity_voxtral] SKIP asr_greedy_token_parity_smoke: set VOKRA_VOXTRAL_GGUF.");
        return;
    };
    if !fixtures_present() || !fixtures_dir().join("asr_tokens.i64.bin").is_file() {
        eprintln!("[parity_voxtral] SKIP asr_greedy_token_parity_smoke: fixtures absent.");
        return;
    }
    eprintln!(
        "[parity_voxtral] TODO asr_greedy_token_parity_smoke: {} + fixture ready, harness \
         lands with M3-10-T19+.",
        gguf.display()
    );
}
