//! Whisper base numerical parity vs the PyTorch (transformers) reference
//! (M0-06-T07/T10/T16/T18; NFR-QL-01, FP32 `atol = 0.01`).
//!
//! Fixtures live in `tests/parity/whisper_base/` and are regenerated by
//! `tools/parity/dump_whisper_reference.py`. Two tests need only the committed
//! fixtures and run everywhere (log-mel front-end; detokenizer). The
//! encoder / decoder / greedy tests need the converted **GGUF**, which is far
//! too large to commit, so they are gated on the `VOKRA_WHISPER_GGUF`
//! environment variable and skip cleanly when it is unset (e.g. in CI).

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use vokra_core::AsrEngine;
use vokra_core::decode::BeamSearchConfig;
use vokra_core::gguf::GgufFile;
use vokra_models::whisper::WhisperModel;
use vokra_models::whisper::asr::WhisperAsr;
use vokra_models::whisper::greedy::greedy_decode;
use vokra_models::whisper::mel::{self, N_FRAMES};
use vokra_models::whisper::tokenizer::WhisperTokenizer;

const ATOL: f32 = 0.01;

/// Per-size parity tolerance lookup (M4-14-T04).
///
/// Every size currently resolves to the global FP32 bound [`ATOL`]` = 0.01`
/// (NFR-QL-01) — **including turbo**. turbo (distilled 809M, decoder 4 layers
/// vs the symmetric 32/32 of large-v3 — the only asymmetric size in
/// [`WHISPER_SIZES`]) may exhibit different numerical behaviour and need a
/// per-size calibration, but per the fabricated-pass ban a looser value may
/// land here **only after** the owner's real-checkpoint run (M4-14-T10)
/// measures an actual max |Δ| above 0.01. If that happens, calibrate honestly
/// at the measured architectural floor × 1.5–2 (the Kokoro
/// `PROSODY_F0_ATOL = 0.05` precedent) and record the SAME value redundantly
/// in all three places (this fn is the single source, the others mirror it):
///
///   1. this lookup's match arm (+ this rustdoc),
///   2. `docs/adr/M4-14-whisper-family.md` §D2 (measured value + derivation),
///   3. `.github/workflows/parity-whisper-real.yml` `PER_SIZE_ATOL` dict
///      (whose fabricated-pass guard cross-checks the Rust-printed atol and
///      fails the run on any drift between the two).
///
/// Unknown sizes panic — an explicit error, never a silent default
/// (FR-EX-08-shaped: a table row added without a tolerance decision must not
/// inherit one).
fn atol_for(size: &str) -> f32 {
    match size {
        // turbo: default 0.01 retained until the T10 real-checkpoint
        // measurement lands; loosening it pre-measurement is forbidden
        // (fabricated pass — see the doc above).
        "base" | "small" | "medium" | "large-v3" | "turbo" => ATOL,
        other => panic!("unknown whisper size {other:?} has no calibrated atol"),
    }
}

/// All whisper sizes tabled for T09/T11 (base is the historical default; the
/// rest each need their own `VOKRA_WHISPER_{SIZE}_GGUF` env var + fixture dir).
/// Rows skip cleanly when either the env var or the fixture dir is absent, so
/// CI (which sets neither) still runs the fixture-only tests unchanged.
const WHISPER_SIZES: &[&str] = &["base", "small", "medium", "large-v3", "turbo"];

/// Env-var name for a size's converted GGUF (`base` → `VOKRA_WHISPER_BASE_GGUF`).
fn size_env_var(size: &str) -> String {
    format!(
        "VOKRA_WHISPER_{}_GGUF",
        size.to_ascii_uppercase().replace('-', "_")
    )
}

/// Fixture dir for a size (`base` → `tests/parity/whisper_base/`).
fn fixtures_dir_for(size: &str) -> PathBuf {
    // CARGO_MANIFEST_DIR = <repo>/crates/vokra-models.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("parity")
        .join(format!("whisper_{}", size.replace('-', "_")))
}

/// Historical single-size helper preserved for the fixture-only tests below.
fn fixtures_dir() -> PathBuf {
    fixtures_dir_for("base")
}

fn read_f32_at(dir: &Path, name: &str) -> Vec<f32> {
    let path = dir.join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 4, 0, "{name}: not a whole number of f32");
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn read_f32(name: &str) -> Vec<f32> {
    read_f32_at(&fixtures_dir(), name)
}

fn manifest_at(dir: &Path) -> HashMap<String, String> {
    let text = std::fs::read_to_string(dir.join("manifest.txt")).expect("manifest");
    let mut m = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            m.insert(k.trim().to_owned(), v.trim().to_owned());
        }
    }
    m
}

fn manifest() -> HashMap<String, String> {
    manifest_at(&fixtures_dir())
}

fn man_usize(m: &HashMap<String, String>, k: &str) -> usize {
    m[k].parse()
        .unwrap_or_else(|_| panic!("manifest {k} not usize"))
}

fn man_u32s(m: &HashMap<String, String>, k: &str) -> Vec<u32> {
    m[k].split_whitespace()
        .map(|t| {
            t.parse()
                .unwrap_or_else(|_| panic!("manifest {k}: bad u32 {t:?}"))
        })
        .collect()
}

/// Parses `samples.txt` into `(ids, expected_text)` cases. The delimiter is
/// ` | ` (one space each side); the text keeps any further leading spaces.
fn load_samples_at(dir: &Path) -> Vec<(Vec<u32>, String)> {
    let text = std::fs::read_to_string(dir.join("samples.txt")).expect("samples.txt");
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim_end_matches('\n');
        if line.trim().is_empty() || line.trim_start().starts_with('#') {
            continue;
        }
        let (ids_str, text) = line.split_once('|').expect("`ids | text`");
        let ids: Vec<u32> = ids_str
            .split_whitespace()
            .map(|t| t.parse().unwrap())
            .collect();
        // Remove exactly the one delimiter space that follows `|`.
        let expected = text.strip_prefix(' ').unwrap_or(text).to_owned();
        out.push((ids, expected));
    }
    out
}

fn load_samples() -> Vec<(Vec<u32>, String)> {
    load_samples_at(&fixtures_dir())
}

/// Element-wise closeness with a diagnostic on the worst offender.
///
/// `atol` is the per-size tolerance from [`atol_for`] (M4-14-T04) — callers in
/// the size-table loops pass `atol_for(size)`; the base-pinned fixture-only /
/// GPU-e2e tests pass `atol_for("base")`. The `[parity]` diagnostic line's
/// `(atol …)` suffix is machine-parsed by parity-whisper-real.yml's
/// fabricated-pass guard, which cross-checks it against the workflow's own
/// `PER_SIZE_ATOL` mirror — keep the format stable.
fn assert_close(got: &[f32], expected: &[f32], ctx: &str, atol: f32) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{ctx}: length {} != expected {}",
        got.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0usize;
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        let d = (g - e).abs();
        if d > worst {
            worst = d;
            worst_i = i;
        }
    }
    // Always report the observed margin (visible with `--nocapture`) so parity
    // headroom is measurable, not just pass/fail.
    eprintln!(
        "[parity] {ctx}: max |Δ| = {worst:.3e} over {} elems (atol {atol})",
        got.len()
    );
    assert!(
        worst <= atol,
        "{ctx}: max |Δ| = {worst} at index {worst_i} (got {} vs {}) exceeds atol {atol}",
        got[worst_i],
        expected[worst_i]
    );
}

/// M4-14-T04: the lookup must stay at the FP32 default for every tabled size
/// until a real measurement justifies a per-size calibration (see
/// [`atol_for`]'s doc — loosening turbo before the T10 owner run is a
/// fabricated pass). This test is the tripwire: a calibration landing in
/// `atol_for` must consciously update the expectation here AND the ADR AND
/// the workflow's `PER_SIZE_ATOL` mirror.
#[test]
fn atol_lookup_defaults_to_fp32_bound_for_all_sizes() {
    for &size in WHISPER_SIZES {
        assert_eq!(
            atol_for(size),
            ATOL,
            "{size}: per-size atol must stay at the 0.01 default until a T10 \
             real-checkpoint measurement lands (fabricated-pass ban)"
        );
    }
    assert_eq!(ATOL, 0.01, "NFR-QL-01 FP32 parity bound");
}

/// Resolves the GGUF path for a whisper size. `VOKRA_WHISPER_GGUF` is preserved
/// as an alias for `VOKRA_WHISPER_BASE_GGUF` (R5 back-compat): a local dev with
/// only `VOKRA_WHISPER_GGUF` set still runs the base row unchanged. Returns
/// `None` (→ skip row) if neither the size-specific env var nor the alias (for
/// base only) is set.
fn gguf_path_for(size: &str) -> Option<std::ffi::OsString> {
    if let Some(p) = std::env::var_os(size_env_var(size)) {
        return Some(p);
    }
    if size == "base" {
        return std::env::var_os("VOKRA_WHISPER_GGUF");
    }
    None
}

/// Opens the converted GGUF for `size`, or `None` to skip cleanly. Skips also
/// when the sibling fixture dir is absent (needed by every gated test to read
/// `manifest.txt` / `input_pcm.f32` / `tokenizer.bin` alongside the GGUF).
fn open_gguf_for(size: &str) -> Option<GgufFile> {
    let path = gguf_path_for(size)?;
    if !fixtures_dir_for(size).is_dir() {
        return None;
    }
    Some(GgufFile::open(&path).unwrap_or_else(|e| panic!("open {}: {e}", size_env_var(size))))
}

/// Loads the converted GGUF for `size` behind an `Arc` (needed by
/// [`WhisperModel::decoder`], which takes `&Arc<Self>` — the handle is cloned
/// into the ownable, `Send` `DecoderState`).
fn load_model_for(size: &str) -> Option<Arc<WhisperModel>> {
    let file = open_gguf_for(size)?;
    Some(Arc::new(
        WhisperModel::from_gguf(&file).expect("load whisper model"),
    ))
}

/// Lists the whisper sizes that will actually exercise a table-driven row,
/// eprint-ing once at test start (visible with `--nocapture`). Rows without an
/// env var / fixture dir are skipped silently — the eprint is the only signal
/// that CI does not silently degrade to zero coverage after the refactor.
fn announce_active_sizes(test_name: &str) -> Vec<&'static str> {
    let mut active: Vec<&'static str> = Vec::new();
    for &size in WHISPER_SIZES {
        if gguf_path_for(size).is_some() && fixtures_dir_for(size).is_dir() {
            active.push(size);
        }
    }
    if active.is_empty() {
        eprintln!(
            "[parity/{test_name}] skip: set VOKRA_WHISPER_{{BASE,SMALL,MEDIUM,LARGE_V3,TURBO}}_GGUF \
             (VOKRA_WHISPER_GGUF still works as an alias for base)"
        );
    } else {
        eprintln!("[parity/{test_name}] running sizes: {}", active.join(", "));
    }
    active
}

// --- fixture-only tests (run in CI) -----------------------------------------

#[test]
fn log_mel_parity() {
    // Fixture-only: the front-end is pure DSP, no weights needed.
    let m = manifest();
    let n_mels = man_usize(&m, "n_mels");
    let mel_frames = man_usize(&m, "mel_frames");
    let pcm = read_f32("input_pcm.f32");
    let reference = read_f32("logmel.f32"); // [n_mels, mel_frames]

    let feats = mel::log_mel(&pcm, n_mels); // [n_mels, N_FRAMES]
    // Gather the first `mel_frames` frames to match the reference slice.
    let mut got = Vec::with_capacity(n_mels * mel_frames);
    for row in 0..n_mels {
        for t in 0..mel_frames {
            got.push(feats[row * N_FRAMES + t]);
        }
    }
    // Base fixture-only front-end (pure DSP): pinned to the base tolerance.
    assert_close(&got, &reference, "log-mel", atol_for("base"));
}

#[test]
fn detokenizer_samples_match_reference() {
    // Fixture-only: uses the committed tokenizer blob.
    let m = manifest();
    let eot = man_u32s(&m, "eot")[0];
    let blob = std::fs::read(fixtures_dir().join("tokenizer.bin")).expect("tokenizer.bin");
    let tok = WhisperTokenizer::from_bytes(&blob, eot).expect("parse tokenizer");
    assert_eq!(tok.vocab_size(), man_usize(&m, "vocab_tokenizer"));

    let samples = load_samples();
    assert!(samples.len() >= 3, "expected several detokenizer samples");
    for (ids, expected) in &samples {
        let got = tok.decode(ids).expect("decode");
        assert_eq!(&got, expected, "detokenize {ids:?}");
    }
}

// --- GGUF-gated numerical parity tests --------------------------------------

#[test]
fn weight_load_and_config_smoke() {
    let active = announce_active_sizes("weight_load_and_config_smoke");
    for size in active {
        let Some(model) = load_model_for(size) else {
            continue;
        };
        let cfg = model.config();
        let m = manifest_at(&fixtures_dir_for(size));
        assert_eq!(cfg.n_mels, man_usize(&m, "n_mels"), "{size}: n_mels");
        assert_eq!(cfg.d_model, man_usize(&m, "d_model"), "{size}: d_model");
        assert_eq!(
            cfg.n_audio_ctx,
            man_usize(&m, "n_audio_ctx"),
            "{size}: n_audio_ctx"
        );
        assert_eq!(cfg.n_vocab, man_usize(&m, "vocab"), "{size}: n_vocab");
        assert_eq!(cfg.eot, man_u32s(&m, "eot")[0], "{size}: eot");
        assert_eq!(
            cfg.decoder_start_ids,
            man_u32s(&m, "prefix"),
            "{size}: decoder_start_ids"
        );
    }
}

#[test]
fn encoder_parity() {
    let active = announce_active_sizes("encoder_parity");
    for size in active {
        let Some(model) = load_model_for(size) else {
            continue;
        };
        let dir = fixtures_dir_for(size);
        let m = manifest_at(&dir);
        let enc_pos = man_usize(&m, "enc_pos");
        let d = man_usize(&m, "d_model");
        let pcm = read_f32_at(&dir, "input_pcm.f32");
        let reference = read_f32_at(&dir, "encoder.f32"); // [enc_pos, d]

        let enc = model.encode_pcm(&pcm).expect("encode");
        assert_eq!(
            enc.n_ctx,
            man_usize(&m, "n_audio_ctx"),
            "{size}: n_audio_ctx"
        );
        assert_eq!(enc.d_model, d, "{size}: d_model");
        let got = &enc.hidden[..enc_pos * d];
        assert_close(
            got,
            &reference,
            &format!("{size}: encoder hidden states"),
            atol_for(size),
        );
    }
}

#[test]
fn decoder_logits_parity_full_and_cached() {
    let active = announce_active_sizes("decoder_logits_parity_full_and_cached");
    for size in active {
        let Some(model) = load_model_for(size) else {
            continue;
        };
        let dir = fixtures_dir_for(size);
        let m = manifest_at(&dir);
        let prefix = man_u32s(&m, "prefix");
        let vocab = man_usize(&m, "vocab");
        let pcm = read_f32_at(&dir, "input_pcm.f32");
        let reference = read_f32_at(&dir, "logits_last.f32"); // [vocab], last prefix position

        let enc = model.encode_pcm(&pcm).expect("encode");

        // Full-sequence forward: logits for the whole prefix at once.
        let mut state = model.decoder(&enc).expect("decoder");
        let full = state.step(&prefix).expect("decoder step");
        assert_eq!(
            full.len(),
            prefix.len() * vocab,
            "{size}: full logits length"
        );
        let full_last = &full[(prefix.len() - 1) * vocab..];
        assert_close(
            full_last,
            &reference,
            &format!("{size}: decoder logits (full forward)"),
            atol_for(size),
        );

        // Cached (token-by-token) forward must reproduce the same last-position
        // logits, validating the KV cache.
        state.reset();
        let mut cached_last = Vec::new();
        for &tok in &prefix {
            cached_last = state.step_last(&[tok]).expect("cached step");
        }
        assert_close(
            &cached_last,
            &reference,
            &format!("{size}: decoder logits (cached)"),
            atol_for(size),
        );
        assert_close(
            &cached_last,
            full_last,
            &format!("{size}: cached vs full last-position logits"),
            atol_for(size),
        );

        // Every prefix position's argmax should match the reference too.
        let ref_argmax = man_u32s(&m, "prefix_argmax");
        for (p, &want) in ref_argmax.iter().enumerate() {
            let row = &full[p * vocab..(p + 1) * vocab];
            let got = argmax(row);
            assert_eq!(got, want, "{size}: prefix position {p} argmax");
        }
    }
}

#[test]
fn greedy_transcript_parity() {
    let active = announce_active_sizes("greedy_transcript_parity");
    for size in active {
        let Some(model) = load_model_for(size) else {
            continue;
        };
        let dir = fixtures_dir_for(size);
        let m = manifest_at(&dir);
        let prefix = man_u32s(&m, "prefix");
        let eot = man_u32s(&m, "eot")[0];
        let expected_tokens = man_u32s(&m, "greedy_tokens");
        let pcm = read_f32_at(&dir, "input_pcm.f32");

        let enc = model.encode_pcm(&pcm).expect("encode");
        let mut state = model.decoder(&enc).expect("decoder");
        let tokens = greedy_decode(&mut state, &prefix, eot, 64).expect("greedy");
        assert_eq!(tokens, expected_tokens, "{size}: greedy token sequence");

        // Detokenize and compare to the reference transcript (the first
        // `samples.txt` case is exactly these greedy ids, whitespace preserved).
        let blob = std::fs::read(dir.join("tokenizer.bin")).expect("tokenizer.bin");
        let tok = WhisperTokenizer::from_bytes(&blob, eot).expect("tokenizer");
        let text = tok.decode(&tokens).expect("decode");
        let (_, expected_text) = load_samples_at(&dir)
            .into_iter()
            .find(|(ids, _)| ids == &tokens)
            .expect("greedy tokens present as a samples.txt case");
        assert_eq!(text, expected_text, "{size}: greedy transcript");
    }
}

#[test]
fn asr_beam_width_one_equals_greedy_and_renders() {
    // Exercises the otherwise-untested asr.rs surface: WhisperBeamScorer (via
    // transcribe_tokens_beam) and AsrEngine::transcribe / render. Same
    // skip-cleanly gate as the other GGUF-backed tests.
    let active = announce_active_sizes("asr_beam_width_one_equals_greedy_and_renders");
    for size in active {
        let Some(file) = open_gguf_for(size) else {
            continue;
        };
        let dir = fixtures_dir_for(size);
        let pcm = read_f32_at(&dir, "input_pcm.f32");

        let asr = WhisperAsr::from_gguf(&file).expect("load whisper asr");
        let prefix = asr.model().config().decoder_start_ids.clone();
        let eot = asr.model().config().eot;

        // Internal oracle: a width-1 beam makes the same argmax decisions as greedy.
        // `beam_search` returns the whole hypothesis (forced prefix included) while
        // `transcribe_tokens` (greedy) returns only the generated suffix, so the
        // sound relationship is `beam == prefix ++ greedy`.
        let greedy = asr.transcribe_tokens(&pcm).expect("greedy tokens");
        let beam = asr
            .transcribe_tokens_beam(&pcm, &BeamSearchConfig::greedy(64))
            .expect("beam tokens");
        let mut expected = prefix;
        expected.extend_from_slice(&greedy);
        assert_eq!(
            beam, expected,
            "{size}: beam_width=1 must reproduce greedy's decisions"
        );

        // Detokenized render: attach the fixture tokenizer and check the assembled
        // transcription equals the greedy detokenization.
        let blob = std::fs::read(dir.join("tokenizer.bin")).expect("tokenizer.bin");
        let tok = WhisperTokenizer::from_bytes(&blob, eot).expect("tokenizer");
        let detok = tok.decode(&greedy).expect("decode");
        let asr_with = WhisperAsr::from_gguf(&file)
            .expect("load whisper asr")
            .with_tokenizer(tok);
        assert_eq!(
            asr_with.transcribe(&pcm).expect("transcribe").text,
            detok,
            "{size}: AsrEngine::transcribe must equal the greedy detokenization"
        );

        // Without a tokenizer (the M0 converter embeds none) render falls back to
        // the bracketed id list; a future GGUF that embeds one would detokenize
        // instead, so accept either sound rendering.
        let bracketed = format!(
            "[no tokenizer; token ids: {}]",
            greedy
                .iter()
                .map(u32::to_string)
                .collect::<Vec<_>>()
                .join(" ")
        );
        let default_text = asr.transcribe(&pcm).expect("transcribe").text;
        assert!(
            default_text == bracketed || default_text == detok,
            "{size}: default render was neither the bracketed fallback nor the detokenization: {default_text:?}"
        );
    }
}

fn argmax(v: &[f32]) -> u32 {
    let mut best = 0usize;
    let mut best_v = f32::NEG_INFINITY;
    for (i, &x) in v.iter().enumerate() {
        if x > best_v {
            best_v = x;
            best = i;
        }
    }
    best as u32
}

// --- Metal e2e parity (Phase 4) ---------------------------------------------

/// Full Whisper on Metal: the encoder + decoder + greedy decode routed through
/// `Compute::Metal` must match the `Compute::Cpu` path (the onnxruntime-agreeing
/// reference) within the FP32 bound (NFR-QL-01, `atol = 0.01`), and the greedy
/// token sequence must match **exactly**. Doubly gated — needs the whisper GGUF
/// (`VOKRA_WHISPER_GGUF`) **and** a real Metal device — and skips cleanly (never
/// a silent CPU substitute, FR-EX-08) when either is absent. Run with:
///
/// ```text
/// VOKRA_WHISPER_GGUF=whisper-base.gguf cargo test -p vokra-models --features metal whisper_metal_e2e -- --nocapture
/// ```
#[cfg(all(feature = "metal", any(target_os = "macos", target_os = "ios")))]
#[test]
fn whisper_metal_e2e_matches_cpu() {
    use vokra_core::BackendKind;
    use vokra_models::{Compute, HotOp};

    // Metal e2e is unchanged by the T09/T11 size refactor — still base-only
    // (the M2-01 target is whisper-base parity on M1 iMac).
    let Some(model) = load_model_for("base") else {
        eprintln!(
            "skip: set VOKRA_WHISPER_BASE_GGUF (or VOKRA_WHISPER_GGUF) for the full Metal e2e"
        );
        return;
    };
    // The complete Whisper hot-op set (Metal must now cover all six).
    let hot = [
        HotOp::Gemm,
        HotOp::Gemv,
        HotOp::Softmax,
        HotOp::LayerNorm,
        HotOp::Gelu,
        HotOp::Conv1d,
    ];
    // Device-gated: build a fully-covering Metal dispatcher, or skip on an
    // explicit BackendUnavailable (no device) — never a silent CPU fall back.
    let metal = match Compute::for_backend(BackendKind::Metal, &hot) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("skip Metal whisper e2e (no Metal device): {e}");
            return;
        }
    };
    assert_eq!(metal.backend_name(), "metal");

    let pcm = read_f32("input_pcm.f32");

    // 1) Encoder parity — same weights, two backends (conv stem + attention).
    let cpu_enc = model.encode_pcm(&pcm).expect("cpu encode");
    let metal_enc = model.encode_pcm_with(&metal, &pcm).expect("metal encode");
    assert_close(
        &metal_enc.hidden,
        &cpu_enc.hidden,
        "whisper encoder (Metal vs CPU)",
        atol_for("base"), // Metal e2e stays base-only (M2-01 target)
    );

    // 2) Decoder logits parity — full forward over the forced prefix.
    let prefix = model.config().decoder_start_ids.clone();
    let mut cpu_dec = model.decoder(&cpu_enc).expect("cpu decoder");
    let mut metal_dec = model
        .decoder_with_backend(&metal_enc, BackendKind::Metal)
        .expect("metal decoder");
    let cpu_logits = cpu_dec.step(&prefix).expect("cpu decoder step");
    let metal_logits = metal_dec.step(&prefix).expect("metal decoder step");
    assert_close(
        &metal_logits,
        &cpu_logits,
        "whisper decoder logits (Metal vs CPU)",
        atol_for("base"),
    );

    // 3) Greedy token sequence — must match the CPU decode exactly (the strongest
    // end-to-end check; argmax gaps dwarf the sub-atol per-logit differences).
    let eot = model.config().eot;
    cpu_dec.reset();
    let cpu_tokens = greedy_decode(&mut cpu_dec, &prefix, eot, 64).expect("cpu greedy");
    metal_dec.reset();
    let metal_tokens = greedy_decode(&mut metal_dec, &prefix, eot, 64).expect("metal greedy");
    assert_eq!(
        metal_tokens, cpu_tokens,
        "greedy token sequence (Metal vs CPU) must be identical"
    );
    eprintln!(
        "[parity] whisper Metal e2e: {} greedy tokens match CPU exactly",
        metal_tokens.len()
    );
}

// --- CUDA e2e parity (Phase 4) ----------------------------------------------

/// Full Whisper on CUDA: the encoder + decoder + greedy decode routed through
/// `Compute::Cuda` must match the `Compute::Cpu` path (the onnxruntime-agreeing
/// reference) within the FP32 bound (NFR-QL-01, `atol = 0.01`), and the greedy
/// token sequence must match **exactly**. Doubly gated — needs the whisper GGUF
/// (`VOKRA_WHISPER_GGUF`) **and** a real NVIDIA GPU (dlopen'd `libcuda` + a
/// device) — and skips cleanly (never a silent CPU substitute, FR-EX-08) when
/// either is absent. This crate is authored on an Apple Mac with no NVIDIA GPU,
/// so it skips here; it runs for real on the **vast.ai RTX 4090** (M2-03-T25):
///
/// ```text
/// VOKRA_WHISPER_GGUF=whisper-base.gguf cargo test -p vokra-models --features cuda whisper_cuda_e2e -- --nocapture
/// ```
#[cfg(all(feature = "cuda", any(unix, windows)))]
#[test]
fn whisper_cuda_e2e_matches_cpu() {
    use vokra_core::BackendKind;
    use vokra_models::{Compute, HotOp};

    // CUDA e2e is unchanged by the T09/T11 size refactor — still base-only
    // (M2-03-T25 targets whisper-base parity on vast.ai RTX 4090).
    let Some(model) = load_model_for("base") else {
        eprintln!(
            "skip: set VOKRA_WHISPER_BASE_GGUF (or VOKRA_WHISPER_GGUF) for the full CUDA e2e"
        );
        return;
    };
    // The complete Whisper hot-op set (CUDA must now cover all six).
    let hot = [
        HotOp::Gemm,
        HotOp::Gemv,
        HotOp::Softmax,
        HotOp::LayerNorm,
        HotOp::Gelu,
        HotOp::Conv1d,
    ];
    // Device-gated: build a fully-covering CUDA dispatcher, or skip on an
    // explicit BackendUnavailable (no driver/device) — never a silent CPU fall
    // back. A coverage `UnsupportedOp` here would be a real bug (Phase 4 covers
    // every op), so it is NOT swallowed.
    let cuda = match Compute::for_backend(BackendKind::Cuda, &hot) {
        Ok(c) => c,
        Err(vokra_core::VokraError::BackendUnavailable(e)) => {
            eprintln!("skip CUDA whisper e2e (no CUDA device): {e}");
            return;
        }
        Err(e) => panic!("unexpected error building a fully-covered CUDA dispatcher: {e}"),
    };
    assert_eq!(cuda.backend_name(), "cuda");

    let pcm = read_f32("input_pcm.f32");

    // 1) Encoder parity — same weights, two backends (conv stem + attention).
    let cpu_enc = model.encode_pcm(&pcm).expect("cpu encode");
    let cuda_enc = model.encode_pcm_with(&cuda, &pcm).expect("cuda encode");
    assert_close(
        &cuda_enc.hidden,
        &cpu_enc.hidden,
        "whisper encoder (CUDA vs CPU)",
        atol_for("base"), // CUDA e2e stays base-only (M2-03-T25 target)
    );

    // 2) Decoder logits parity — full forward over the forced prefix.
    let prefix = model.config().decoder_start_ids.clone();
    let mut cpu_dec = model.decoder(&cpu_enc).expect("cpu decoder");
    let mut cuda_dec = model
        .decoder_with_backend(&cuda_enc, BackendKind::Cuda)
        .expect("cuda decoder");
    let cpu_logits = cpu_dec.step(&prefix).expect("cpu decoder step");
    let cuda_logits = cuda_dec.step(&prefix).expect("cuda decoder step");
    assert_close(
        &cuda_logits,
        &cpu_logits,
        "whisper decoder logits (CUDA vs CPU)",
        atol_for("base"),
    );

    // 3) Greedy token sequence — must match the CPU decode exactly (the strongest
    // end-to-end check; argmax gaps dwarf the sub-atol per-logit differences).
    let eot = model.config().eot;
    cpu_dec.reset();
    let cpu_tokens = greedy_decode(&mut cpu_dec, &prefix, eot, 64).expect("cpu greedy");
    cuda_dec.reset();
    let cuda_tokens = greedy_decode(&mut cuda_dec, &prefix, eot, 64).expect("cuda greedy");
    assert_eq!(
        cuda_tokens, cpu_tokens,
        "greedy token sequence (CUDA vs CPU) must be identical"
    );
    eprintln!(
        "[parity] whisper CUDA e2e: {} greedy tokens match CPU exactly",
        cuda_tokens.len()
    );
}
