//! Kokoro-82M numerical parity vs the upstream reference (M2-07-T11 / T17).
//!
//! Fixtures live in `tests/parity/kokoro/` and are regenerated by
//! `tools/parity/dump_kokoro_reference.py`. All tensors dumped by the reference
//! script must match the native forward output at FP32 `atol = 0.01`
//! (NFR-QL-01).
//!
//! The full forward requires the converted **GGUF**, which is too large to
//! commit, so every test that touches [`KokoroTts`] is gated on the
//! `VOKRA_KOKORO_GGUF` environment variable and skips cleanly when it is
//! unset (e.g. in CI). The fixture-only tests (manifest read-back, shape /
//! length checks) run everywhere.
//!
//! # `mode = placeholder` vs `mode = full` (per module, T17)
//!
//! The dumper writes a global `mode = full` marker when at least one module
//! carries a PyTorch re-forward, plus per-module keys `<module>_mode ∈
//! {placeholder, full}` for `text_encoder`, `bert`, `prosody`, `decoder`. Each
//! gated test below reads only the marker for the module it exercises:
//!
//! * `<module>_mode = placeholder` — shape / length checks only; byte-level
//!   parity is intentionally skipped with a `eprintln!`.
//! * `<module>_mode = full` — byte-level parity vs the reference tensor at
//!   `atol = 0.01`. Skipped cleanly when `VOKRA_KOKORO_GGUF` is unset (no
//!   Rust forward to compare against without a real voice GGUF).
//!
//! The T17 dump upgrades `text_encoder` + `bert` to `full`; `prosody` and
//! `decoder` remain `placeholder` (length regulation + iSTFT require a
//! dedicated re-forward WP). Rust-side tests below skip byte-parity for
//! those two per FR-EX-08 (never a fabricated pass).

#![allow(clippy::items_after_statements)]

use std::collections::HashMap;
use std::path::{Path, PathBuf};

const ATOL: f32 = 0.01;

/// Fixture dir for kokoro (repo-root-relative `tests/parity/kokoro/`).
fn fixtures_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR = <repo>/crates/vokra-models.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("parity")
        .join("kokoro")
}

fn read_f32(name: &str) -> Vec<f32> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 4, 0, "{name}: not a whole number of f32");
    bytes
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn read_i64(name: &str) -> Vec<i64> {
    let path = fixtures_dir().join(name);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert_eq!(bytes.len() % 8, 0, "{name}: not a whole number of i64");
    bytes
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes([c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7]]))
        .collect()
}

fn manifest() -> HashMap<String, String> {
    let text = std::fs::read_to_string(fixtures_dir().join("manifest.txt")).expect("manifest");
    let mut m = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            m.insert(k.trim().to_owned(), v.trim().to_owned());
        }
    }
    m
}

fn man_usize(m: &HashMap<String, String>, k: &str) -> usize {
    m.get(k)
        .unwrap_or_else(|| panic!("manifest missing key {k}"))
        .parse()
        .unwrap_or_else(|_| panic!("manifest {k} not usize"))
}

/// Element-wise closeness with a diagnostic on the worst offender (identical
/// convention to `parity_whisper.rs`).
#[allow(dead_code)]
fn assert_close(got: &[f32], expected: &[f32], ctx: &str) {
    assert_eq!(
        got.len(),
        expected.len(),
        "{ctx}: length {} != expected {}",
        got.len(),
        expected.len()
    );
    let mut worst = 0.0f32;
    let mut worst_i = 0usize;
    for (i, (g, e)) in got.iter().zip(expected).enumerate() {
        let d = (g - e).abs();
        if d > worst {
            worst = d;
            worst_i = i;
        }
    }
    eprintln!(
        "[parity] {ctx}: max |Δ| = {worst:.3e} over {} elems (atol {ATOL})",
        got.len()
    );
    assert!(
        worst <= ATOL,
        "{ctx}: max |Δ| = {worst} at index {worst_i} (got {} vs {}) exceeds atol {ATOL}",
        got[worst_i],
        expected[worst_i]
    );
}

/// Skip cleanly when the fixture dir is absent (fresh checkout without the
/// dumper being run yet). This keeps CI green even before the fixtures land.
fn fixtures_present() -> bool {
    fixtures_dir().is_dir() && fixtures_dir().join("manifest.txt").is_file()
}

// -----------------------------------------------------------------------------
// Fixture-only tests (no GGUF required, run on every PR)
// -----------------------------------------------------------------------------

/// Manifest → known-shape cross-check. Guarantees the dumper's shape contract
/// (what the Rust side depends on) is preserved across regenerations. Runs
/// wherever the fixture is present.
#[test]
fn manifest_shapes_are_self_consistent() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}. Run tools/parity/dump_kokoro_reference.py.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();

    // Every dimensional key the harness relies on must be present.
    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let dec_frames = man_usize(&m, "dec_frames");
    let hidden_dim = man_usize(&m, "hidden_dim");
    let style_dim = man_usize(&m, "style_dim");
    let mel_channels = man_usize(&m, "mel_channels");
    let pcm_len = man_usize(&m, "pcm_len");
    let prosody_channels = man_usize(&m, "prosody_channels");

    // Dumper contract: NUM_PHONEMES / ENC_POS / DEC_FRAMES / PCM_LEN /
    // PROSODY_CHANNELS are Python-side constants; they must stay positive.
    assert!(num_phonemes > 0, "num_phonemes > 0");
    assert!(enc_pos > 0, "enc_pos > 0");
    assert!(dec_frames > 0, "dec_frames > 0");
    assert!(pcm_len > 0, "pcm_len > 0");
    assert!(hidden_dim > 0, "hidden_dim > 0");
    assert!(style_dim > 0, "style_dim > 0");
    assert!(mel_channels > 0, "mel_channels > 0");
    assert_eq!(prosody_channels, 2, "prosody = (duration, F0/energy)");
}

/// Binary length ↔ manifest cross-check. Catches a partially-written or
/// mismatched fixture set before any parity comparison runs.
#[test]
fn fixture_binaries_match_manifest_lengths() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let dec_frames = man_usize(&m, "dec_frames");
    let hidden_dim = man_usize(&m, "hidden_dim");
    let style_dim = man_usize(&m, "style_dim");
    let mel_channels = man_usize(&m, "mel_channels");
    let pcm_len = man_usize(&m, "pcm_len");
    let prosody_channels = man_usize(&m, "prosody_channels");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes, "phoneme_ids.i64 length");
    for (i, id) in ids.iter().enumerate() {
        assert!(*id >= 0, "phoneme_ids[{i}] = {id} < 0");
    }

    let style = read_f32("style.f32");
    assert_eq!(style.len(), style_dim, "style.f32 length");

    let enc = read_f32("text_encoder.f32");
    assert_eq!(enc.len(), enc_pos * hidden_dim, "text_encoder.f32 length");

    let pros = read_f32("prosody.f32");
    assert_eq!(pros.len(), enc_pos * prosody_channels, "prosody.f32 length");

    let mel = read_f32("mel_pre_istft.f32");
    assert_eq!(
        mel.len(),
        dec_frames * mel_channels,
        "mel_pre_istft.f32 length"
    );

    let pcm = read_f32("pcm.f32");
    assert_eq!(pcm.len(), pcm_len, "pcm.f32 length");
}

/// Manifest mode marker. In `placeholder`, byte-level parity is intentionally
/// skipped by the gated tests below; in `full`, per-module keys
/// (`<module>_mode`) decide byte-parity per module. This test just documents
/// which mode the current fixture set encodes, visible with `--nocapture`.
#[test]
fn manifest_declares_mode() {
    if !fixtures_present() {
        eprintln!(
            "[parity_kokoro] SKIP: no fixture dir at {:?}.",
            fixtures_dir()
        );
        return;
    }
    let m = manifest();
    let mode = m
        .get("mode")
        .cloned()
        .unwrap_or_else(|| "placeholder".to_owned());
    let te = module_mode(&m, "text_encoder_mode");
    let bert = module_mode(&m, "bert_mode");
    let pros = module_mode(&m, "prosody_mode");
    let dec = module_mode(&m, "decoder_mode");
    eprintln!(
        "[parity_kokoro] fixture mode = {mode}; per-module modes: \
         text_encoder = {te}, bert = {bert}, prosody = {pros}, decoder = {dec}"
    );
    assert!(
        matches!(mode.as_str(), "placeholder" | "full"),
        "mode must be `placeholder` or `full`, got {mode:?}"
    );
    for (name, val) in [
        ("text_encoder_mode", te.as_str()),
        ("bert_mode", bert.as_str()),
        ("prosody_mode", pros.as_str()),
        ("decoder_mode", dec.as_str()),
    ] {
        assert!(
            matches!(val, "placeholder" | "full"),
            "{name} must be `placeholder` or `full`, got {val:?}"
        );
    }
}

/// Reads a per-module mode marker (`<module>_mode`) from the manifest, falling
/// back to the global `mode` for backward compatibility with older fixtures
/// that only carried the global marker. Absent entirely → `"placeholder"`
/// (safest default: never claim a byte-parity that wasn't actually generated).
fn module_mode(m: &HashMap<String, String>, key: &str) -> String {
    if let Some(v) = m.get(key) {
        return v.clone();
    }
    m.get("mode")
        .cloned()
        .unwrap_or_else(|| "placeholder".to_owned())
}

// -----------------------------------------------------------------------------
// GGUF-gated tests (skip cleanly without `VOKRA_KOKORO_GGUF`)
// -----------------------------------------------------------------------------

/// Loads a converted Kokoro voice GGUF referenced by `VOKRA_KOKORO_GGUF`, or
/// `None` to skip. Also skips when the fixture dir is missing (we need the
/// manifest / phoneme ids / style to drive a forward).
fn load_gguf_path() -> Option<std::ffi::OsString> {
    if !fixtures_present() {
        return None;
    }
    std::env::var_os("VOKRA_KOKORO_GGUF")
}

/// End-to-end shape parity: the native `synthesize_phonemes` output shape
/// (post-iSTFT PCM) must be consistent with the manifest's `sample_rate`,
/// `num_phonemes`, and the reference dumper's per-phoneme frame budget. Byte-
/// level PCM parity requires `decoder_mode = full` (skipped otherwise).
#[test]
fn e2e_forward_matches_reference_shape() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!(
            "[parity_kokoro] SKIP: set VOKRA_KOKORO_GGUF to a converted Kokoro voice \
             GGUF to run the end-to-end forward parity."
        );
        return;
    };
    let m = manifest();
    let num_phonemes = man_usize(&m, "num_phonemes");
    let style_dim = man_usize(&m, "style_dim");
    let sample_rate = man_usize(&m, "sample_rate");
    let decoder_mode = module_mode(&m, "decoder_mode");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);
    let style = read_f32("style.f32");
    assert_eq!(style.len(), style_dim);

    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!(
            "load VOKRA_KOKORO_GGUF = {gguf:?}: {e}. Convert via \
             `vokra-cli convert --model kokoro-82m ...` first."
        )
    });

    // The native forward returns `SynthesizedAudio { samples, sample_rate }`.
    // The parity contract here is:
    //   * shape / length matches the reference dumper's `pcm.f32`, and
    //   * (decoder_mode = full only) byte-level closeness at ATOL.
    let ref_pcm = read_f32("pcm.f32");
    assert!(!ref_pcm.is_empty());

    let audio = tts
        .synthesize_phonemes(&ids, None, Some(&style), 0.0, 1.0)
        .expect("kokoro forward");

    // Sample-rate cross-check: dumper's manifest must agree with the loaded
    // voice's declared sample rate (FR-EX-08: a silent mismatch would mean
    // the fixture is for a *different* voice than the GGUF under test).
    assert_eq!(
        audio.sample_rate as usize, sample_rate,
        "native sample rate {} Hz != manifest {} Hz",
        audio.sample_rate, sample_rate,
    );

    // Shape check: the reference dump caps PCM at `pcm_len`, and the native
    // forward's actual length must not be *less* than that (dumper caps, not
    // truncates the native output). If more, the check compares the leading
    // slice.
    assert!(
        audio.samples.len() >= ref_pcm.len(),
        "native PCM length {} < reference {}",
        audio.samples.len(),
        ref_pcm.len()
    );
    eprintln!(
        "[parity_kokoro] shape OK: native {} samples, reference {} samples, sr {sample_rate} Hz",
        audio.samples.len(),
        ref_pcm.len()
    );

    if decoder_mode == "placeholder" {
        eprintln!(
            "[parity_kokoro] SKIP byte-level pcm parity: decoder_mode = placeholder. \
             Regenerate fixtures with a decoder NumPy re-forward to enable."
        );
        return;
    }

    assert_close(&audio.samples[..ref_pcm.len()], &ref_pcm, "kokoro pcm");
}

// -----------------------------------------------------------------------------
// Per-module byte-level parity tests (T17, gated on `<module>_mode = full`)
// -----------------------------------------------------------------------------
//
// These invoke the internal component forwards (text_encoder, bert) through
// the public `KokoroTts::from_path` load path + a purpose-built accessor. All
// skip cleanly when `VOKRA_KOKORO_GGUF` is unset (no Rust forward to compare).
// They also skip cleanly when the module's `<module>_mode = placeholder`.

/// The text_encoder Rust forward at `atol = 0.01` vs the reference dumped in
/// `text_encoder.f32`. Enabled when `text_encoder_mode = full`.
#[test]
fn text_encoder_forward_bit_parity() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!("[parity_kokoro] SKIP: VOKRA_KOKORO_GGUF unset.");
        return;
    };
    let m = manifest();
    let te_mode = module_mode(&m, "text_encoder_mode");
    if te_mode != "full" {
        eprintln!("[parity_kokoro] SKIP text_encoder byte parity: text_encoder_mode = {te_mode}");
        return;
    }

    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let hidden_dim = man_usize(&m, "hidden_dim");

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);

    let expected = read_f32("text_encoder.f32");
    assert_eq!(
        expected.len(),
        enc_pos * hidden_dim,
        "text_encoder.f32 shape = [enc_pos, hidden_dim]"
    );

    // Drive the Rust text_encoder forward via the tester bridge on `KokoroTts`.
    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!("load VOKRA_KOKORO_GGUF = {gguf:?}: {e}");
    });
    let full = tts
        .text_encoder_forward_for_parity(&ids)
        .expect("text_encoder forward");
    // Full output is [t, hidden_dim] row-major; compare its first ENC_POS rows.
    let head_len = enc_pos * hidden_dim;
    assert!(
        full.len() >= head_len,
        "native text_encoder output {} shorter than expected head {head_len}",
        full.len()
    );
    assert_close(&full[..head_len], &expected, "kokoro text_encoder head");
}

/// The bert Rust forward at `atol = 0.01` vs the reference dumped in
/// `bert.f32`. Enabled when `bert_mode = full`; requires the voice GGUF to
/// carry the PL-BERT branch (the canary tensor
/// `bert.module.embeddings.word_embeddings.weight`).
#[test]
fn bert_forward_bit_parity() {
    let Some(gguf) = load_gguf_path() else {
        eprintln!("[parity_kokoro] SKIP: VOKRA_KOKORO_GGUF unset.");
        return;
    };
    let m = manifest();
    let bert_mode = module_mode(&m, "bert_mode");
    if bert_mode != "full" {
        eprintln!("[parity_kokoro] SKIP bert byte parity: bert_mode = {bert_mode}");
        return;
    }

    let num_phonemes = man_usize(&m, "num_phonemes");
    let enc_pos = man_usize(&m, "enc_pos");
    let bert_out_dim = man_usize(&m, "bert_out_dim");
    assert!(
        bert_out_dim > 0,
        "bert_out_dim = 0 → dumper wrote no bert.f32; \
         bert_mode = full is a manifest bug"
    );

    let ids = read_i64("phoneme_ids.i64");
    assert_eq!(ids.len(), num_phonemes);

    let expected = read_f32("bert.f32");
    assert_eq!(
        expected.len(),
        enc_pos * bert_out_dim,
        "bert.f32 shape = [enc_pos, bert_out_dim]"
    );

    let tts = vokra_models::kokoro::KokoroTts::from_path(&gguf).unwrap_or_else(|e| {
        panic!("load VOKRA_KOKORO_GGUF = {gguf:?}: {e}");
    });
    let full = tts
        .bert_forward_for_parity(&ids)
        .expect("bert forward — voice must carry the PL-BERT branch (canary tensor present)");
    let head_len = enc_pos * bert_out_dim;
    assert!(
        full.len() >= head_len,
        "native bert output {} shorter than expected head {head_len}",
        full.len()
    );
    assert_close(&full[..head_len], &expected, "kokoro bert head");
}
