//! Independent real-checkpoint parity for the canonical Charsiu aligner.
//!
//! The committed fixture is generated by
//! `tools/parity/charsiu_dump_reference.py`, which runs Transformers'
//! official `Wav2Vec2ForCTC` implementation against the pinned upstream
//! checkpoint.  The 360 MiB GGUF is intentionally not committed: point
//! `VOKRA_CHARSIU_GGUF` at the converted artifact to fire this leg.

use std::path::Path;

use vokra_models::align::charsiu::Charsiu;

const PCM_BYTES: &[u8] = include_bytes!("fixtures/charsiu/pcm_400.f32.bin");
const LOGITS_BYTES: &[u8] = include_bytes!("fixtures/charsiu/logits_1x42.f32.bin");
// Registered from the historical independent VAST measurement (7.629e-6);
// do not widen this bound to match an observed result.
const FP32_ATOL: f32 = 0.0002;

fn decode_f32(bytes: &[u8]) -> Vec<f32> {
    assert_eq!(
        bytes.len() % 4,
        0,
        "fixture byte length must be f32-aligned"
    );
    bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect()
}

#[test]
fn canonical_checkpoint_matches_transformers_logits() {
    let Some(path) = std::env::var_os("VOKRA_CHARSIU_GGUF") else {
        eprintln!(
            "[parity_charsiu] SKIP: set VOKRA_CHARSIU_GGUF to the converted pinned \
             charsiu/en_w2v2_fc_10ms artifact"
        );
        return;
    };
    let model = Charsiu::from_gguf(Path::new(&path)).expect("bind canonical Charsiu GGUF");
    let pcm = decode_f32(PCM_BYTES);
    let expected = decode_f32(LOGITS_BYTES);
    let (got, frames) = model
        .logits(&pcm, 16_000)
        .expect("run real Charsiu forward");
    assert_eq!(frames, 1);
    assert_eq!(got.len(), expected.len());

    let mut max_abs = 0.0f32;
    let mut max_index = 0usize;
    for (i, (&actual, &reference)) in got.iter().zip(&expected).enumerate() {
        let delta = (actual - reference).abs();
        if delta > max_abs {
            max_abs = delta;
            max_index = i;
        }
    }
    eprintln!(
        "CHARSIU_OFFICIAL_PARITY_METRICS frames={frames} logits={} max_abs={max_abs:.9} index={max_index} \
         rust={:.9} transformers={:.9} atol={FP32_ATOL:.9}",
        got.len(),
        got[max_index],
        expected[max_index]
    );

    assert!(
        max_abs <= FP32_ATOL,
        "Charsiu logits exceed the independent Transformers parity gate: \
         max_abs={max_abs:.9e} at {max_index}, atol={FP32_ATOL:.9e}"
    );
    eprintln!(
        "CHARSIU_OFFICIAL_PARITY PASS max_abs={max_abs:.9} atol={FP32_ATOL:.9} \
         frames={frames} reference=transformers.Wav2Vec2ForCTC fixture=official_canned_pcm"
    );
}

#[test]
fn committed_fixture_has_the_pinned_shape() {
    assert_eq!(decode_f32(PCM_BYTES).len(), 400);
    assert_eq!(decode_f32(LOGITS_BYTES).len(), 42);
}
