//! `whisper-extras` family — real-checkpoint parity harness.
//!
//! Covered models (both = Whisper large-v3 encoder + 2-layer decoder, same
//! shape quintuple `(d_model=1280, n_audio_layer=32, n_text_layer=2,
//! n_mels=128, vocab=51866)`; distinct upstream + license + arch tag):
//!
//! - **distil-whisper / distil-large-v3.5** (MIT / MIT) —
//!   [`vokra_models::distil_whisper::EXPECTED_ARCH`] = `"distil-whisper"`.
//! - **kotoba-tech / kotoba-whisper-v2.2** (Apache-2.0 / Apache-2.0) —
//!   [`vokra_models::kotoba_whisper::EXPECTED_ARCH`] = `"kotoba-whisper"`;
//!   architecturally identical to `-v2.0`, only distilled on a newer
//!   ReazonSpeech snapshot.
//!
//! # Gating (fabricated pass 禁止 — FR-EX-08)
//!
//! Every test is env-gated on `VOKRA_<ARCH>_GGUF` pointing at a
//! pre-converted GGUF (produced by `vokra-cli convert --model
//! {distil-whisper,kotoba-whisper-v2.2}` against a real HF snapshot at a
//! pinned revision — see the VAST runner under
//! `tools/parity/whisper_extras/run_vast_validation.sh`; the GitHub workflow
//! is deliberately model-free.
//! When the env var is unset, the test prints a clear skip reason and
//! returns — **never** a silent pass, **never** a synthesized substitute.
//!
//! `VOKRA_<ARCH>_REFDIR` is mandatory whenever a GGUF is supplied. It must be
//! an independent packet generated by
//! `tools/parity/whisper_extras/dump_reference.py` from the pinned Transformers
//! implementation. The test
//! compares the native CPU encoder, prefix logits, and greedy token sequence
//! against that packet; a missing or malformed packet is an error, never a
//! skip. The config-only constructors remain covered by model unit tests, but
//! are not a success condition for this real-weight harness.
//!
//! # What the test verifies today (real CPU parity)
//!
//! 1. `vokra.model.arch` string matches the expected canonical tag
//!    (distinct from vanilla Whisper's `"whisper"` — provenance / telemetry /
//!    model-card correctness), and authenticates the fixed source packet
//!    identity before running the native forward.
//! 2. Every `vokra.whisper.*` hparam the converter emits equals the
//!    primary-source config transcribed in the runtime module (a converter
//!    that started writing a different `n_text_layer` value than the runtime
//!    honors would silently break the distil axis — this test catches it).
//! 3. The distil invariant `n_text_layer < n_audio_layer` holds on both
//!    sides (converter output *and* the Rust config factory).
//! 4. At least one representative encoder + decoder tensor exists with the
//!    expected element count (byte-level sanity on the shape flow — a
//!    zero-tensor GGUF would still pass steps 1-3 but is caught here).
//! 5. Native CPU encoder states, decoder prefix logits, and greedy generated
//!    token ids match the independent reference within the fixed FP32 bound.
//!
//! # What the test explicitly does NOT do
//!
//! - It does not run model execution when either env var is absent. This is a
//!   deliberate gated skip for ordinary local/PR runs; the real run belongs on
//!   VAST and requires both paths.
//!
//! # Reference packet contract
//!
//! The packet is intentionally small: real PCM, the first 32 encoder rows,
//! last-position prefix logits, and the greedy suffix. Its manifest pins the
//! upstream repo/revision, reference library versions, input hash, shapes,
//! decode language/task/no-timestamps semantics, metadata-file hashes, and
//! hashes for every binary file. Kotoba v2.2 must use the exact Japanese
//! prefix `[50258, 50266, 50360, 50364]`; the older family aliases are not
//! silently reinterpreted.

#![allow(clippy::items_after_statements)]

use std::panic;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;

use vokra_core::gguf::GgufFile;
use vokra_core::gguf::chunks;
use vokra_models::whisper::WhisperModel;

const FP32_ATOL: f32 = 0.01;
const INPUT_AUDIO_SHA256: &str = "58adb4ea501d955fcd40bfbb69128f8f40428b81d8716b9ed337949773be253f";
const INPUT_PCM_SAMPLES: usize = 480_000;
const REFERENCE_SCHEMA: &str = "vokra-whisper-extras-reference-v1";
const KEY_PROVENANCE_UPSTREAM_HF: &str = "vokra.provenance.upstream_hf";
const KEY_PROVENANCE_UPSTREAM_REVISION: &str = "vokra.provenance.upstream_revision";

// ---------------------------------------------------------------------------
// Family manifest — kept close to the top so a future model landing in the
// whisper-extras family (e.g. a distil-medium.en, or an upcoming kotoba-
// whisper-v3) has one obvious place to register.
// ---------------------------------------------------------------------------

/// Canonical member of the `whisper-extras` parity family.
///
/// `arch_slug` doubles as the human name (`distil_whisper` / `kotoba_whisper`)
/// and the env-var infix (`VOKRA_DISTIL_WHISPER_GGUF` /
/// `VOKRA_KOTOBA_WHISPER_GGUF` — see [`gguf_env_var`] / [`refdir_env_var`]).
struct FamilyMember {
    /// Slug matching the module name (`distil_whisper` / `kotoba_whisper`).
    arch_slug: &'static str,
    /// The `vokra.model.arch` string the converter writes and the runtime
    /// module publishes as `EXPECTED_ARCH`.
    expected_arch: &'static str,
    /// The upstream HF repo id. The VAST runner and reference manifest pin the
    /// immutable revision; this label appears in skip messages so an owner
    /// reading a green PR knows which upstream slot is being probed.
    upstream_repo: &'static str,
    /// Immutable upstream snapshot revision required by the reference packet.
    upstream_revision: &'static str,
    /// SPDX identifier of the weight license (matches
    /// `vokra.provenance.weight_license` written by the converter).
    weight_license_spdx: &'static str,
    /// Language passed to the official reference pipeline.
    language: &'static str,
    /// Decode task passed to the official reference pipeline.
    task: &'static str,
    /// Whether the reference disables timestamps.
    no_timestamps: bool,
    /// Exact tokenizer-derived decoder prefix required by the GGUF.
    decoder_prefix: &'static [u32],
    checkpoint_bytes: usize,
    checkpoint_sha256: &'static str,
    config_bytes: usize,
    config_sha256: &'static str,
    generation_config_bytes: usize,
    generation_config_sha256: &'static str,
    tokenizer_bytes: usize,
    tokenizer_sha256: &'static str,
}

/// Every member of the whisper-extras parity family.
///
/// The order is stable so `[parity] whisper-extras: running …` step-summary
/// tables (added later) can rely on it.
const FAMILY: &[FamilyMember] = &[
    FamilyMember {
        arch_slug: "distil_whisper",
        expected_arch: "distil-whisper",
        upstream_repo: "distil-whisper/distil-large-v3.5",
        upstream_revision: "728a7691f3ff1d3d971528d3203a6e9559165d41",
        weight_license_spdx: "MIT",
        language: "en",
        task: "transcribe",
        no_timestamps: true,
        decoder_prefix: &[50_258, 50_259, 50_360, 50_364],
        checkpoint_bytes: 3_025_686_376,
        checkpoint_sha256: "76ec9f754fc4b4810845dc36b71d1897c1342e702810c179e1569690084cfb0c",
        config_bytes: 1_249,
        config_sha256: "515a10a9979258d3fc71cf79b2cd055c189f07d78879a15bd9bc282673308b85",
        generation_config_bytes: 4_249,
        generation_config_sha256: "b521c66612bd95be36c154f2d3904f6e4ea3be481a18a48f293d66791f60cf98",
        tokenizer_bytes: 2_480_645,
        tokenizer_sha256: "b3c8202bbf06d8ee4232c5984baa563784ac4737e2e7fdc42fa180200d3cfcdb",
    },
    FamilyMember {
        arch_slug: "kotoba_whisper",
        expected_arch: "kotoba-whisper",
        upstream_repo: "kotoba-tech/kotoba-whisper-v2.2",
        upstream_revision: "9d33482a0eb9b57f1ad80708e8ac5538246d8355",
        weight_license_spdx: "Apache-2.0",
        language: "ja",
        task: "transcribe",
        no_timestamps: true,
        decoder_prefix: &[50_258, 50_266, 50_360, 50_364],
        checkpoint_bytes: 3_025_686_376,
        checkpoint_sha256: "e0ef3e7b379515f0c35d0e7885638ddef0fa9f5c8e3e3f88cbc6da9b39edd1e9",
        config_bytes: 1_499,
        config_sha256: "75e0166afbf44308af4908793fc5ade1707890ed15760f0529b468dcfc378aec",
        generation_config_bytes: 3_898,
        generation_config_sha256: "20d28b9169207ab6ca402ec9342393a88ec3f341d88c9da24e516e1da71c24de",
        tokenizer_bytes: 3_931_381,
        tokenizer_sha256: "615928f5a25409279b47b47d87a4ca2aaee3bd09f65e1a3df6c9d23c718cfdb0",
    },
];

// ---------------------------------------------------------------------------
// Env plumbing (task contract: env_paths_for + skip_reason helpers).
// ---------------------------------------------------------------------------

/// Env-var name for a member's converted GGUF
/// (`distil_whisper` → `VOKRA_DISTIL_WHISPER_GGUF`).
fn gguf_env_var(arch: &str) -> String {
    format!("VOKRA_{}_GGUF", arch.to_ascii_uppercase())
}

/// Env-var name for a member's optional reference-dump directory
/// (`distil_whisper` → `VOKRA_DISTIL_WHISPER_REFDIR`).
fn refdir_env_var(arch: &str) -> String {
    format!("VOKRA_{}_REFDIR", arch.to_ascii_uppercase())
}

/// Returns `(gguf_path, refdir)` for `arch`, each `None` when the
/// corresponding env var is unset. This is the task-contracted helper —
/// the tests call it once and branch on the tuple.
fn env_paths_for(arch: &str) -> (Option<PathBuf>, Option<PathBuf>) {
    let gguf = std::env::var_os(gguf_env_var(arch)).map(PathBuf::from);
    let refdir = std::env::var_os(refdir_env_var(arch)).map(PathBuf::from);
    (gguf, refdir)
}

/// Human-readable skip annotation printed to stderr (visible with
/// `--nocapture` and in CI logs) when the required env var is absent. Names
/// the env var and the upstream repo so an owner reading a green run
/// immediately knows which slot to populate to flip the switch.
fn skip_reason(arch: &str, upstream_repo: &str) -> String {
    format!(
        "[parity_whisper_extras/{arch}] SKIP: set {env} to a converted GGUF \
         (vokra-cli convert --model {kebab} --input <hf snapshot>) to run this leg. \
         Upstream: {upstream_repo}. This is a clean gated skip, not a pass \
         (fabricated pass 禁止 — FR-EX-08).",
        env = gguf_env_var(arch),
        // The CLI flag uses the kebab-case model tag from vokra-cli/src/convert.rs:
        // "distil-whisper" / "kotoba-whisper" (never underscored).
        kebab = arch.replace('_', "-"),
    )
}

// ---------------------------------------------------------------------------
// GGUF invariant helpers (shared between the two per-model tests).
// ---------------------------------------------------------------------------

/// One `vokra.whisper.*` hparam pair (key + expected `u32` value) the
/// converter writes deterministically from the checkpoint shapes.
struct HparamExpectation {
    key: &'static str,
    expected: u32,
    human_name: &'static str,
}

/// Reads a `u32`-valued metadata entry, panicking loudly (with the key name)
/// if it is missing or of the wrong type. Loud panics here are the whole
/// point: a converter that started writing `n_text_layer` as `I32` instead
/// of `U32` would silently break the runtime, so we refuse to guess.
fn expect_u32(gguf: &GgufFile, key: &str) -> u32 {
    let raw = gguf
        .get(key)
        .unwrap_or_else(|| panic!("GGUF is missing required metadata key `{key}`"));
    let widened = raw.as_u64().unwrap_or_else(|| {
        panic!(
            "GGUF metadata key `{key}` is not an unsigned int (got {:?})",
            raw.value_type()
        )
    });
    u32::try_from(widened)
        .unwrap_or_else(|_| panic!("GGUF metadata key `{key}` = {widened} does not fit into u32"))
}

/// Reads a `String`-valued metadata entry, panicking with the key name on
/// absence or wrong type.
fn expect_string<'a>(gguf: &'a GgufFile, key: &str) -> &'a str {
    let raw = gguf
        .get(key)
        .unwrap_or_else(|| panic!("GGUF is missing required metadata key `{key}`"));
    raw.as_str().unwrap_or_else(|| {
        panic!(
            "GGUF metadata key `{key}` is not a String (got {:?})",
            raw.value_type()
        )
    })
}

/// Verifies each hparam pair. On mismatch, panics with a message that names
/// the human-readable axis, the observed value, and the expected value.
fn verify_hparams(gguf: &GgufFile, pairs: &[HparamExpectation]) {
    for h in pairs {
        let got = expect_u32(gguf, h.key);
        assert_eq!(
            got, h.expected,
            "GGUF `{}` ({}) = {got}, expected {} — a converter that emits a \
             different value than the runtime module transcribes silently breaks \
             the distil axis; refusing to compare",
            h.key, h.human_name, h.expected,
        );
    }
}

/// Confirms a tensor exists at `name` and its element count equals the
/// expected product. Dtype is intentionally not pinned (F16 / F32 / BF16
/// pass-through are all valid per the converter's rules; the runtime binds
/// through the same dequant path regardless).
fn expect_tensor_elements(gguf: &GgufFile, name: &str, expected_elements: u64) {
    let info = gguf.tensor_info(name).unwrap_or_else(|| {
        panic!(
            "GGUF is missing required tensor `{name}` (a zero-tensor / \
             metadata-only GGUF would still pass metadata sanity but fail here)"
        )
    });
    let got = info
        .element_count()
        .unwrap_or_else(|e| panic!("tensor `{name}`: element_count overflow: {e:?}"));
    assert_eq!(
        got, expected_elements,
        "tensor `{name}` element_count = {got}, expected {expected_elements} \
         (dims stored innermost-first: {:?})",
        info.dimensions,
    );
}

fn read_f32(path: &Path) -> Vec<f32> {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert!(
        bytes.len().is_multiple_of(4),
        "{path:?}: truncated f32 packet"
    );
    bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes(b.try_into().expect("f32 bytes")))
        .collect()
}

fn read_u32(path: &Path) -> Vec<u32> {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    assert!(
        bytes.len().is_multiple_of(4),
        "{path:?}: truncated u32 packet"
    );
    bytes
        .chunks_exact(4)
        .map(|b| u32::from_le_bytes(b.try_into().expect("u32 bytes")))
        .collect()
}

fn manifest_usize(root: &vokra_core::json::JsonValue, key: &str) -> usize {
    root.get(key)
        .and_then(vokra_core::json::JsonValue::as_u64)
        .and_then(|n| usize::try_from(n).ok())
        .unwrap_or_else(|| panic!("reference manifest `{key}` must be a usize"))
}

fn manifest_u32s(root: &vokra_core::json::JsonValue, key: &str) -> Vec<u32> {
    root.get(key)
        .and_then(vokra_core::json::JsonValue::as_array)
        .unwrap_or_else(|| panic!("reference manifest `{key}` must be an array"))
        .iter()
        .map(|v| {
            v.as_u64()
                .and_then(|n| u32::try_from(n).ok())
                .unwrap_or_else(|| panic!("reference manifest `{key}` contains a non-u32"))
        })
        .collect()
}

fn manifest_string<'a>(root: &'a vokra_core::json::JsonValue, key: &str) -> &'a str {
    root.get(key)
        .and_then(vokra_core::json::JsonValue::as_str)
        .unwrap_or_else(|| panic!("reference manifest `{key}` must be a string"))
}

fn manifest_f32(root: &vokra_core::json::JsonValue, key: &str) -> f32 {
    match root.get(key) {
        Some(vokra_core::json::JsonValue::Float(value)) => *value as f32,
        Some(vokra_core::json::JsonValue::Int(value)) => *value as f32,
        _ => panic!("reference manifest `{key}` must be a number"),
    }
}

fn manifest_bool(root: &vokra_core::json::JsonValue, key: &str) -> bool {
    match root.get(key) {
        Some(vokra_core::json::JsonValue::Bool(value)) => *value,
        _ => panic!("reference manifest `{key}` must be a boolean"),
    }
}

fn assert_manifest_sha256(root: &vokra_core::json::JsonValue, key: &str) {
    let value = manifest_string(root, key);
    assert_eq!(
        value.len(),
        64,
        "reference manifest `{key}` must be SHA-256"
    );
    assert!(
        value.bytes().all(|byte| byte.is_ascii_hexdigit()),
        "reference manifest `{key}` must contain hexadecimal SHA-256"
    );
}

fn sha256_file(path: &Path) -> String {
    for program in ["sha256sum", "shasum"] {
        let output = if program == "shasum" {
            Command::new(program).args(["-a", "256"]).arg(path).output()
        } else {
            Command::new(program).arg(path).output()
        };
        if let Ok(output) = output {
            if output.status.success() {
                if let Some(hash) = String::from_utf8_lossy(&output.stdout)
                    .split_whitespace()
                    .next()
                {
                    if hash.len() == 64 && hash.bytes().all(|b| b.is_ascii_hexdigit()) {
                        return hash.to_owned();
                    }
                }
            }
        }
    }
    panic!("no usable sha256 utility available for reference packet {path:?}");
}

/// Require the complete independent packet before any model forward. A
/// partially copied directory is a hard error, never a clean parity skip.
fn parse_reference_packet(member: &FamilyMember, refdir: &Path) -> vokra_core::json::JsonValue {
    assert!(
        refdir.is_dir(),
        "VOKRA_{}_REFDIR = {refdir:?} does not exist or is not a directory",
        member.arch_slug.to_ascii_uppercase(),
    );
    let path = refdir.join("manifest.json");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    let root = vokra_core::json::parse(&bytes).unwrap_or_else(|e| panic!("parse {path:?}: {e}"));
    assert_eq!(manifest_string(&root, "schema"), REFERENCE_SCHEMA);
    assert_eq!(manifest_string(&root, "model"), member.arch_slug);
    assert_eq!(
        manifest_string(&root, "upstream_repo"),
        member.upstream_repo
    );
    assert_eq!(
        manifest_string(&root, "upstream_revision"),
        member.upstream_revision,
        "reference packet upstream revision drift"
    );
    assert_eq!(
        manifest_string(&root, "weight_license_spdx"),
        member.weight_license_spdx
    );
    assert_eq!(
        manifest_string(&root, "reference_implementation"),
        "transformers.WhisperForConditionalGeneration",
        "reference must come from the independent Transformers implementation"
    );
    assert_eq!(
        manifest_usize(&root, "checkpoint_bytes"),
        member.checkpoint_bytes,
        "checkpoint byte identity drift"
    );
    assert_eq!(
        manifest_string(&root, "checkpoint_sha256"),
        member.checkpoint_sha256,
        "checkpoint SHA-256 identity drift"
    );
    assert_eq!(
        manifest_usize(&root, "config_bytes"),
        member.config_bytes,
        "config byte identity drift"
    );
    assert_eq!(
        manifest_string(&root, "config_sha256"),
        member.config_sha256,
        "config SHA-256 identity drift"
    );
    assert_eq!(
        manifest_usize(&root, "generation_config_bytes"),
        member.generation_config_bytes,
        "generation_config byte identity drift"
    );
    assert_eq!(
        manifest_string(&root, "generation_config_sha256"),
        member.generation_config_sha256,
        "generation_config SHA-256 identity drift"
    );
    assert_eq!(
        manifest_usize(&root, "tokenizer_bytes"),
        member.tokenizer_bytes,
        "tokenizer byte identity drift"
    );
    assert_eq!(
        manifest_string(&root, "tokenizer_sha256"),
        member.tokenizer_sha256,
        "tokenizer SHA-256 identity drift"
    );
    for name in [
        "input_pcm.f32le",
        "encoder.f32le",
        "logits_last.f32le",
        "greedy_tokens.u32le",
    ] {
        let file = refdir.join(name);
        assert!(file.is_file(), "reference packet missing {file:?}");
        let expected = root
            .get("files")
            .and_then(vokra_core::json::JsonValue::as_object)
            .and_then(|entries| entries.iter().find(|(key, _)| key == name))
            .and_then(|(_, value)| value.as_str())
            .unwrap_or_else(|| panic!("reference manifest missing files.{name}"));
        assert_eq!(
            sha256_file(&file),
            expected,
            "reference packet hash drift: {name}"
        );
    }
    assert_eq!(manifest_usize(&root, "sample_rate"), 16_000);
    assert_eq!(
        manifest_string(&root, "audio_sha256"),
        INPUT_AUDIO_SHA256,
        "reference audio SHA-256 must match the fixed parity input"
    );
    assert_eq!(
        manifest_usize(&root, "pcm_samples"),
        INPUT_PCM_SAMPLES,
        "reference audio must be exactly 30 seconds at 16 kHz"
    );
    assert_eq!(
        manifest_f32(&root, "atol"),
        FP32_ATOL,
        "FP32_ATOL=0.01 is the preregistered existing Whisper-family bound, not a new measured result"
    );
    assert_manifest_sha256(&root, "generation_config_sha256");
    assert_manifest_sha256(&root, "tokenizer_sha256");
    let pcm = read_f32(&refdir.join("input_pcm.f32le"));
    let encoder = read_f32(&refdir.join("encoder.f32le"));
    let logits = read_f32(&refdir.join("logits_last.f32le"));
    let tokens = read_u32(&refdir.join("greedy_tokens.u32le"));
    assert_eq!(manifest_usize(&root, "pcm_samples"), pcm.len());
    assert!(
        manifest_usize(&root, "pcm_samples") > 0,
        "reference PCM is empty"
    );
    assert!(
        pcm.iter().all(|value| value.is_finite()),
        "reference PCM is non-finite"
    );

    let rows = manifest_usize(&root, "encoder_rows");
    let d_model = manifest_usize(&root, "d_model");
    let encoder_len = rows
        .checked_mul(d_model)
        .unwrap_or_else(|| panic!("reference encoder_rows*d_model overflows usize"));
    assert!(rows > 0, "reference encoder_rows must be non-zero");
    assert!(d_model > 0, "reference d_model must be non-zero");
    assert_eq!(
        encoder.len(),
        encoder_len,
        "reference encoder byte length drift"
    );
    assert!(
        encoder.iter().all(|value| value.is_finite()),
        "reference encoder contains non-finite values"
    );

    let vocab = manifest_usize(&root, "vocab");
    assert!(vocab > 0, "reference vocab must be non-zero");
    assert_eq!(logits.len(), vocab, "reference logits byte length drift");
    assert!(
        logits.iter().all(|value| value.is_finite()),
        "reference logits contain non-finite values"
    );

    let manifest_prefix = manifest_u32s(&root, "decoder_prefix");
    assert!(
        !manifest_prefix.is_empty(),
        "reference decoder prefix is empty"
    );
    let manifest_tokens = manifest_u32s(&root, "greedy_tokens");
    assert!(
        !manifest_tokens.is_empty(),
        "reference greedy token sequence is empty"
    );
    assert_eq!(
        tokens, manifest_tokens,
        "greedy token binary disagrees with manifest"
    );
    let eot = manifest_usize(&root, "eot");
    assert!(eot <= u32::MAX as usize, "reference eot does not fit u32");
    assert!(eot < vocab, "reference eot is outside manifest vocabulary");
    assert!(
        manifest_prefix
            .iter()
            .all(|&token| token as usize < vocab),
        "reference decoder prefix contains a token outside manifest vocabulary"
    );
    assert_eq!(
        manifest_string(&root, "language"),
        member.language,
        "reference language semantics drift"
    );
    assert_eq!(
        manifest_string(&root, "task"),
        member.task,
        "reference task semantics drift"
    );
    assert_eq!(
        manifest_bool(&root, "no_timestamps"),
        member.no_timestamps,
        "reference timestamp semantics drift"
    );
    assert_eq!(
        manifest_prefix, member.decoder_prefix,
        "reference decoder prefix must match the authenticated model contract"
    );
    assert!(
        manifest_tokens.iter().any(|&token| token as usize == eot),
        "reference greedy sequence never emits manifest eot"
    );
    assert!(
        manifest_tokens
            .iter()
            .all(|&token| token as usize < vocab),
        "reference greedy sequence contains a token outside manifest vocabulary"
    );
    assert!(
        manifest_tokens.len() <= 224,
        "reference greedy sequence exceeds MAX_NEW_TOKENS=224"
    );
    for (name, item_size, item_count) in [
        ("input_pcm.f32le", 4usize, pcm.len()),
        ("encoder.f32le", 4usize, encoder.len()),
        ("logits_last.f32le", 4usize, logits.len()),
        ("greedy_tokens.u32le", 4usize, tokens.len()),
    ] {
        let expected_bytes = item_count
            .checked_mul(item_size)
            .unwrap_or_else(|| panic!("reference {name} byte length overflows usize"));
        assert_eq!(
            std::fs::metadata(refdir.join(name))
                .unwrap_or_else(|e| panic!("stat reference {name}: {e}"))
                .len(),
            expected_bytes as u64,
            "reference {name} byte length drift"
        );
    }
    root
}

fn assert_close(actual: &[f32], expected: &[f32], label: &str) {
    assert_eq!(actual.len(), expected.len(), "{label}: length mismatch");
    assert!(
        actual.iter().all(|value| value.is_finite())
            && expected.iter().all(|value| value.is_finite()),
        "{label}: non-finite value"
    );
    let (index, max_abs) = actual
        .iter()
        .zip(expected)
        .enumerate()
        .map(|(i, (a, b))| (i, (a - b).abs()))
        .max_by(|a, b| a.1.total_cmp(&b.1))
        .expect("non-empty reference vector");
    eprintln!(
        "[parity_whisper_extras] {label}: max |Δ|={max_abs:.9e} at {index}, atol={FP32_ATOL:.3e}"
    );
    assert!(
        max_abs <= FP32_ATOL,
        "{label}: max |Δ|={max_abs:.9e} at {index} exceeds {FP32_ATOL}"
    );
}

fn run_real_cpu_parity(member: &FamilyMember, file: &GgufFile, refdir: &Path) {
    let root = parse_reference_packet(member, refdir);
    let pcm = read_f32(&refdir.join("input_pcm.f32le"));
    let encoder_reference = read_f32(&refdir.join("encoder.f32le"));
    let logits_reference = read_f32(&refdir.join("logits_last.f32le"));
    let token_reference = read_u32(&refdir.join("greedy_tokens.u32le"));
    let model = Arc::new(WhisperModel::from_gguf(file).expect("bind real Whisper weights"));
    let encoder = model.encode_pcm(&pcm).expect("native CPU encoder");
    let rows = manifest_usize(&root, "encoder_rows");
    let width = model.config().d_model;
    assert_eq!(width, manifest_usize(&root, "d_model"));
    assert!(
        rows <= model.config().n_audio_ctx,
        "reference encoder_rows={rows} exceeds model encoder context {}",
        model.config().n_audio_ctx
    );
    assert_eq!(
        model.config().n_vocab,
        manifest_usize(&root, "vocab"),
        "model config vocab disagrees with reference manifest"
    );
    assert_eq!(
        model.config().eot as usize,
        manifest_usize(&root, "eot"),
        "model config eot disagrees with reference manifest"
    );
    let native_len = rows
        .checked_mul(width)
        .unwrap_or_else(|| panic!("native encoder rows*d_model overflows usize"));
    assert!(
        encoder.hidden.len() >= native_len,
        "native encoder output is shorter than reference row bound"
    );
    assert_close(
        &encoder.hidden[..native_len],
        &encoder_reference,
        "encoder hidden",
    );

    let prefix = manifest_u32s(&root, "decoder_prefix");
    assert!(!prefix.is_empty(), "reference decoder prefix is empty");
    assert_eq!(
        model.config().decoder_start_ids,
        prefix,
        "decoder prefix drift"
    );
    assert_eq!(
        model.config().decoder_start_ids.as_slice(),
        member.decoder_prefix,
        "native decoder prefix is not the authenticated model contract"
    );
    let mut decoder = model.decoder(&encoder).expect("native CPU decoder");
    let logits = decoder.step(&prefix).expect("native CPU prefix logits");
    let vocab = model.config().n_vocab;
    assert_eq!(
        logits.len(),
        prefix.len() * vocab,
        "native prefix logits shape drift"
    );
    let last = &logits[(prefix.len() - 1) * vocab..];
    assert_close(last, &logits_reference, "decoder prefix last logits");

    match member.arch_slug {
        "distil_whisper" => {
            let asr = vokra_models::distil_whisper::DistilWhisperAsr::from_gguf(file)
                .expect("bind distil-whisper real weights");
            assert_eq!(
                asr.transcribe(&pcm).expect("native distil transcription"),
                token_reference
            );
        }
        "kotoba_whisper" => {
            let asr = vokra_models::kotoba_whisper::KotobaWhisperAsr::from_gguf(file)
                .expect("bind kotoba-whisper real weights");
            assert_eq!(
                asr.transcribe(&pcm).expect("native kotoba transcription"),
                token_reference
            );
        }
        other => panic!("unregistered whisper-extras member {other}"),
    }
}

// ---------------------------------------------------------------------------
// distil_whisper
// ---------------------------------------------------------------------------

/// distil-whisper real CPU parity. Skips only when neither input is supplied.
#[test]
fn parity_whisper_extras_distil_whisper() {
    let member = FAMILY
        .iter()
        .find(|m| m.arch_slug == "distil_whisper")
        .expect("family entry present");
    let (gguf_path, refdir) = env_paths_for(member.arch_slug);
    let Some(gguf_path) = gguf_path else {
        assert!(
            refdir.is_none(),
            "reference packet requires a matching GGUF"
        );
        eprintln!("{}", skip_reason(member.arch_slug, member.upstream_repo));
        return;
    };
    let refdir = refdir.expect("VOKRA_DISTIL_WHISPER_REFDIR is required with the GGUF");

    // Primary-source config transcribed in the runtime module (each field
    // was fetched from HF and pinned in Rust — see
    // `distil_whisper::DistilWhisperConfig::distil_large_v3_5`).
    let cfg = vokra_models::distil_whisper::DistilWhisperConfig::distil_large_v3_5();
    cfg.validate_for_forward()
        .expect("primary-source distil-large-v3.5 config must be well-formed");
    assert!(
        cfg.n_text_layer < cfg.n_audio_layer,
        "distil invariant must hold on the Rust config side too \
         (n_text_layer={} vs n_audio_layer={})",
        cfg.n_text_layer,
        cfg.n_audio_layer,
    );

    // GGUF load + arch stamp.
    let file = GgufFile::open(&gguf_path)
        .unwrap_or_else(|e| panic!("open {}: {e:?}", gguf_path.display()));
    let arch = expect_string(&file, chunks::KEY_MODEL_ARCH);
    assert_eq!(
        arch,
        member.expected_arch,
        "GGUF `{}` = {arch:?}, expected {:?} — distil-whisper GGUFs must \
         carry the `distil-whisper` arch tag (distinct from vanilla \
         Whisper's `whisper` and from kotoba-whisper's `kotoba-whisper`) \
         so runtime telemetry / logs / model cards label the model correctly",
        chunks::KEY_MODEL_ARCH,
        member.expected_arch,
    );

    // Every `vokra.whisper.*` axis the converter emits.
    let pairs = [
        HparamExpectation {
            key: "vokra.whisper.n_mels",
            expected: cfg.n_mels as u32,
            human_name: "n_mels",
        },
        HparamExpectation {
            key: "vokra.whisper.n_audio_ctx",
            expected: cfg.n_audio_ctx as u32,
            human_name: "n_audio_ctx",
        },
        HparamExpectation {
            key: "vokra.whisper.n_audio_state",
            expected: cfg.d_model as u32,
            human_name: "n_audio_state (= d_model)",
        },
        HparamExpectation {
            key: "vokra.whisper.n_audio_head",
            expected: cfg.n_audio_head as u32,
            human_name: "n_audio_head",
        },
        HparamExpectation {
            key: "vokra.whisper.n_audio_layer",
            expected: cfg.n_audio_layer as u32,
            human_name: "n_audio_layer",
        },
        HparamExpectation {
            key: "vokra.whisper.n_text_ctx",
            expected: cfg.n_text_ctx as u32,
            human_name: "n_text_ctx",
        },
        HparamExpectation {
            key: "vokra.whisper.n_text_state",
            expected: cfg.d_model as u32,
            human_name: "n_text_state (= d_model)",
        },
        HparamExpectation {
            key: "vokra.whisper.n_text_head",
            expected: cfg.n_text_head as u32,
            human_name: "n_text_head",
        },
        HparamExpectation {
            key: "vokra.whisper.n_text_layer",
            expected: cfg.n_text_layer as u32,
            human_name: "n_text_layer (the distil axis)",
        },
        HparamExpectation {
            key: "vokra.whisper.n_vocab",
            expected: cfg.n_vocab as u32,
            human_name: "n_vocab",
        },
        HparamExpectation {
            key: "vokra.whisper.ffn_dim",
            expected: cfg.ffn_dim as u32,
            human_name: "ffn_dim",
        },
        HparamExpectation {
            key: "vokra.whisper.eot",
            expected: cfg.eot,
            human_name: "eot",
        },
    ];
    verify_hparams(&file, &pairs);

    // Distil invariant on the GGUF side too — a converter-side regression
    // that swapped n_text_layer and n_audio_layer would break every
    // downstream binding (KV cache, decoder loop, greedy).
    let gguf_n_audio_layer = expect_u32(&file, "vokra.whisper.n_audio_layer");
    let gguf_n_text_layer = expect_u32(&file, "vokra.whisper.n_text_layer");
    assert!(
        gguf_n_text_layer < gguf_n_audio_layer,
        "GGUF distil invariant violated: n_text_layer={gguf_n_text_layer} \
         must be < n_audio_layer={gguf_n_audio_layer}",
    );

    // Provenance stamp: the raw SPDX literal must round-trip exactly.
    // A converter that started writing `mit` (lower) vs `MIT` (upper) would
    // silently break license-audit tooling that pattern-matches on the exact
    // SPDX literal.
    //
    // KEY note (harness bug fixed 2026-07-25): the SPDX literal lives on
    // `KEY_PROVENANCE_LICENSE` (raw string, "MIT"). The sibling key
    // `KEY_PROVENANCE_WEIGHT_LICENSE` holds the resolved *canonical class
    // name* (e.g. "permissive"), which is intentionally NOT the SPDX literal
    // — see `crates/vokra-core/src/gguf/chunks.rs::KEY_PROVENANCE_*` and the
    // `LicenseClass::as_str()` contract. Previously this test hit the
    // canonical-class key by mistake and failed on real distil GGUFs where
    // the converter correctly wrote "permissive" (dispatch run 30116427518
    // step 14).
    let license = expect_string(&file, chunks::KEY_PROVENANCE_LICENSE);
    assert_eq!(
        license,
        member.weight_license_spdx,
        "GGUF `{}` = {license:?}, expected {:?} (distil-whisper is MIT — see \
         module docstring `# Weight license`)",
        chunks::KEY_PROVENANCE_LICENSE,
        member.weight_license_spdx,
    );
    // Representative tensor sanity — encoder block 0 Q-projection weight
    // and decoder block 0 Q-projection weight. Element counts (both = d²)
    // catch a "zero-tensor GGUF" that would otherwise clear every metadata
    // check. Layer-0 is chosen because it exists in every distil / kotoba
    // variant (n_audio_layer >= 1, n_text_layer >= 1 is enforced by the
    // config validator).
    let d = cfg.d_model as u64;
    expect_tensor_elements(
        &file,
        "model.encoder.layers.0.self_attn.q_proj.weight",
        d * d,
    );
    expect_tensor_elements(
        &file,
        "model.decoder.layers.0.self_attn.q_proj.weight",
        d * d,
    );

    run_real_cpu_parity(member, &file, &refdir);
    eprintln!(
        "[parity_whisper_extras/{}] native CPU real-weight parity PASS",
        member.arch_slug
    );
    let _ = gguf_path; // moved into `open`; retained for a clearer test-scope trace.
}

// ---------------------------------------------------------------------------
// kotoba_whisper
// ---------------------------------------------------------------------------

/// kotoba-whisper real CPU parity. Skips only when neither input is supplied.
///
/// The task pins `kotoba-tech/kotoba-whisper-v2.2`, whose architectural
/// quintuple is identical to `-v2.0` (both distilled from Whisper large-v3
/// with a 2-layer decoder). The runtime module factory
/// `KotobaWhisperConfig::kotoba_whisper_v2_0` is therefore the correct
/// ground truth for v2.2 as well (config values verified against
/// `huggingface.co/kotoba-tech/kotoba-whisper-v2.2/raw/main/config.json`,
/// fetched 2026-07-25).
#[test]
fn parity_whisper_extras_kotoba_whisper() {
    let member = FAMILY
        .iter()
        .find(|m| m.arch_slug == "kotoba_whisper")
        .expect("family entry present");
    let (gguf_path, refdir) = env_paths_for(member.arch_slug);
    let Some(gguf_path) = gguf_path else {
        assert!(
            refdir.is_none(),
            "reference packet requires a matching GGUF"
        );
        eprintln!("{}", skip_reason(member.arch_slug, member.upstream_repo));
        return;
    };
    let refdir = refdir.expect("VOKRA_KOTOBA_WHISPER_REFDIR is required with the GGUF");

    let cfg = vokra_models::kotoba_whisper::KotobaWhisperConfig::kotoba_whisper_v2_0();
    cfg.validate_for_forward()
        .expect("primary-source kotoba-whisper v2.x config must be well-formed");
    assert!(
        cfg.n_text_layer < cfg.n_audio_layer,
        "distil invariant must hold on the Rust config side too \
         (n_text_layer={} vs n_audio_layer={})",
        cfg.n_text_layer,
        cfg.n_audio_layer,
    );

    let file = GgufFile::open(&gguf_path)
        .unwrap_or_else(|e| panic!("open {}: {e:?}", gguf_path.display()));

    let arch = expect_string(&file, chunks::KEY_MODEL_ARCH);
    assert_eq!(
        arch,
        member.expected_arch,
        "GGUF `{}` = {arch:?}, expected {:?} — kotoba-whisper GGUFs must \
         carry the `kotoba-whisper` arch tag (distinct from vanilla \
         Whisper's `whisper` and from distil-whisper's `distil-whisper`) \
         so runtime telemetry / logs / model cards label the model correctly",
        chunks::KEY_MODEL_ARCH,
        member.expected_arch,
    );

    let pairs = [
        HparamExpectation {
            key: "vokra.whisper.n_mels",
            expected: cfg.n_mels as u32,
            human_name: "n_mels",
        },
        HparamExpectation {
            key: "vokra.whisper.n_audio_ctx",
            expected: cfg.n_audio_ctx as u32,
            human_name: "n_audio_ctx",
        },
        HparamExpectation {
            key: "vokra.whisper.n_audio_state",
            expected: cfg.d_model as u32,
            human_name: "n_audio_state (= d_model)",
        },
        HparamExpectation {
            key: "vokra.whisper.n_audio_head",
            expected: cfg.n_audio_head as u32,
            human_name: "n_audio_head",
        },
        HparamExpectation {
            key: "vokra.whisper.n_audio_layer",
            expected: cfg.n_audio_layer as u32,
            human_name: "n_audio_layer",
        },
        HparamExpectation {
            key: "vokra.whisper.n_text_ctx",
            expected: cfg.n_text_ctx as u32,
            human_name: "n_text_ctx",
        },
        HparamExpectation {
            key: "vokra.whisper.n_text_state",
            expected: cfg.d_model as u32,
            human_name: "n_text_state (= d_model)",
        },
        HparamExpectation {
            key: "vokra.whisper.n_text_head",
            expected: cfg.n_text_head as u32,
            human_name: "n_text_head",
        },
        HparamExpectation {
            key: "vokra.whisper.n_text_layer",
            expected: cfg.n_text_layer as u32,
            human_name: "n_text_layer (JA-ASR-2 axis)",
        },
        HparamExpectation {
            key: "vokra.whisper.n_vocab",
            expected: cfg.n_vocab as u32,
            human_name: "n_vocab",
        },
        HparamExpectation {
            key: "vokra.whisper.ffn_dim",
            expected: cfg.ffn_dim as u32,
            human_name: "ffn_dim",
        },
        HparamExpectation {
            key: "vokra.whisper.eot",
            expected: cfg.eot,
            human_name: "eot",
        },
    ];
    verify_hparams(&file, &pairs);

    let gguf_n_audio_layer = expect_u32(&file, "vokra.whisper.n_audio_layer");
    let gguf_n_text_layer = expect_u32(&file, "vokra.whisper.n_text_layer");
    assert!(
        gguf_n_text_layer < gguf_n_audio_layer,
        "GGUF distil invariant violated: n_text_layer={gguf_n_text_layer} \
         must be < n_audio_layer={gguf_n_audio_layer}",
    );

    // KEY note: raw SPDX literal lives on `KEY_PROVENANCE_LICENSE`; the
    // sibling `KEY_PROVENANCE_WEIGHT_LICENSE` holds the resolved canonical
    // class name (e.g. "permissive") — see the same-file distil block above
    // for full rationale.
    let license = expect_string(&file, chunks::KEY_PROVENANCE_LICENSE);
    assert_eq!(
        license,
        member.weight_license_spdx,
        "GGUF `{}` = {license:?}, expected {:?} (kotoba-whisper is \
         Apache-2.0 — see module docstring `# Weight license`)",
        chunks::KEY_PROVENANCE_LICENSE,
        member.weight_license_spdx,
    );
    let source = expect_string(&file, chunks::KEY_PROVENANCE_SOURCE);
    assert_eq!(
        expect_string(&file, chunks::KEY_MODEL_NAME),
        "kotoba-whisper-v2.2",
        "Kotoba parity requires the explicit v2.2 converter selector"
    );
    assert_eq!(
        expect_string(&file, KEY_PROVENANCE_UPSTREAM_HF),
        member.upstream_repo,
        "GGUF upstream HF repo drift"
    );
    assert_eq!(
        expect_string(&file, KEY_PROVENANCE_UPSTREAM_REVISION),
        member.upstream_revision,
        "GGUF upstream revision drift"
    );
    assert!(
        source.contains(member.upstream_repo) && source.contains(member.upstream_revision),
        "GGUF provenance source cannot authenticate the pinned {} revision: {source:?}",
        member.upstream_repo,
    );

    let d = cfg.d_model as u64;
    expect_tensor_elements(
        &file,
        "model.encoder.layers.0.self_attn.q_proj.weight",
        d * d,
    );
    expect_tensor_elements(
        &file,
        "model.decoder.layers.0.self_attn.q_proj.weight",
        d * d,
    );

    run_real_cpu_parity(member, &file, &refdir);
    eprintln!(
        "[parity_whisper_extras/{}] native CPU real-weight parity PASS",
        member.arch_slug
    );
    let _ = gguf_path;
}

// ---------------------------------------------------------------------------
// Family invariants (fixture-free — always runs, catches manifest drift).
// ---------------------------------------------------------------------------

/// Family manifest smoke: the two arch slugs remain distinct, both from
/// each other and from vanilla Whisper's `"whisper"`. Drift here would mean
/// two different upstream models landing under the same `vokra.model.arch`
/// tag, silently breaking provenance / license attribution.
#[test]
fn family_arch_slugs_are_distinct() {
    let mut slugs: Vec<&'static str> = FAMILY.iter().map(|m| m.expected_arch).collect();
    slugs.sort_unstable();
    let mut deduped = slugs.clone();
    deduped.dedup();
    assert_eq!(
        slugs, deduped,
        "expected_arch tags must be pairwise distinct within the family"
    );
    for m in FAMILY {
        assert_ne!(
            m.expected_arch, "whisper",
            "`{}` must not collide with vanilla Whisper's `whisper` arch tag",
            m.arch_slug,
        );
    }
}

/// Family manifest ↔ runtime module cross-check: each expected arch string
/// must equal the module's own `EXPECTED_ARCH` constant. A rename in one
/// place without the other would silently break provenance stamping.
#[test]
fn family_expected_arch_matches_runtime_modules() {
    let distil = FAMILY
        .iter()
        .find(|m| m.arch_slug == "distil_whisper")
        .expect("distil_whisper in family");
    assert_eq!(
        distil.expected_arch,
        vokra_models::distil_whisper::EXPECTED_ARCH,
        "distil_whisper family manifest disagrees with runtime EXPECTED_ARCH",
    );

    let kotoba = FAMILY
        .iter()
        .find(|m| m.arch_slug == "kotoba_whisper")
        .expect("kotoba_whisper in family");
    assert_eq!(
        kotoba.expected_arch,
        vokra_models::kotoba_whisper::EXPECTED_ARCH,
        "kotoba_whisper family manifest disagrees with runtime EXPECTED_ARCH",
    );
}

/// The env-var naming helper must produce the exact strings the workflow
/// YAML sets (`VOKRA_DISTIL_WHISPER_GGUF` / `VOKRA_KOTOBA_WHISPER_GGUF`
/// and the corresponding `_REFDIR` pair). Drift between this file and the
/// YAML would mean the CI sets an env var that no test reads.
#[test]
fn env_var_naming_matches_workflow() {
    assert_eq!(gguf_env_var("distil_whisper"), "VOKRA_DISTIL_WHISPER_GGUF");
    assert_eq!(gguf_env_var("kotoba_whisper"), "VOKRA_KOTOBA_WHISPER_GGUF");
    assert_eq!(
        refdir_env_var("distil_whisper"),
        "VOKRA_DISTIL_WHISPER_REFDIR"
    );
    assert_eq!(
        refdir_env_var("kotoba_whisper"),
        "VOKRA_KOTOBA_WHISPER_REFDIR"
    );
}

/// `skip_reason` includes the env var name and upstream repo — the two
/// pieces of information an owner needs to flip a green skip into a real
/// run.
#[test]
fn skip_reason_includes_env_var_and_upstream_repo() {
    for m in FAMILY {
        let msg = skip_reason(m.arch_slug, m.upstream_repo);
        assert!(
            msg.contains(&gguf_env_var(m.arch_slug)),
            "skip_reason must name the env var: {msg}",
        );
        assert!(
            msg.contains(m.upstream_repo),
            "skip_reason must name the upstream repo: {msg}",
        );
        // The kebab-case CLI flag must appear so an owner can copy-paste
        // the reproduction command.
        assert!(
            msg.contains(&m.arch_slug.replace('_', "-")),
            "skip_reason must name the kebab-case model tag: {msg}",
        );
    }
}

// ---------------------------------------------------------------------------
// Additional unit-only coverage (audit follow-up 2026-07-25) — every test
// below runs on every `cargo test`, needs no checkpoint, and pins a seam or
// contract that the two env-gated per-model tests only exercise transitively.
// ---------------------------------------------------------------------------

/// Downcast a panic payload to a `String` for substring assertions. Mirrors
/// the shape used in `parity_nemo_asr.rs` so callers can inspect the panic
/// message directly.
fn panic_payload_string(payload: &(dyn std::any::Any + Send)) -> String {
    if let Some(s) = payload.downcast_ref::<&'static str>() {
        (*s).to_owned()
    } else if let Some(s) = payload.downcast_ref::<String>() {
        s.clone()
    } else {
        "<non-string panic payload>".to_owned()
    }
}

/// Per-test unique tempfs entry under `env::temp_dir()`. `cargo test` runs
/// tests within one binary in parallel threads that share a PID, so the
/// caller must pass a distinct `tag` per test to avoid inter-test races.
fn temp_scratch(tag: &str) -> PathBuf {
    std::env::temp_dir().join(format!(
        "vokra_parity_whisper_extras_{}_{}",
        tag,
        std::process::id(),
    ))
}

/// Direct unit-test coverage of the environment gate. `env_paths_for`
/// (lines 150-154) IS the switch — the two env-gated per-model tests
/// exercise it only when an owner provisions fixtures, so on the CI baseline
/// (env vars unset) a regression that made this helper return
/// `(Some(PathBuf::new()), _)` on an unset env var would slip past the two
/// existing tests silently (both would still take the early-return skip
/// path, but for the wrong reason). Namespaced arch slug so no `VOKRA_*_GGUF`
/// / `_REFDIR` env var could plausibly collide.
///
/// The workspace forbids `unsafe` (`unsafe_code = "deny"` in workspace
/// `Cargo.toml`) and `std::env::set_var` is `unsafe` in Rust 2024, so the
/// Some-branch (env set, path visible) cannot be exercised directly without
/// breaking the workspace lint — see the equivalent note in
/// `parity_tts_dac.rs::env_paths_for_returns_none_when_unset`. The
/// Some-branch is transitively exercised by the two per-model tests as soon
/// as an owner provisions `VOKRA_<ARCH>_GGUF`.
#[test]
fn env_paths_for_returns_none_when_both_unset() {
    // A slug intentionally namespaced to this helper. `env_paths_for` will
    // read `VOKRA_WHISPER_EXTRAS_HARNESS_PROBE_ONLY_GGUF` /
    // `_REFDIR` — no CI job could plausibly set these.
    let arch = "whisper_extras_harness_probe_only";
    let (gguf, refdir) = env_paths_for(arch);
    assert!(
        gguf.is_none(),
        "expected {} unset in the test env, got Some({:?}) — env leakage \
         from another process, or a regression in env_paths_for that returns \
         Some on an unset env var (environment gate broken)",
        gguf_env_var(arch),
        gguf,
    );
    assert!(
        refdir.is_none(),
        "expected {} unset in the test env, got Some({:?}) — env leakage or \
         asymmetric handling of the refdir arm",
        refdir_env_var(arch),
        refdir,
    );
}

/// A supplied reference directory must be a real packet, not an absent path.
#[test]
fn reference_packet_panics_on_nonexistent_path() {
    let member = &FAMILY[0];
    let refdir = temp_scratch("nonexistent");
    // Ensure the path really does not exist. Both variants (in case a prior
    // interrupted run left something behind).
    let _ = std::fs::remove_dir_all(&refdir);
    let _ = std::fs::remove_file(&refdir);

    let refdir_captured = refdir.clone();
    let payload = panic::catch_unwind(move || {
        parse_reference_packet(member, &refdir_captured);
    })
    .expect_err("parse_reference_packet must panic on a nonexistent path");

    let msg = panic_payload_string(&*payload);
    assert!(
        msg.contains("does not exist or is not a directory"),
        "panic must name the failure mode; got: {msg}",
    );
    assert!(
        msg.contains("VOKRA_DISTIL_WHISPER_REFDIR"),
        "panic must name the specific env var (owner-actionable); got: {msg}",
    );
    assert!(
        msg.contains(&format!("{refdir:?}")),
        "panic must show the offending path so the owner can inspect it; got: {msg}",
    );
}

/// A supplied reference path that is a regular file must be rejected.
#[test]
fn reference_packet_panics_when_path_is_regular_file() {
    let member = &FAMILY[1];
    let path = temp_scratch("regular_file");
    // Ensure a clean slate then materialize a file at the path.
    let _ = std::fs::remove_dir_all(&path);
    let _ = std::fs::remove_file(&path);
    std::fs::write(&path, b"not a directory").expect("write temp file for refdir test");

    let path_captured = path.clone();
    let payload = panic::catch_unwind(move || {
        parse_reference_packet(member, &path_captured);
    })
    .expect_err("parse_reference_packet must reject regular files");

    // Cleanup before the assertions so a message-shape regression does not
    // leak the temp file across CI runs.
    let _ = std::fs::remove_file(&path);

    let msg = panic_payload_string(&*payload);
    assert!(
        msg.contains("does not exist or is not a directory"),
        "panic must name the failure mode consistently with the missing-path \
         branch (one message shape for both `.is_dir() == false` reasons); \
         got: {msg}",
    );
    assert!(
        msg.contains("VOKRA_KOTOBA_WHISPER_REFDIR"),
        "panic must name the specific env var (owner-actionable); got: {msg}",
    );
}

/// An empty directory must fail instead of being treated as a reference.
#[test]
fn reference_packet_rejects_empty_directory() {
    let member = &FAMILY[0];
    let dir = temp_scratch("empty_dir");
    // Best-effort cleanup of any stale artifact then materialize the dir
    // and drain any lingering entries so the "empty" invariant holds.
    let _ = std::fs::remove_file(&dir);
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("create empty temp dir for refdir test");
    for entry in std::fs::read_dir(&dir)
        .expect("read empty temp dir")
        .flatten()
    {
        let p = entry.path();
        if p.is_dir() {
            let _ = std::fs::remove_dir_all(&p);
        } else {
            let _ = std::fs::remove_file(&p);
        }
    }

    let dir_captured = dir.clone();
    let payload = panic::catch_unwind(move || {
        parse_reference_packet(member, &dir_captured);
    })
    .expect_err("an empty reference directory must not be accepted");
    let msg = panic_payload_string(&*payload);
    assert!(msg.contains("manifest.json"));

    let _ = std::fs::remove_dir_all(&dir);
}

/// Membership pin for the `FAMILY` manifest. `family_arch_slugs_are_distinct`
/// calls `Vec::dedup` on the slugs — but on an EMPTY family the deduped +
/// sorted Vec is trivially equal to itself, so an accidental deletion of
/// both entries would slip past both existing family tests. This test flips
/// that failure mode into a loud, specific mismatch and names the two
/// canonical members so a rebase that dropped either one is immediately
/// visible.
///
/// When a genuine new member lands (e.g. `distil-medium.en`, or a future
/// `kotoba-whisper-v3`), the maintainer must update the pinned set here —
/// that friction is exactly what the header comment (lines 87-90) invites.
#[test]
fn family_membership_is_pinned() {
    assert!(
        FAMILY.len() >= 2,
        "FAMILY must contain at least the two canonical members \
         (distil-whisper + kotoba-whisper); a rebase that emptied FAMILY \
         would let family_arch_slugs_are_distinct pass on an empty Vec"
    );

    let mut got: Vec<&'static str> = FAMILY.iter().map(|m| m.expected_arch).collect();
    got.sort_unstable();

    let mut want: Vec<&'static str> = vec!["distil-whisper", "kotoba-whisper"];
    want.sort_unstable();

    assert_eq!(
        got, want,
        "FAMILY membership drift: expected sorted expected_arch set = {want:?}, \
         got {got:?}. If a new member is being added, update this pin AND the \
         SPDX-distinctness test below; if a member is being removed, weigh the \
         provenance / license fallout first (see the arch_slug rustdoc).",
    );
}

/// Guards against a rebase-time copy-paste bug that would set both members'
/// `weight_license_spdx` to the same value (e.g. both `MIT`) — such a bug
/// would let the WRONG SPDX ride into the produced GGUFs and silently break
/// the downstream license-audit tooling that pattern-matches on the exact
/// SPDX literal (see the per-model rustdoc on `weight_license_spdx`, and
/// the license-round-trip assertions inside the two env-gated per-model
/// tests). Distinctness across FAMILY today is a strict property; if a
/// future member legitimately shares a license with an existing one, this
/// test must be re-shaped to check a specific expected multiset.
#[test]
fn family_license_spdx_values_are_distinct() {
    let mut licenses: Vec<&'static str> = FAMILY.iter().map(|m| m.weight_license_spdx).collect();
    licenses.sort_unstable();
    let mut deduped = licenses.clone();
    deduped.dedup();
    assert_eq!(
        licenses, deduped,
        "weight_license_spdx values must be pairwise distinct across FAMILY, \
         got {licenses:?}. A copy-paste bug that set both members to the same \
         SPDX literal would let the WRONG license ride into GGUFs — \
         downstream license-audit tooling pattern-matches on the exact literal \
         (see per-model rustdoc `# Weight license`).",
    );
}

/// `skip_reason` must carry three grep-friendly wording contracts that the
/// existing `skip_reason_includes_env_var_and_upstream_repo` does not pin:
///
/// - `SKIP:` prefix — CI log aggregators distinguish green-skips from
///   green-passes by scanning for this literal. Softening to `[skipped]` or
///   `SKIPPED —` would silently break every dashboard scraper.
/// - `FR-EX-08` requirement anchor — cross-refs the fabricated-pass ban so
///   a future reader can trace WHY the harness refuses to synthesize a pass.
/// - `fabricated pass` self-audit wording — mirrors the harness rustdoc
///   (lines 15-22). A refactor that dropped this wording would erase the
///   discipline signal even though the env-var + repo tokens are still present.
#[test]
fn skip_reason_contains_grep_prefix_and_fr_ex_08_anchors() {
    let msg = skip_reason("distil_whisper", "distil-whisper/distil-large-v3.5");
    assert!(
        msg.contains("SKIP:"),
        "skip_reason must carry the literal `SKIP:` prefix (grep contract for \
         CI log aggregators — a `[skipped]` / `SKIPPED —` softening would \
         silently break dashboard scrapers); got: {msg}",
    );
    assert!(
        msg.contains("FR-EX-08"),
        "skip_reason must anchor the fabricated-pass ban to requirement \
         FR-EX-08 (traceability); got: {msg}",
    );
    assert!(
        msg.contains("fabricated pass"),
        "skip_reason must include the `fabricated pass` self-audit wording \
         (discipline signal — mirrors the harness rustdoc lines 15-22); \
         got: {msg}",
    );
}

// ---------------------------------------------------------------------------
// Cross-module architectural invariants (Scout A-5 follow-up, 2026-07-29).
//
// The rustdocs on both `distil_whisper` and `kotoba_whisper` claim they share
// the **exact same architectural shape** — the Whisper large-v3 encoder with
// a shrunk 2-layer decoder. That claim is the whole basis of the "very cheap
// follow-on" contract (both delegate to `crate::whisper::WhisperModel` with a
// shrunk `n_text_layer`; every op / kernel is shared verbatim).
//
// Today the claim lives only in the module rustdocs and is transitively
// enforced by the two env-gated per-model tests reading tensor axes from real
// GGUFs. On the CI baseline (env vars unset), a drift where one factory
// updated its `d_model` / `n_audio_layer` / etc. but the other did not would
// slip past every existing test. These tests turn that documented invariant
// into a machine-checked cross-module contract, executed on every `cargo
// test` — no fixture required.
// ---------------------------------------------------------------------------

/// Both modules' primary-source configs share the exact architectural
/// quintuple `(d_model=1280, n_audio_layer=32, n_text_layer=2, n_mels=128,
/// n_vocab=51_866)`. This is the shape of "Whisper large-v3 encoder + shrunk
/// 2-layer decoder" — the "very cheap follow-on" foundation. A regression
/// that shifted either factory (e.g. a hypothetical rebase that updated
/// `n_vocab` on the distil side but not the kotoba side) would silently
/// break the shared-runtime delegation contract; this test catches it.
#[test]
fn family_shares_architectural_quintuple() {
    let d = vokra_models::distil_whisper::DistilWhisperConfig::distil_large_v3_5();
    let k = vokra_models::kotoba_whisper::KotobaWhisperConfig::kotoba_whisper_v2_0();
    // Encoder shape — must be identical (both keep the large-v3 encoder
    // intact).
    assert_eq!(
        (
            d.d_model,
            d.n_audio_layer,
            d.n_audio_head,
            d.n_audio_ctx,
            d.n_mels
        ),
        (
            k.d_model,
            k.n_audio_layer,
            k.n_audio_head,
            k.n_audio_ctx,
            k.n_mels
        ),
        "distil-whisper vs kotoba-whisper encoder shape mismatch: \
         (d_model, n_audio_layer, n_audio_head, n_audio_ctx, n_mels) \
         diverged. Both modules claim the same Whisper large-v3 encoder \
         topology in their rustdocs — that claim is the basis of the \
         shared `WhisperModel` delegation. If a genuine divergence is \
         being introduced, this pin must be updated deliberately.",
    );
    // Decoder shape — must be identical (both shrink to 2 layers).
    assert_eq!(
        (d.n_text_layer, d.n_text_head, d.n_text_ctx),
        (k.n_text_layer, k.n_text_head, k.n_text_ctx),
        "distil-whisper vs kotoba-whisper decoder shape mismatch: \
         (n_text_layer, n_text_head, n_text_ctx) diverged. The 2-layer \
         decoder is the distil axis shared across the whisper-extras \
         family — a divergence here would mean the two GGUFs need \
         different decoder loops, breaking the shared runtime.",
    );
    // Vocab + FFN — must be identical (both inherit the large-v3
    // multilingual tokenizer and FFN width).
    assert_eq!(
        (d.n_vocab, d.ffn_dim),
        (k.n_vocab, k.ffn_dim),
        "distil-whisper vs kotoba-whisper (n_vocab, ffn_dim) mismatch: \
         both modules must inherit large-v3's multilingual vocab \
         (51_866 for <|yue|>) and FFN width (5120).",
    );
    // Pin the specific quintuple documented in both module rustdocs so a
    // rebase that shifted BOTH factories in lockstep is still caught (the
    // above cross-module equality checks would silently pass on a
    // synchronized drift; this pin binds the shape to the primary-source
    // upstream config.json values fetched 2026-07-24 / 2026-07-25).
    let quintuple = (
        d.d_model,
        d.n_audio_layer,
        d.n_text_layer,
        d.n_mels,
        d.n_vocab,
    );
    assert_eq!(
        quintuple,
        (1280, 32, 2, 128, 51_866),
        "distil-large-v3.5 quintuple must match the upstream \
         config.json (fetched 2026-07-24): (d_model=1280, \
         n_audio_layer=32, n_text_layer=2, n_mels=128, n_vocab=51866). \
         Any change here must be paired with an update to the module \
         rustdocs and the converter's `derive_name` table.",
    );
}

/// The Whisper family invariant `head_dim = d_model / n_head = 64` must hold
/// on both encoder and decoder for both modules. The rustdocs claim this as
/// "the Whisper invariant across every family size" (base / small / medium /
/// large-v3 / turbo / distil-large-v3.5 / kotoba-whisper). If either side
/// shifted (e.g. accidentally set `n_audio_head = 16` while keeping `d_model
/// = 1280`, yielding `head_dim = 80`), the pre-baked attention kernels
/// hard-coded to `head_dim = 64` (see e.g. FA v2 driver) would silently
/// produce garbage. This test binds the invariant to the primary-source
/// factories.
#[test]
fn family_head_dim_is_the_whisper_invariant_64() {
    let d = vokra_models::distil_whisper::DistilWhisperConfig::distil_large_v3_5();
    let k = vokra_models::kotoba_whisper::KotobaWhisperConfig::kotoba_whisper_v2_0();
    // Encoder head dim.
    assert_eq!(
        d.head_dim(),
        64,
        "distil-large-v3.5 head_dim = {} != 64 (Whisper family invariant)",
        d.head_dim(),
    );
    assert_eq!(
        k.head_dim(),
        64,
        "kotoba-whisper-v2.0 head_dim = {} != 64 (Whisper family invariant)",
        k.head_dim(),
    );
    // Decoder head split — Whisper convention is `n_text_head == n_audio_head`
    // for both distil and kotoba (unlike turbo which shrinks n_text_head).
    // A future distil/kotoba variant that shifted the ratio would be a new
    // family and must extend this test with an explicit pin.
    assert_eq!(
        d.n_text_head, d.n_audio_head,
        "distil-large-v3.5: n_text_head ({}) must equal n_audio_head ({}) \
         (the family keeps the encoder head count on the decoder side)",
        d.n_text_head, d.n_audio_head,
    );
    assert_eq!(
        k.n_text_head, k.n_audio_head,
        "kotoba-whisper: n_text_head ({}) must equal n_audio_head ({}) \
         (the family keeps the encoder head count on the decoder side)",
        k.n_text_head, k.n_audio_head,
    );
}

/// Both modules' primary-source configs share the exact same tokenizer
/// boundary constants: `eot = 50_257` (`<|endoftext|>`), `sot = 50_258`
/// (`<|startoftranscript|>`), and `sample_rate = 16_000` (Whisper feature
/// extractor). The rustdocs claim these come from the large-v3 multilingual
/// tokenizer, invariant across the whisper-extras family. A converter that
/// silently updated `eot` on one side would break decode stop conditions;
/// this test pins the invariant.
#[test]
fn family_shares_tokenizer_and_sample_rate_constants() {
    let d = vokra_models::distil_whisper::DistilWhisperConfig::distil_large_v3_5();
    let k = vokra_models::kotoba_whisper::KotobaWhisperConfig::kotoba_whisper_v2_0();
    assert_eq!(
        d.eot, 50_257,
        "distil-large-v3.5 eot = {}, expected 50_257 (Whisper multilingual \
         <|endoftext|>)",
        d.eot,
    );
    assert_eq!(
        k.eot, 50_257,
        "kotoba-whisper-v2.0 eot = {}, expected 50_257 (Whisper multilingual \
         <|endoftext|>)",
        k.eot,
    );
    assert_eq!(
        d.sot, 50_258,
        "distil-large-v3.5 sot = {}, expected 50_258 (Whisper multilingual \
         <|startoftranscript|>)",
        d.sot,
    );
    assert_eq!(
        k.sot, 50_258,
        "kotoba-whisper-v2.0 sot = {}, expected 50_258 (Whisper multilingual \
         <|startoftranscript|>)",
        k.sot,
    );
    // Sample rate is the Whisper feature-extractor convention, not derived
    // from config.json — both modules inherit it from the openai/whisper
    // preprocessor. A future kotoba-whisper variant that shifted this
    // (e.g. some 24 kHz Japanese-specific pre-processing) would break the
    // shared runtime; this pin catches it.
    assert_eq!(
        d.sample_rate, 16_000,
        "distil-large-v3.5 sample_rate = {} Hz, expected 16_000 Hz \
         (Whisper convention)",
        d.sample_rate,
    );
    assert_eq!(
        k.sample_rate, 16_000,
        "kotoba-whisper-v2.0 sample_rate = {} Hz, expected 16_000 Hz \
         (Whisper convention)",
        k.sample_rate,
    );
    // Cross-module equality: both must agree on these constants, not just
    // each match some absolute expectation.
    assert_eq!(
        (d.eot, d.sot, d.sample_rate),
        (k.eot, k.sot, k.sample_rate),
        "distil / kotoba tokenizer + sample-rate constants must be pairwise \
         equal; got distil=({}, {}, {}) vs kotoba=({}, {}, {})",
        d.eot,
        d.sot,
        d.sample_rate,
        k.eot,
        k.sot,
        k.sample_rate,
    );
}

/// The distil invariant `n_text_layer < n_audio_layer` must hold on BOTH
/// primary-source config factories. The individual module unit tests each
/// verify this for their own factory, but there is no cross-module test
/// today: a rebase that broke the invariant on one side (e.g. set
/// `n_text_layer = 32` on kotoba to match encoder depth) would slip past the
/// other module's tests silently. This test binds both sides in one place.
#[test]
fn family_distil_invariant_holds_on_both_primary_source_factories() {
    let d = vokra_models::distil_whisper::DistilWhisperConfig::distil_large_v3_5();
    let k = vokra_models::kotoba_whisper::KotobaWhisperConfig::kotoba_whisper_v2_0();
    assert!(
        d.n_text_layer < d.n_audio_layer,
        "distil-large-v3.5 distil invariant broken: n_text_layer={} \
         must be < n_audio_layer={}. A distil checkpoint shrinks the \
         decoder; equal or larger decoder depth is not distil (it is \
         vanilla Whisper).",
        d.n_text_layer,
        d.n_audio_layer,
    );
    assert!(
        k.n_text_layer < k.n_audio_layer,
        "kotoba-whisper-v2.0 distil invariant broken: n_text_layer={} \
         must be < n_audio_layer={}. Kotoba-whisper is Japanese-distilled \
         from large-v3 with a shrunk decoder; equal or larger decoder \
         depth is not kotoba-whisper.",
        k.n_text_layer,
        k.n_audio_layer,
    );
    // Both primary-source factories must produce well-formed configs
    // (validate_for_forward returns Ok). If a future rebase introduced a
    // primary-source factory whose invariants fail, both env-gated tests
    // would panic — this test surfaces the bug on any `cargo test` without
    // needing a fixture.
    d.validate_for_forward()
        .expect("distil-large-v3.5 primary-source config must validate");
    k.validate_for_forward()
        .expect("kotoba-whisper-v2.0 primary-source config must validate");
}

/// The VAST runner and reference manifest pin
/// `kotoba-tech/kotoba-whisper-v2.2` (see `KOTOBA_REPO` in the runner).
/// The runtime compliance registry lists `-v1.0` /
/// `-v1.1` / `-v2.0` / `-v2.1` / `-bilingual-v1.0` explicitly and covers
/// `-v2.2` transitively via the `kotoba-whisper-` prefix walk. This test
/// pins the exact VAST-pinned literal so that a future prefix-walk
/// removal or a rebase that dropped the walk would surface a red test
/// **before** the CI job produces a GGUF that the license registry cannot
/// classify. Without this pin, a `kotoba-whisper-v2.2` resolution failure
/// would only surface as a runtime `M2-13` refusal after minutes of HF
/// download and conversion — an expensive round trip for a preventable
/// static drift.
#[test]
fn workflow_pinned_kotoba_v2_2_resolves_permissive() {
    use vokra_core::compliance::{LicenseClass, registry_lookup};
    for id in [
        // The precise slug the VAST runner and reference manifest pin (see
        // run_vast_validation.sh KOTOBA_REPO —
        // resolved to the model id after stripping the `kotoba-tech/`
        // owner prefix).
        "kotoba-whisper-v2.2",
        // Underscore alias — the runtime module's rustdoc lists the
        // dot/underscore pair explicitly for every other member; v2.2 is
        // added here for parity with the walk's dash-based prefix rule.
        "kotoba-whisper-v2_2",
        // Also pin a hypothetical future release so the prefix-walk
        // contract stays visible: any `kotoba-whisper-vN.M` (N,M >= 0)
        // must resolve Permissive. A future member with a different
        // license would need its own registry arm carved out.
        "kotoba-whisper-v3.0",
    ] {
        assert_eq!(
            registry_lookup(id),
            Some(LicenseClass::Permissive),
            "compliance registry must resolve `{id}` to Permissive \
             (Apache-2.0). The VAST runner and reference manifest pin \
             kotoba-whisper-v2.2 \
             specifically; if this test regresses, the M2-13 gate would \
             reject a converted GGUF from a workflow run that already \
             paid the HF download cost.",
        );
    }
}

/// Mirror of the kotoba pin above: the VAST runner and reference manifest pin
/// `distil-whisper/distil-large-v3.5` and the runtime module's rustdoc
/// lists both `distil-whisper` and `distil-large-*` variants as Permissive
/// (MIT). Binds the exact VAST-pinned literal so a prefix-walk
/// regression on the distil side is caught statically, symmetric with the
/// kotoba-side pin.
#[test]
fn workflow_pinned_distil_large_v3_5_resolves_permissive() {
    use vokra_core::compliance::{LicenseClass, registry_lookup};
    for id in [
        // The precise slug the VAST runner pins (after stripping the
        // `distil-whisper/` owner prefix — see
        // parity-whisper-extras-real.yml env.DISTIL_WHISPER_REPO).
        "distil-large-v3.5",
        // Underscore alias — mirror of the kotoba-side pin so the dot /
        // underscore variance both flow through registry_lookup.
        "distil-large-v3_5",
        // A hypothetical future distil member — any future
        // `distil-large-*` release must stay Permissive via the walk.
        "distil-large-v4.0",
    ] {
        assert_eq!(
            registry_lookup(id),
            Some(LicenseClass::Permissive),
            "compliance registry must resolve `{id}` to Permissive (MIT). \
             The VAST runner pins distil-large-v3.5 specifically; a \
             prefix-walk regression here would let a converted GGUF from \
             a workflow-paid HF download fail the M2-13 gate.",
        );
    }
}
