//! Exact parity against the official Transformers MusicGen scheduling code.
//!
//! The reference is generated on VAST by
//! `tools/parity/musicgen_delay_pattern_dump_reference.py`, which imports the
//! pinned upstream methods directly and never constructs a model. The fixture
//! is intentionally not invented or regenerated by this Rust implementation.

use std::path::{Path, PathBuf};

use vokra_ops::musicgen_delay_pattern::{
    MusicGenDelayPatternAttrs, apply_musicgen_delay_pattern, build_musicgen_delay_pattern,
};

const REFERENCE_DIR_ENV: &str = "VOKRA_MUSICGEN_DELAY_REFERENCE_DIR";
const PAD: u32 = 2_048;

fn read_u32(path: &Path) -> Vec<u32> {
    let bytes = std::fs::read(path).unwrap_or_else(|error| panic!("read {path:?}: {error}"));
    assert_eq!(bytes.len() % 4, 0, "unaligned u32 fixture: {path:?}");
    bytes
        .chunks_exact(4)
        .map(|chunk| u32::from_le_bytes(chunk.try_into().unwrap()))
        .collect()
}

fn read_i64(path: &Path) -> Vec<i64> {
    let bytes = std::fs::read(path).unwrap_or_else(|error| panic!("read {path:?}: {error}"));
    assert_eq!(bytes.len() % 8, 0, "unaligned i64 fixture: {path:?}");
    bytes
        .chunks_exact(8)
        .map(|chunk| i64::from_le_bytes(chunk.try_into().unwrap()))
        .collect()
}

fn check_case(
    reference: &Path,
    stem: &str,
    attrs: MusicGenDelayPatternAttrs,
) -> vokra_ops::musicgen_delay_pattern::MusicGenDelayPattern {
    let input = read_u32(&reference.join(format!("{stem}.input_ids.u32")));
    let expected_prefix = read_u32(&reference.join(format!("{stem}.prefix.u32")));
    let expected_pattern = read_i64(&reference.join(format!("{stem}.pattern.i64")));
    let got = build_musicgen_delay_pattern(&input, attrs).expect("build delay pattern");
    assert_eq!(got.prefix, expected_prefix, "{stem}: prefix diverged");
    assert_eq!(got.pattern, expected_pattern, "{stem}: pattern diverged");
    got
}

#[test]
#[ignore = "requires a VAST-generated official Transformers 4.45.2 fixture"]
fn musicgen_delay_pattern_matches_official_transformers() {
    let reference = PathBuf::from(
        std::env::var_os(REFERENCE_DIR_ENV)
            .unwrap_or_else(|| panic!("{REFERENCE_DIR_ENV} must point at the official dump")),
    );
    assert!(
        reference.is_dir(),
        "reference is not a directory: {reference:?}"
    );

    check_case(
        &reference,
        "mono_no_prompt",
        MusicGenDelayPatternAttrs {
            batch_size: 1,
            num_codebooks: 4,
            prompt_len: 1,
            max_length: 8,
            audio_channels: 1,
            pad_token_id: PAD,
        },
    );
    let prompted = check_case(
        &reference,
        "mono_prompted",
        MusicGenDelayPatternAttrs {
            batch_size: 1,
            num_codebooks: 4,
            prompt_len: 3,
            max_length: 8,
            audio_channels: 1,
            pad_token_id: PAD,
        },
    );
    check_case(
        &reference,
        "stereo_no_prompt",
        MusicGenDelayPatternAttrs {
            batch_size: 1,
            num_codebooks: 4,
            prompt_len: 1,
            max_length: 5,
            audio_channels: 2,
            pad_token_id: PAD,
        },
    );
    check_case(
        &reference,
        "mono_short_sequence",
        MusicGenDelayPatternAttrs {
            batch_size: 1,
            num_codebooks: 4,
            prompt_len: 1,
            max_length: 6,
            audio_channels: 1,
            pad_token_id: PAD,
        },
    );

    let mut generated = vec![99; 4 * 5];
    apply_musicgen_delay_pattern(
        &mut generated,
        prompted.rows,
        5,
        &prompted.pattern,
        prompted.max_length,
    )
    .expect("apply delay pattern");
    assert_eq!(
        generated,
        read_u32(&reference.join("mono_prompted.applied.u32")),
        "mono_prompted: applied values diverged"
    );
}
