#!/usr/bin/env python3
"""CAM++ (3D-Speaker) speaker-encoder parity fixtures (M0-08).

Oracle for the native `vokra-models` CAM++ forward pass. Feeds a FIXED, seeded
random fbank input `[1, T, 80]` through the reference `campplus.onnx` under
onnxruntime and dumps the final 192-d embedding plus a set of intermediate node
outputs (chosen by walking the graph) that localise the fault when the native
port diverges. The fbank->embedding NETWORK is fully validatable this way; the
audio->fbank FRONTEND is validated separately once a Kaldi-fbank oracle exists.

Outputs (f32 little-endian, C-order) + manifest.txt (shape + sha256). Re-run:

    python tests/parity/camplus/gen_reference.py \
        --onnx /path/to/campplus.onnx --out tests/parity/camplus
"""

import argparse
import hashlib
import pathlib

import numpy as np
import onnx
import onnxruntime as ort

SEED = 1234
T = 200  # fbank frames (arbitrary but fixed; > cam_seg_len=100 so seg_pool tiles)
FEAT = 80  # fbank bins

# Intermediate node output edges, pinned by a graph walk of campplus.onnx. Each
# tuple is (fixture_stem, onnx_value_name). These localise the port over 3206
# nodes: FCM reshape -> tdnn -> D-TDNN blocks 1/2/3 -> stats pooling -> embed.
INTERMEDIATES = [
    ("post_fcm_reshape", "/head/Reshape_output_0"),
    ("post_tdnn", "/xvector/tdnn/nonlinear/relu/Relu_output_0"),
    ("post_block1", "/xvector/block1/Concat_11_output_0"),
    ("post_block2", "/xvector/block2/Concat_23_output_0"),
    ("post_block3", "/xvector/block3/Concat_15_output_0"),
    ("post_stats", "/xvector/stats/Concat_output_0"),
]
FINAL = ("embedding", "output")


def sha16(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()[:16]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--onnx", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    # Augment the graph so onnxruntime exposes the intermediate edges as outputs.
    model = onnx.load(args.onnx)
    existing = {o.name for o in model.graph.output}
    for _stem, name in INTERMEDIATES:
        if name not in existing:
            model.graph.output.append(onnx.helper.make_empty_tensor_value_info(name))
    aug = out / "_campplus_augmented.onnx"
    onnx.save(model, str(aug))

    # Fixed, seeded fbank input.
    rng = np.random.default_rng(SEED)
    fbank = rng.standard_normal((1, T, FEAT)).astype(np.float32)

    sess = ort.InferenceSession(str(aug), providers=["CPUExecutionProvider"])
    in_name = sess.get_inputs()[0].name
    want = [name for _stem, name in INTERMEDIATES] + [FINAL[1]]
    outs = sess.run(want, {in_name: fbank})
    named = dict(zip(want, outs))
    aug.unlink()  # do not commit the temporary augmented model

    lines = [
        "# CAM++ (3D-Speaker) speaker-encoder parity manifest (M0-08).",
        "# Generated by tests/parity/camplus/gen_reference.py from campplus.onnx",
        "# via onnxruntime. `<stem> shape=[..] len=N sha256=<hex16>`; f32 LE C-order.",
        f"model = iic/speech_campplus (CAM++ 3D-Speaker)",
        f"seed = {SEED}",
        f"atol = 0.01",
        f"input_frames = {T}",
        f"feat_dim = {FEAT}",
        f"embed_dim = {int(named[FINAL[1]].size)}",
    ]

    def dump(stem: str, arr: np.ndarray) -> None:
        arr = np.ascontiguousarray(arr.astype(np.float32))
        b = arr.tobytes()
        (out / f"{stem}.f32").write_bytes(b)
        lines.append(
            f"{stem} shape={list(arr.shape)} len={arr.size} sha256={sha16(b)}"
        )

    dump("input_fbank", fbank)
    for stem, name in INTERMEDIATES:
        dump(stem, named[name])
    dump(FINAL[0], named[FINAL[1]])

    (out / "manifest.txt").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
