//! # vokra-capi
//!
//! C ABI surface for the Vokra runtime (SRS §1.3: "C ABI"), the single
//! binding layer for Unity / Godot / other host runtimes (FR-API-01). The
//! generated header is `include/vokra.h` (cbindgen, `scripts/gen-c-abi.sh`);
//! see `docs/adr/0003-c-abi-design.md`.
//!
//! The public product of this crate is its set of `#[no_mangle]`
//! `extern "C"` symbols, exported from the `libvokra` cdylib/staticlib. The
//! Rust modules below are internal; C consumers see only `include/vokra.h`.
//!
//! # Surface (M0-09)
//!
//! - **Status / errors** (`error`): `vokra_status_t`, thread-local errno +
//!   `vokra_last_error()`.
//! - **Handles** (`handle`): opaque `vokra_session_t` / `vokra_stream_t`.
//! - **Boundary guard** (`ffi_guard`): `catch_unwind` firewall + NULL / UTF-8
//!   argument validation (no panic ever crosses the boundary — NFR-RL-07).
//! - **Session** (`session`): `vokra_session_create_from_file` (arch-detected
//!   engine injection), `vokra_session_retain` (atomic ref count, FR-API-03),
//!   `vokra_session_destroy`, `vokra_version`.
//! - **ASR** (`asr`): `vokra_asr_transcribe` + `vokra_string_free`.
//! - **TTS** (`tts`): `vokra_tts_synthesize` (piper-plus native, no
//!   onnxruntime) + `vokra_audio_free`.
//! - **Streaming** (`stream`): `vokra_stream_open` / `_push_pcm` / `_poll`
//!   (f32 speech probabilities) / `_poll_events` (typed `vokra_event_t`, M1-08) /
//!   `_destroy`, over a lock-free SPSC ring (FR-ST-02).
//!
//! M0 (v0.1 spike) has **no ABI stability commitment** (IF-01; the semver
//! commitment starts at v1.0). The header is regenerated by CI and must not be
//! hand-edited.
//!
//! # Unsafe policy (NFR-RL-07, SRS §5-(1))
//!
//! A C ABI inevitably requires `unsafe` (raw pointers across the FFI
//! boundary), so this crate opts out of the workspace-wide
//! `unsafe_code = "deny"` below. Safety is guaranteed *at the API boundary*
//! (argument validation, no panics across FFI — see [`ffi_guard`]), and every
//! `unsafe` block carries a `// SAFETY:` comment (enforced by
//! `clippy::undocumented_unsafe_blocks` at the workspace level).
//!
//! # Numeric parsing policy (NFR-RL-01)
//!
//! The C ABI takes typed numeric arguments (`int32_t` / `float` / `size_t`);
//! it never converts strings to numbers, so the `LC_NUMERIC`-sensitive
//! `strtod` is absent by construction. `scripts/check-forbidden-symbols.sh`
//! scans `crates/vokra-capi/` and the C smoke tests under `tests/capi/`.

// Local opt-out from the workspace `unsafe_code = "deny"` lint — see the
// crate-level "Unsafe policy" docs above (M0-02-T03).
#![allow(unsafe_code)]

mod asr;
mod error;
mod ffi_guard;
mod handle;
mod session;
mod stream;
mod tts;
