/*
 * vokra.h — C ABI for the Vokra speech runtime.
 *
 * Copyright The Vokra Authors.
 * SPDX-License-Identifier: Apache-2.0
 *
 * !!! AUTO-GENERATED by cbindgen from the `vokra-capi` crate — DO NOT EDIT. !!!
 * Regenerate with `scripts/gen-c-abi.sh`; CI fails on drift
 * (`scripts/gen-c-abi.sh --check`).
 *
 * STABILITY: this is the v0.9 (M3) window. The ABI is NOT frozen; the semver
 * ABI-stability commitment starts at v1.0 GA (IF-01; docs/milestones.md §4.2
 * note 3, §9 M5-13; the 2026-07-14 v-label reassignment #2 moved the freeze
 * executor from M4-12 to M5-13 — v1.0 GA = M5 close, M4 = v1.0-rc
 * prerelease). During the v0.9 window every symbol delta must be
 * recorded in docs/abi-changelog.md and covered by an entry dated on the day
 * the PR opens — scripts/check-abi-changelog.sh (M3-16) enforces this.
 */

#ifndef VOKRA_H
#define VOKRA_H

/* Generated by cbindgen. Do not edit by hand — see scripts/gen-c-abi.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Status code returned by the fallible Vokra C functions (ADR-0003 §3-d).
//
// `VOKRA_OK` is 0; every error is a distinct non-zero code mirroring a
// `VokraError` variant, plus `VOKRA_ERROR_PANIC` for a Rust panic caught at
// the FFI boundary and `VOKRA_ERROR_OTHER` for any future `#[non_exhaustive]`
// variant. The numeric values are part of the (M0-unstable) ABI.
typedef enum vokra_status_t {
    // Success.
    VOKRA_OK = 0,
    // I/O failure (file open / read / metadata). Maps `VokraError::Io`.
    VOKRA_ERROR_IO = 1,
    // A model file could not be loaded or parsed. Maps `VokraError::ModelLoad`.
    VOKRA_ERROR_MODEL_LOAD = 2,
    // The selected backend does not support an op. Maps `VokraError::UnsupportedOp`.
    VOKRA_ERROR_UNSUPPORTED_OP = 3,
    // The requested backend is unavailable. Maps `VokraError::BackendUnavailable`.
    VOKRA_ERROR_BACKEND_UNAVAILABLE = 4,
    // A caller-supplied argument is invalid (NULL, non-UTF-8, wrong rate, ...).
    // Maps `VokraError::InvalidArgument`.
    VOKRA_ERROR_INVALID_ARGUMENT = 5,
    // An audio graph failed validation. Maps `VokraError::GraphValidation`.
    VOKRA_ERROR_GRAPH_VALIDATION = 6,
    // The requested capability is not wired for this model/task (e.g. calling
    // TTS on an ASR model). Maps `VokraError::NotImplemented`.
    VOKRA_ERROR_NOT_IMPLEMENTED = 7,
    // A Rust panic was caught at the FFI boundary (never propagated across it).
    VOKRA_ERROR_PANIC = 8,
    // Any other / future error variant.
    VOKRA_ERROR_OTHER = 9,
} vokra_status_t;

// Per-frame outcome reported by [`vokra_aec_process`] (mirrors
// `vokra_ops::AecStatus`; FR-EX-08 — degraded modes are visible, never
// silent).
typedef enum vokra_aec_status_t {
    // Far-end window fully covered; the canceller ran normally.
    VOKRA_AEC_CANCELLED = 0,
    // Nothing is playing and the far-end history is silent: the mic frame
    // was copied through bit-exactly (state frozen).
    VOKRA_AEC_PASS_THROUGH = 1,
    // Part (or all) of the far-end window had no data and was zero-filled;
    // the live echo tail keeps being cancelled. The missing sample count is
    // reported through `out_missing`.
    VOKRA_AEC_PARTIAL_REFERENCE = 2,
    // The divergence guard fired and the canceller reset itself this frame.
    VOKRA_AEC_RESET = 3,
} vokra_aec_status_t;

// Kind tag of a [`vokra_event_t`] (M1-08). The numeric values are part of the
// (M0-unstable) ABI.
typedef enum vokra_event_kind_t {
    // Unknown / reserved event kind (forward-compat placeholder).
    VOKRA_EVENT_UNKNOWN = 0,
    // A VAD speech-probability event: `a` = frame index, `b` = probability.
    VOKRA_EVENT_SPEECH_PROB = 1,
    // An ASR token event: `a` = token id, `b` = reserved (`0`).
    VOKRA_EVENT_TOKEN = 2,
} vokra_event_kind_t;

// Opaque far-end writer handle: the producer half of the far-end queue.
// Owned by the playback-callback thread. Opaque to C.
typedef struct vokra_aec_ref_writer_t vokra_aec_ref_writer_t;

// Opaque AEC handle: the canceller state plus the reader half of the
// far-end queue. Owned by the inference thread. Opaque to C.
typedef struct vokra_aec_t vokra_aec_t;

// Opaque duplex-session handle (module docs). Created by
// `vokra_s2s_duplex_open`, released by `vokra_s2s_duplex_destroy`.
typedef struct vokra_s2s_duplex_t vokra_s2s_duplex_t;

// Opaque cross-thread barge-in handle (module docs). Created by
// `vokra_s2s_interrupt_handle`, released by
// `vokra_s2s_interrupt_destroy`; firing it is `vokra_s2s_interrupt`.
typedef struct vokra_s2s_interrupt_t vokra_s2s_interrupt_t;

// Opaque session handle: one loaded model bound to one backend, with the
// matching native engine injected (ASR / TTS / VAD — see
// `crate::session::vokra_session_create_from_file`).
//
// Created by `vokra_session_create_from_file`, cloned by
// `vokra_session_retain` (atomic ref count, FR-API-03) and released by
// `vokra_session_destroy`. The loaded model stays alive until the last handle
// is destroyed. Backed by `Session: Send + Sync`, so a handle is safe to share
// across C threads. Opaque to C.
typedef struct vokra_session_t vokra_session_t;

// Opaque streaming handle: a native stepping [`Stream`] (M1-08) whose events
// flow through a lock-free ring, drained by `vokra_stream_poll` (VAD speech
// probabilities) or `vokra_stream_poll_events` (typed events).
//
// Created by `vokra_stream_open`, released by `vokra_stream_destroy`. Opaque to
// C. All recurrent state (LSTM `h`/`c`, framing, KV cache) is hidden inside the
// stepper (FR-LD-06 / FR-ST-05).
typedef struct vokra_stream_t vokra_stream_t;

// Construction parameters for [`vokra_aec_create`].
//
// `sample_rate` / `frame_size` / `filter_length` follow the SpeexDSP
// guidance (speex_echo.h: a frame of 10-20 ms; a tail of 100-500 ms).
// `frame_size` must be even. `ref_queue_capacity_samples` sizes the far-end
// queue; `0` selects the documented default of `8 * filter_length` samples
// (rounded up to a power of two).
typedef struct vokra_aec_config_t {
    // Sample rate of mic and far-end PCM (must match on both sides).
    uint32_t sample_rate;
    // Samples per `vokra_aec_process` call (even, > 0).
    size_t frame_size;
    // Echo tail length in samples (>= frame_size).
    size_t filter_length;
    // Far-end queue capacity in samples; 0 = default (8 * filter_length).
    size_t ref_queue_capacity_samples;
} vokra_aec_config_t;

// A generalized streaming event drained by `vokra_stream_poll_events` (M1-08).
//
// A fixed 12-byte POD (`kind` + `a` + `b`); the meaning of `a` / `b` depends on
// `kind` (see [`vokra_event_kind_t`]). This layout is a new (M0-unstable) ABI
// surface, pinned by the numeric-layout test.
typedef struct vokra_event_t {
    // Discriminates how `a` / `b` are interpreted.
    enum vokra_event_kind_t kind;
    // Primary integer field (frame index for VAD, token id for ASR).
    uint32_t a;
    // Secondary float field (probability for VAD; reserved `0` for ASR).
    float b;
} vokra_event_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Creates an echo canceller and its far-end reference writer.
//
// On success writes one handle through each out-pointer; on failure both
// out-pointers are left untouched. The two handles have independent
// lifetimes (destroy each with its own `*_destroy`, in either order).
//
// # Safety
//
// `config` must be `NULL` or point to a valid [`vokra_aec_config_t`];
// `out_aec` / `out_writer` must be valid non-`NULL` out-pointers. `NULL`
// `config` is rejected as `VOKRA_ERROR_INVALID_ARGUMENT` (never
// dereferenced).
enum vokra_status_t vokra_aec_create(const struct vokra_aec_config_t *config,
                                     struct vokra_aec_t **out_aec,
                                     struct vokra_aec_ref_writer_t **out_writer);

// Pushes a far-end (playback) chunk whose first sample plays at absolute
// sample position `playback_pos`, writing the number of samples accepted to
// `out_accepted`.
//
// Reject-on-full backpressure: when the queue cannot take the whole chunk,
// only the fitting prefix is accepted (`*out_accepted < num_samples`,
// possibly 0); retry the remainder at `playback_pos + accepted` after the
// inference thread has consumed a frame. `out_accepted` is mandatory so a
// partial accept is never silent (FR-EX-08).
//
// Backward / overlapping `playback_pos` tags are an explicit
// `VOKRA_ERROR_INVALID_ARGUMENT` (time tags are monotonic; a forward gap is
// legal and reads back as silence).
//
// # Safety
//
// `writer` must be a live handle from [`vokra_aec_create`], used by one
// thread at a time (the playback callback thread). `pcm` must be `NULL`
// only when `num_samples == 0`, otherwise valid for `num_samples` reads.
// `out_accepted` must be a valid non-`NULL` out-pointer. May run
// concurrently with `vokra_aec_process` on the paired `vokra_aec_t`
// (SPSC queue), but not with itself on the same handle.
enum vokra_status_t vokra_aec_ref_push(struct vokra_aec_ref_writer_t *writer,
                                       const float *pcm,
                                       size_t num_samples,
                                       uint64_t playback_pos,
                                       size_t *out_accepted);

// Cancels the echo of one mic frame (`num_samples == frame_size`) whose
// first sample was captured at absolute sample position `mic_pos` on the
// same clock the far-end pushes use. Writes `frame_size` cancelled samples
// to `out` and the per-frame outcome ([`vokra_aec_status_t`]) to
// `out_status`; when the outcome is `VOKRA_AEC_PARTIAL_REFERENCE`, the
// number of zero-filled far-end samples is written to `out_missing`
// (optional pointer — pass `NULL` if not needed; it is set to 0 for the
// other outcomes).
//
// # Safety
//
// `aec` must be a live handle from [`vokra_aec_create`], used by one
// thread at a time (the inference thread). `mic` must be valid for
// `num_samples` reads and `out` for `num_samples` writes; `out_status`
// must be a valid non-`NULL` out-pointer; `out_missing` may be `NULL`.
// May run concurrently with `vokra_aec_ref_push` on the paired writer.
enum vokra_status_t vokra_aec_process(struct vokra_aec_t *aec,
                                      const float *mic,
                                      uint64_t mic_pos,
                                      float *out,
                                      size_t num_samples,
                                      enum vokra_aec_status_t *out_status,
                                      size_t *out_missing);

// Resets the canceller to its as-new state (bit-exact with a fresh
// [`vokra_aec_create`] of the same config). Pair it with barge-in
// (`vokra_stream_interrupt`) in full-duplex loops.
//
// # Safety
//
// `aec` must be a live handle, used by one thread at a time.
enum vokra_status_t vokra_aec_reset(struct vokra_aec_t *aec);

// Destroys an AEC handle. `NULL` is a no-op. The paired writer handle stays
// valid (its pushes simply pile up unread) and must be destroyed with
// [`vokra_aec_ref_writer_destroy`].
//
// # Safety
//
// `aec` must be `NULL` or a live handle from [`vokra_aec_create`] not used
// after this call (and not concurrently with it).
void vokra_aec_destroy(struct vokra_aec_t *aec);

// Destroys a far-end writer handle. `NULL` is a no-op. The paired AEC
// handle stays valid (its windows read as silence once the queue drains —
// the pass-through semantics take over).
//
// # Safety
//
// `writer` must be `NULL` or a live handle from [`vokra_aec_create`] not
// used after this call (and not concurrently with it).
void vokra_aec_ref_writer_destroy(struct vokra_aec_ref_writer_t *writer);

// Transcribes mono `f32` PCM to text using the session's ASR engine (FR-API-01).
//
// # Parameters
//
// - `session`: a session created from a Whisper GGUF.
// - `pcm` / `num_samples`: mono `f32` samples (may be empty). `pcm` may be
//   `NULL` only when `num_samples == 0`.
// - `sample_rate`: the PCM sample rate in Hz. It must equal the model's front
//   end sample rate — Vokra does not resample in M0 (FR-OP-04 is M1); a
//   mismatch is `VOKRA_ERROR_INVALID_ARGUMENT`.
// - `out_text_utf8`: on `VOKRA_OK`, receives a NUL-terminated UTF-8 transcript
//   to be freed with `vokra_string_free`. Untouched on error.
//
// # Safety
//
// `session` must be a valid session handle, `pcm` valid for `num_samples`
// reads (or `NULL` when `num_samples == 0`), and `out_text_utf8` a writable
// `char*` location.
enum vokra_status_t vokra_asr_transcribe(const struct vokra_session_t *session,
                                         const float *pcm,
                                         size_t num_samples,
                                         int32_t sample_rate,
                                         char **out_text_utf8);

// Frees a transcript returned by `vokra_asr_transcribe`. `NULL` is a no-op;
// double-free is undefined behaviour.
//
// # Safety
//
// `s` must be `NULL` or a pointer returned by `vokra_asr_transcribe` that has
// not already been freed.
void vokra_string_free(char *s);

// Returns the calling thread's last error message as a NUL-terminated UTF-8
// C string, or `NULL` if no error has been recorded on this thread.
//
// The returned pointer is owned by Vokra and stays valid until the next error
// is recorded **on the same thread**; do not free it and do not use it across
// threads. `vokra_last_error` itself never fails and never allocates
// (ADR-0003 §3-b).
const char *vokra_last_error(void);

// Opens a full-duplex S2S session (Moshi = M4-06) on a session whose
// model injected a duplex engine.
//
// # Parameters
//
// - `session`: a live session handle (`vokra_session_create_from_file`
//   with a `moshi` GGUF).
// - `deterministic`: non-zero → greedy (temperature-0) sampling on both
//   decode channels (reproducible demos / parity).
// - `seed`: stochastic sampling seed (ignored when `deterministic`).
// - `aec_disabled_explicitly`: non-zero **explicitly** skips the echo
//   canceller (recorded-file input only — a loud warning is recorded on
//   the session; there is no silent variant). Zero requires the engine's
//   AEC wiring and fails loudly without it (FR-OP-60).
// - `playback_offset_samples`: echo-reference clock compensation for the
//   real playback latency (owner-tunable; 0 for file-driven use).
// - `out_duplex`: on `VOKRA_OK`, receives the new handle.
//
// # Returns
//
// `VOKRA_OK`, or a non-zero status (no duplex engine on this session,
// AEC posture violation, ...) with detail from `vokra_last_error()`.
//
// # Safety
//
// `session` must be a live session handle; `out_duplex` must be a valid,
// writable pointer.
enum vokra_status_t vokra_s2s_duplex_open(const struct vokra_session_t *session,
                                          int32_t deterministic,
                                          uint64_t seed,
                                          int32_t aec_disabled_explicitly,
                                          uint64_t playback_offset_samples,
                                          struct vokra_s2s_duplex_t **out_duplex);

// Mono samples per push/pull frame of `duplex` (size your PCM buffers
// with this — 1920 for the real 24 kHz / 12.5 Hz model).
//
// # Safety
//
// `duplex` must be a live duplex handle; `out_hop` valid and writable.
enum vokra_status_t vokra_s2s_frame_hop(const struct vokra_s2s_duplex_t *duplex,
                                        size_t *out_hop);

// PCM sample rate (Hz) of both duplex directions.
//
// # Safety
//
// `duplex` must be a live duplex handle; `out_rate` valid and writable.
enum vokra_status_t vokra_s2s_sample_rate(const struct vokra_s2s_duplex_t *duplex,
                                          uint32_t *out_rate);

// Feeds one mic frame (exactly `vokra_s2s_frame_hop` samples) through
// the input front (AEC unless explicitly disabled) and one model step.
//
// `out_emitted` (optional — may be `NULL`) receives non-zero once the
// model produced a frame for this push (after its delay warmup); pull it
// with `vokra_s2s_pull_audio`.
//
// # Safety
//
// `duplex` must be a live duplex handle owned by the calling thread;
// `pcm` must point to `len` readable floats; `out_emitted` must be
// `NULL` or writable.
enum vokra_status_t vokra_s2s_push_mic(struct vokra_s2s_duplex_t *duplex,
                                       const float *pcm,
                                       size_t len,
                                       int32_t *out_emitted);

// Pops the next model frame for playback into `out_pcm`
// (`capacity >= vokra_s2s_frame_hop` floats). `*out_len` is the sample
// count written — `0` means nothing is pending (delay warmup / caught
// up / flushed by a barge-in). Pulling is the playback hand-off: the
// frame is stamped into the echo-reference queue at this moment.
//
// # Safety
//
// `duplex` must be a live duplex handle owned by the calling thread;
// `out_pcm` must point to `capacity` writable floats; `out_len` must be
// valid and writable.
enum vokra_status_t vokra_s2s_pull_audio(struct vokra_s2s_duplex_t *duplex,
                                         float *out_pcm,
                                         size_t capacity,
                                         size_t *out_len);

// Copies the inner monologue accumulated so far (Moshi's self-generated
// transcript, display-rule filtered) into `buf` as NUL-terminated UTF-8.
//
// `*out_needed` always receives the byte length **including** the NUL;
// when `buf` is `NULL` or `buf_len` is too small, nothing is written and
// the call still returns `VOKRA_OK` — size with a first call, then
// fetch (the standard two-call string discipline).
//
// # Safety
//
// `duplex` must be a live duplex handle owned by the calling thread;
// `buf` must be `NULL` or `buf_len` writable bytes; `out_needed` valid
// and writable.
enum vokra_status_t vokra_s2s_text(const struct vokra_s2s_duplex_t *duplex,
                                   char *buf,
                                   size_t buf_len,
                                   size_t *out_needed);

// Creates a cross-thread barge-in handle for `duplex` (module docs —
// safe to fire from another thread while this one pushes/pulls).
//
// # Safety
//
// `duplex` must be a live duplex handle; `out_interrupt` valid and
// writable.
enum vokra_status_t vokra_s2s_interrupt_handle(const struct vokra_s2s_duplex_t *duplex,
                                               struct vokra_s2s_interrupt_t **out_interrupt);

// Requests barge-in (M3-14 semantics): the session flushes pending model
// output and resets its generation state at the next push/pull boundary;
// mic intake continues. Callable from any thread (the handle owns its
// own atomic flag — module docs).
//
// # Safety
//
// `interrupt` must be a live interrupt handle (not yet destroyed).
enum vokra_status_t vokra_s2s_interrupt(const struct vokra_s2s_interrupt_t *interrupt);

// Frees a barge-in handle. `NULL` is a no-op; double-free is undefined
// behaviour.
//
// # Safety
//
// `interrupt` must be `NULL` or a handle from
// `vokra_s2s_interrupt_handle` not already freed.
void vokra_s2s_interrupt_destroy(struct vokra_s2s_interrupt_t *interrupt);

// Frees a duplex session. `NULL` is a no-op; double-free is undefined
// behaviour. Outstanding interrupt handles stay valid (they only own an
// atomic flag) but firing them after destroy has no observer.
//
// # Safety
//
// `duplex` must be `NULL` or a handle from `vokra_s2s_duplex_open` not
// already freed.
void vokra_s2s_duplex_destroy(struct vokra_s2s_duplex_t *duplex);

// Copies the model's attribution text (FR-MD-09 — weights whose license
// requires display, e.g. Moshi / Mimi CC-BY 4.0) into `buf` as
// NUL-terminated UTF-8, with the two-call sizing discipline of
// `vokra_s2s_text`.
//
// `*out_needed == 0` (and nothing written) means the loaded model's
// weights carry **no** display obligation (permissive licenses) — an
// attribution-required weight always yields a non-empty text (the
// runtime falls back to a registry-derived string when the GGUF chunk is
// absent; M4-06-T23).
//
// # Safety
//
// `session` must be a live session handle; `buf` must be `NULL` or
// `buf_len` writable bytes; `out_needed` valid and writable.
enum vokra_status_t vokra_model_attribution(const struct vokra_session_t *session,
                                            char *buf,
                                            size_t buf_len,
                                            size_t *out_needed);

// Loads a model from a GGUF file and creates an inference session on the CPU
// backend (FR-API-01).
//
// The architecture is detected from the GGUF's `vokra.model.arch` metadata and
// the matching native engine is injected: `whisper` → ASR, `silero-vad` → VAD,
// `piper-plus-mb-istft-vits2` → TTS. ONNX is never loaded (FR-LD-05).
//
// # Parameters
//
// - `path_utf8`: NUL-terminated UTF-8 path to the `.gguf` model file.
// - `out_session`: on `VOKRA_OK`, receives a new session handle to be freed
//   with `vokra_session_destroy`. Untouched on error.
//
// # Returns
//
// `VOKRA_OK`, or a non-zero status with the detail available from
// `vokra_last_error()` (missing file, unparsable GGUF, unknown arch, ...).
//
// # Safety
//
// `path_utf8` must be a valid NUL-terminated C string and `out_session` a
// valid, writable `vokra_session_t*` location.
enum vokra_status_t vokra_session_create_from_file(const char *path_utf8,
                                                   struct vokra_session_t **out_session);

// Retains the session, producing an independent handle that shares the same
// loaded model via an atomic ref count (FR-API-03).
//
// This is the C ABI atomic ref count: it clones the inner `Session` (a cheap
// atomic `Arc` bump), so the model is freed only when the last handle is passed
// to `vokra_session_destroy`. The new handle is safe to move to another thread
// (`Session` is `Send + Sync`).
//
// # Parameters
//
// - `session`: an existing session handle to retain.
// - `out_session`: on `VOKRA_OK`, receives a new handle to be freed with
//   `vokra_session_destroy`. Untouched on error.
//
// # Safety
//
// `session` must be a valid session handle and `out_session` a writable
// `vokra_session_t*` location.
enum vokra_status_t vokra_session_retain(const struct vokra_session_t *session,
                                         struct vokra_session_t **out_session);

// Frees a session handle from `vokra_session_create_from_file` /
// `vokra_session_retain`. `NULL` is a no-op; using the handle after this call
// is undefined behaviour. The model is freed when the last handle is destroyed.
//
// # Safety
//
// `session` must be `NULL` or a handle from `vokra_session_create_from_file`
// or `vokra_session_retain` that has not already been destroyed.
void vokra_session_destroy(struct vokra_session_t *session);

// Returns the Vokra runtime version as a static NUL-terminated UTF-8 string
// (the `vokra-capi` crate version). The pointer is static — never free it.
const char *vokra_version(void);

// Opens a VAD stream over a session (FR-API-01 / FR-ST-02).
//
// # Parameters
//
// - `session`: a session created from a Silero VAD GGUF.
// - `sample_rate`: the stream sample rate in Hz (Silero accepts 8000 or
//   16000; other rates are rejected by the first `vokra_stream_push_pcm`).
// - `out_stream`: on `VOKRA_OK`, receives a stream handle freed with
//   `vokra_stream_destroy`. The stream retains the session, so it keeps the
//   model alive even after `vokra_session_destroy`.
//
// Returns `VOKRA_ERROR_NOT_IMPLEMENTED` if the session's model is not a VAD
// model (no VAD engine was injected).
//
// # Safety
//
// `session` must be a valid session handle and `out_stream` a writable
// `vokra_stream_t*` location.
enum vokra_status_t vokra_stream_open(const struct vokra_session_t *session,
                                      int32_t sample_rate,
                                      struct vokra_stream_t **out_stream);

// Pushes mono `f32` PCM into a VAD stream (FR-API-01). Each completed frame's
// event is enqueued on the stream's ring; drain them with `vokra_stream_poll`
// or `vokra_stream_poll_events`. A trailing partial frame is held internally.
//
// # Safety
//
// `stream` must be a valid stream handle and `pcm` valid for `num_samples`
// reads (or `NULL` when `num_samples == 0`).
enum vokra_status_t vokra_stream_push_pcm(struct vokra_stream_t *stream,
                                          const float *pcm,
                                          size_t num_samples);

// Drains up to `capacity` buffered speech probabilities into `out_probs`
// (FR-API-01). Non-blocking: writes `*out_count` = number written (0 if none
// pending). `out_probs` may be `NULL` only when `capacity == 0`.
//
// # Safety
//
// `stream` must be a valid stream handle, `out_probs` valid for `capacity`
// writes (or `NULL` when `capacity == 0`), and `out_count` a writable
// `size_t` location.
enum vokra_status_t vokra_stream_poll(struct vokra_stream_t *stream,
                                      float *out_probs,
                                      size_t capacity,
                                      size_t *out_count);

// Drains up to `capacity` typed events into `out_events` (M1-08). Non-blocking:
// writes `*out_count` = number written. `out_events` may be `NULL` only when
// `capacity == 0`. This is the generalized poll; `vokra_stream_poll` is the
// f32-probability fast path over the same ring.
//
// # Safety
//
// `stream` must be a valid stream handle, `out_events` valid for `capacity`
// writes (or `NULL` when `capacity == 0`), and `out_count` a writable
// `size_t` location.
enum vokra_status_t vokra_stream_poll_events(struct vokra_stream_t *stream,
                                             struct vokra_event_t *out_events,
                                             size_t capacity,
                                             size_t *out_count);

// Barge-in: flushes the current chunk output, drains the stream's ring
// (when the consumer half is still on this stream), resets the stepper's
// hidden state, and clears the barge-in flag — all synchronously, so the
// next `vokra_stream_push_pcm` is accepted in a clean state (M3-14 /
// FR-ST-03).
//
// This is the C-ABI counterpart of [`Stream::interrupt`](vokra_core::Stream::interrupt).
// A bare (no-stepper) stream is a documented no-op that still returns
// `VOKRA_OK`.
//
// # Thread safety
//
// `vokra_stream_interrupt` takes exclusive access to the stream handle for
// the duration of the call (mirroring the `&mut self` receiver on the Rust
// API). A C caller that shares one `vokra_stream_t*` across threads MUST
// serialise access — the underlying barge-in flag is lock-free, but the
// handler mutates the ring and stepper state. For cross-thread barge-in
// without ownership of the stream, hold the stream on one thread and drive
// interrupts through a Rust-side [`InterruptHandle`](vokra_core::InterruptHandle);
// a dedicated C ABI for the cross-thread handle is a follow-on (M3-16 v0.9
// ABI changelog).
//
// # Safety
//
// `stream` must be a valid stream handle from `vokra_stream_open` and must
// not be aliased on another thread for the duration of the call.
enum vokra_status_t vokra_stream_interrupt(struct vokra_stream_t *stream);

// Frees a stream handle from `vokra_stream_open`. `NULL` is a no-op.
//
// # Safety
//
// `stream` must be `NULL` or a handle from `vokra_stream_open` not already
// destroyed.
void vokra_stream_destroy(struct vokra_stream_t *stream);

// Synthesizes speech PCM from UTF-8 text using the session's TTS engine
// (FR-API-01, piper-plus native path).
//
// # Parameters
//
// - `session`: a session created from a piper-plus voice GGUF.
// - `text_utf8`: NUL-terminated UTF-8 text to synthesize.
// - `out_pcm`: on `VOKRA_OK`, receives a Vokra-owned mono `f32` buffer (values
//   in `[-1, 1]`) to be freed with `vokra_audio_free(*out_pcm, *out_num_samples)`.
// - `out_num_samples`: receives the sample count of `*out_pcm`.
// - `out_sample_rate`: receives the output sample rate in Hz.
//
// All three out-params are written only on `VOKRA_OK`.
//
// # Safety
//
// `session` must be a valid session handle, `text_utf8` a valid C string, and
// the three out-pointers writable locations of the matching type.
enum vokra_status_t vokra_tts_synthesize(const struct vokra_session_t *session,
                                         const char *text_utf8,
                                         float **out_pcm,
                                         size_t *out_num_samples,
                                         int32_t *out_sample_rate);

// Frees a PCM buffer returned by `vokra_tts_synthesize`. Pass the pointer and
// the sample count from the same call. `NULL` is a no-op; double-free is
// undefined behaviour.
//
// # Safety
//
// `pcm` must be `NULL`, or the `*out_pcm` from a `vokra_tts_synthesize` call
// with the matching `num_samples`, not already freed.
void vokra_audio_free(float *pcm, size_t num_samples);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VOKRA_H */
