#!/usr/bin/env python3
"""Dump FSQ codec family reference fixtures — WavTokenizer / X-Codec 2 /
NanoCodec Group-FSQ (M4-16 T10/T11 + #45).

This is an **offline** tool (FR-LD-05: no Python / PyTorch is ever pulled
into the runtime). It writes the committed fixtures under
``tests/parity/fsq/{wavtokenizer,xcodec2,nanocodec}/`` that the Rust parity test
(``crates/vokra-ops/tests/parity_fsq_codec.rs``) compares against
(NFR-QL-01 design-wide FP32 ``atol = 0.01``; the measured per-fixture gaps
are far tighter — recorded in each manifest). CI never runs Python — the
fixtures are committed (kaldi_fbank / M4-04 RVQ precedent).

The WavTokenizer / X-Codec 2 fixtures remain synthetic fixed-seed fixtures.
The NanoCodec fixture is generated by restoring NVIDIA's pinned real
checkpoint and calling its upstream NeMo quantizer object; the op itself has
no learned codebook weights. Follows the ``mimi_dump.py`` (M4-04 §D-j)
manifest / writer conventions and stays separate from RVQ (FR-OP-31 vs
FR-OP-30).

Subcommands
-----------

``wavtokenizer``
    Reference = ``torch.nn.functional.embedding(codes, table)`` — the
    **verbatim call** WavTokenizer's decode reduces to
    (``encoder/quantization/core_vq.py``: ``EuclideanCodebook.dequantize =
    F.embedding(embed_ind, self.embed)``; released configs are
    ``num_quantizers: 1`` with an Identity ``project_out``, so the n_q=1
    residual loop is a single gather — ADR M4-16 §D-c). The upstream repo
    is not pip-packaged, so the fixture drives the exact torch API rather
    than an installed package; the manifest records this honestly.

    - ``codebook_table_sliced.f32`` — ``[rows, d_model]`` seeded
      ``torch.randn`` table (sliced vs the released 4096 × 512; a gather is
      complete op semantics as long as codes < rows).
    - ``codes.u32`` — ``[time]`` fixed-seed codes in ``[0, rows)``
      (single codebook — one code per timestep, FSQ-family layout).
    - ``decoded_features.f32`` — ``[time, d_model]`` reference gather.
    - ``manifest.txt`` — shapes / seed / sha256 / versions / honest notes.

``xcodec2``
    Reference = ``vector_quantize_pytorch.ResidualFSQ`` at the **exact
    xcodec2==0.1.5 pin (vector-quantize-pytorch==1.17.8)** driven through
    the same public API ``modeling_xcodec2.py::decode_code`` calls:
    ``ResidualFSQ(dim=d_model, levels=[4]*8, num_quantizers=1)
    .get_output_from_indices(indices)`` with a seeded random
    ``project_out`` Linear. The **levels tuple is the real [4; 8]**
    (effective vocab 4^8 = 65536 — FR-OP-31's "65k+"); only ``d_model`` is
    sliced (64 vs the released 2048) to keep the fixture small.

    - ``levels.u32`` — the levels tuple (machine-checked by the Rust test
      so a drifted regeneration cannot silently change the attrs).
    - ``out_proj_weight.f32`` — ``[d_model, n_dims]`` row-major (torch
      ``nn.Linear.weight`` layout ``[out, in]``, dumped verbatim).
    - ``out_proj_bias.f32`` — ``[d_model]``.
    - ``codes.u32`` — ``[time]`` fixed-seed codes in ``[0, 65536)``
      (guaranteed to reach the top quartile so the high mixed-radix dims
      are exercised).
    - ``decoded_features.f32`` — ``[time, d_model]`` reference decode.
    - ``manifest.txt``.

    ``--oracle numpy`` replaces the torch reference with a numpy float32
    transcription of the pinned formula (basis cumprod → per-dim level →
    ``(l - half)/half`` → ``W @ code + b``) for environments without the
    pins; the manifest records which oracle generated the fixture
    (fabricated pass 禁止 — the committed fixture uses the real pin).

``nanocodec``
    Reference = the actual
    ``nemo.collections.tts.modules.audio_codec_modules.GroupFiniteScalarQuantizer``
    restored from NVIDIA's pinned 0.6 kbps NanoCodec ``.nemo`` checkpoint.
    The checkpoint supplies the real runtime group count and registered
    ``num_levels`` buffers. Fixed deterministic indices (including 0 and the
    top valid code 4031) are driven through the upstream public ``decode``
    method. Missing NeMo, a wrong source commit, a checkpoint hash mismatch,
    or a different quantizer class aborts loudly; there is no fallback oracle.

    - ``levels_per_group.u32`` — checkpoint levels ``[9, 8, 8, 7]``.
    - ``codes_time_group.u32`` — row-major ``[time, n_groups]`` indices.
    - ``decoded_features.f32`` — upstream ``[B,D,T]`` output transposed to
      row-major ``[time, n_groups * dims_per_group]``.
    - ``manifest.txt`` — checkpoint/source hashes, versions and shapes.

Fixture filenames deliberately use ``.f32`` / ``.u32`` / ``.txt`` only —
never the weight extensions ``.safetensors/.gguf/.pth/.bin`` — so the
compliance scanners stay inert on them (asserted by the Rust test).

Usage
-----

::

    uv run --python 3.12 --project tools/parity python tools/parity/fsq_dump.py wavtokenizer \\
        --out tests/parity/fsq/wavtokenizer --seed 0 --time 32 --rows 256 --d-model 64

    uv run --python 3.12 --project tools/parity python tools/parity/fsq_dump.py xcodec2 \\
        --out tests/parity/fsq/xcodec2 --seed 0 --time 32 --d-model 64

    uv run --python 3.12 --project tools/parity/nanocodec \\
        python tools/parity/fsq_dump.py nanocodec \\
        --checkpoint /path/to/nemo-nano-codec-22khz-0.6kbps-12.5fps.nemo \\
        --nemo-source-root /path/to/NVIDIA-NeMo-Speech \\
        --out tests/parity/fsq/nanocodec --time 16
"""

from __future__ import annotations

import argparse
import hashlib
import inspect
import subprocess
from pathlib import Path

# The released X-Codec 2 levels tuple — vq/codec_decoder_vocos.py
# `ResidualFSQ(dim=vq_dim, levels=[4, 4, 4, 4, 4,4,4,4], num_quantizers=1)`
# (ADR M4-16 §D-c; verified 2026-07-15).
XCODEC2_LEVELS = [4, 4, 4, 4, 4, 4, 4, 4]

NANOCODEC_REPO = "nvidia/nemo-nano-codec-22khz-0.6kbps-12.5fps"
NANOCODEC_REPO_COMMIT = "5c8e22ed763c14d81337fbe6ca74062f3d10f7e5"
NANOCODEC_CHECKPOINT_SHA256 = "bd5883099d0c74ceda760b6b7a1600b86da4d8a02531c9c282679951dcb08870"
NEMO_SPEECH_COMMIT = "4fcff72febec9395fdbd4bfa0747bfda2ecd3cef"
NANOCODEC_GROUPS = 4
NANOCODEC_LEVELS = [9, 8, 8, 7]


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_f32(path: Path, arr) -> None:
    import numpy as np

    np.ascontiguousarray(arr, dtype=np.float32).astype("<f4").tofile(path)


def _write_u32(path: Path, arr) -> None:
    import numpy as np

    np.ascontiguousarray(arr, dtype=np.uint32).astype("<u4").tofile(path)


def _versions() -> str:
    import numpy as np

    parts = [f"numpy=={np.__version__}"]
    try:
        import torch

        parts.append(f"torch=={torch.__version__}")
    except ImportError:
        parts.append("torch==(absent)")
    try:
        from importlib.metadata import version

        parts.append(f"vector-quantize-pytorch=={version('vector-quantize-pytorch')}")
    except Exception:  # noqa: BLE001 — best-effort version report
        parts.append("vector-quantize-pytorch==(absent)")
    return " ".join(parts)


def _manifest(out_dir: Path, lines: list[str], files: list[str]) -> None:
    for name in files:
        lines.append(f"sha256 {name} {_sha256(out_dir / name)}")
    (out_dir / "manifest.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


# ---------------------------------------------------------------------------
# wavtokenizer — single-codebook gather reference
# ---------------------------------------------------------------------------


def dump_wavtokenizer(args: argparse.Namespace) -> None:
    import numpy as np

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(args.seed)
    table = rng.standard_normal((args.rows, args.d_model)).astype(np.float32)
    codes = rng.integers(0, args.rows, size=(args.time,), dtype=np.uint32)
    # Pin the boundary rows so the extreme indices are always exercised.
    codes[0] = 0
    codes[-1] = args.rows - 1

    if args.oracle == "torch":
        import torch

        decoded = (
            torch.nn.functional.embedding(
                torch.from_numpy(codes.astype(np.int64)), torch.from_numpy(table)
            )
            .numpy()
            .astype(np.float32)
        )
        oracle_note = (
            "reference: torch.nn.functional.embedding — the verbatim call in WavTokenizer "
            "encoder/quantization/core_vq.py EuclideanCodebook.dequantize (n_q=1, "
            "project_out=Identity; upstream repo is not pip-packaged so the exact torch API "
            "is driven directly)"
        )
    else:
        decoded = table[codes.astype(np.int64)]
        oracle_note = (
            "reference: numpy float32 gather (--oracle numpy fallback; formula-equivalent "
            "to torch F.embedding — regenerate with the torch oracle before committing)"
        )

    _write_f32(out_dir / "codebook_table_sliced.f32", table)
    _write_u32(out_dir / "codes.u32", codes)
    _write_f32(out_dir / "decoded_features.f32", decoded)

    _manifest(
        out_dir,
        [
            "M4-16 T10 WavTokenizer VQ reference fixture (SYNTHETIC weights)",
            oracle_note,
            f"versions: {_versions()}",
            "canonical released shape: vocab_size=4096 (vq_bins), d_model=512 (dimension) "
            "— fixture is sliced (gather semantics complete for codes < rows); "
            "num_quantizers=1 per released configs (ADR M4-16 §D-c)",
            "weights: NONE downloaded / used — table is seeded standard_normal "
            "(real-checkpoint parity = flip-the-switch, model-integration WP)",
            f"fixture shapes: codebook_table_sliced [({args.rows}, {args.d_model})]; "
            f"codes [({args.time},)] u32; decoded_features [({args.time}, {args.d_model})]",
            f"seed: {args.seed}; codes in [0, {args.rows}) with boundary rows pinned",
        ],
        ["codebook_table_sliced.f32", "codes.u32", "decoded_features.f32"],
    )


# ---------------------------------------------------------------------------
# xcodec2 — FSQ dequant + out-projection reference (pin 1.17.8)
# ---------------------------------------------------------------------------


def _numpy_fsq_reference(codes, levels, weight, bias):
    """Numpy float32 transcription of the pinned 1.17.8 decode formula
    (finite_scalar_quantization.py `indices_to_level_indices` +
    `_scale_and_shift_inverse`; residual_fsq.py `get_output_from_indices`
    with num_quantizers=1 → scale=(L−1)^0=1 → project_out)."""
    import numpy as np

    time = codes.shape[0]
    n_dims = len(levels)
    grid = np.zeros((time, n_dims), dtype=np.float32)
    for t in range(time):
        rem = int(codes[t])
        for d, level in enumerate(levels):
            level_index = rem % level
            rem //= level
            half = level // 2
            grid[t, d] = np.float32(level_index - half) / np.float32(half)
    return (grid @ weight.T + bias).astype(np.float32)


def dump_xcodec2(args: argparse.Namespace) -> None:
    import numpy as np

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    levels = list(XCODEC2_LEVELS)
    n_dims = len(levels)
    vocab = 1
    for level in levels:
        vocab *= level

    rng = np.random.default_rng(args.seed)
    weight = rng.standard_normal((args.d_model, n_dims)).astype(np.float32)
    bias = rng.standard_normal((args.d_model,)).astype(np.float32)
    codes = rng.integers(0, vocab, size=(args.time,), dtype=np.uint32)
    # Pin the boundary codes so index 0 and the top of the 65536 range are
    # always exercised (the Rust test asserts the top quartile is reached).
    codes[0] = 0
    codes[-1] = vocab - 1

    if args.oracle == "torch":
        import torch
        from vector_quantize_pytorch import ResidualFSQ

        quantizer = ResidualFSQ(dim=args.d_model, levels=levels, num_quantizers=1)
        with torch.no_grad():
            quantizer.project_out.weight.copy_(torch.from_numpy(weight))
            quantizer.project_out.bias.copy_(torch.from_numpy(bias))
        quantizer = quantizer.eval()
        # Same public API modeling_xcodec2.py::decode_code drives:
        # indices shaped [batch, time, num_quantizers].
        indices = torch.from_numpy(codes.astype(np.int64)).reshape(1, args.time, 1)
        with torch.no_grad():
            decoded = quantizer.get_output_from_indices(indices)
        decoded = decoded.squeeze(0).numpy().astype(np.float32)
        oracle_note = (
            "reference: vector_quantize_pytorch.ResidualFSQ.get_output_from_indices — the "
            "exact module + public API modeling_xcodec2.py::decode_code calls, at the "
            "xcodec2==0.1.5 pin vector-quantize-pytorch==1.17.8 (MIT reference CODE; "
            "project_out weights are seeded synthetic)"
        )
    else:
        decoded = _numpy_fsq_reference(codes, levels, weight, bias)
        oracle_note = (
            "reference: numpy float32 transcription of the pinned 1.17.8 formula "
            "(--oracle numpy fallback — regenerate with the torch oracle before committing)"
        )

    _write_u32(out_dir / "levels.u32", np.asarray(levels, dtype=np.uint32))
    _write_f32(out_dir / "out_proj_weight.f32", weight)
    _write_f32(out_dir / "out_proj_bias.f32", bias)
    _write_u32(out_dir / "codes.u32", codes)
    _write_f32(out_dir / "decoded_features.f32", decoded)

    _manifest(
        out_dir,
        [
            "M4-16 T11 X-Codec 2 FSQ reference fixture (SYNTHETIC projection)",
            oracle_note,
            f"versions: {_versions()}",
            f"levels tuple: {levels} (the released X-Codec 2 value — "
            f"vq/codec_decoder_vocos.py; effective vocab = {vocab})",
            f"canonical released d_model: 2048 (vq_dim default) — fixture slices d_model "
            f"to {args.d_model}; the levels axis is NOT sliced",
            "weights: NONE downloaded / used — project_out is seeded standard_normal "
            "(real-checkpoint parity = flip-the-switch, model-integration WP)",
            f"fixture shapes: out_proj_weight [({args.d_model}, {n_dims})] (nn.Linear "
            f"[out, in] row-major); out_proj_bias [({args.d_model},)]; "
            f"codes [({args.time},)] u32 in [0, {vocab}) with boundary codes pinned; "
            f"decoded_features [({args.time}, {args.d_model})]",
            f"seed: {args.seed}",
        ],
        [
            "levels.u32",
            "out_proj_weight.f32",
            "out_proj_bias.f32",
            "codes.u32",
            "decoded_features.f32",
        ],
    )


# ---------------------------------------------------------------------------
# NanoCodec — real-checkpoint GroupFiniteScalarQuantizer reference
# ---------------------------------------------------------------------------


def _git_head(repo: Path) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    return proc.stdout.strip()


def dump_nanocodec(args: argparse.Namespace) -> None:
    import numpy as np
    import torch

    try:
        import nemo
        from nemo.collections.tts.models import AudioCodecModel
        from nemo.collections.tts.modules.audio_codec_modules import GroupFiniteScalarQuantizer
    except ImportError as exc:
        raise SystemExit(
            "nanocodec oracle requires pinned NVIDIA-NeMo/Speech; run through "
            "`uv run --python 3.12 --project tools/parity/nanocodec ...` with no "
            "fallback"
        ) from exc

    checkpoint = Path(args.checkpoint).resolve()
    if not checkpoint.is_file():
        raise SystemExit(f"checkpoint not found: {checkpoint}")
    checkpoint_sha = _sha256(checkpoint)
    if checkpoint_sha != NANOCODEC_CHECKPOINT_SHA256:
        raise SystemExit(
            f"checkpoint sha256 mismatch: got {checkpoint_sha}, "
            f"expected {NANOCODEC_CHECKPOINT_SHA256}"
        )

    source_root = Path(args.nemo_source_root).resolve()
    source_head = _git_head(source_root)
    if source_head != NEMO_SPEECH_COMMIT:
        raise SystemExit(
            f"NVIDIA-NeMo/Speech checkout is {source_head}, expected {NEMO_SPEECH_COMMIT}"
        )
    oracle_source = Path(inspect.getsourcefile(GroupFiniteScalarQuantizer) or "").resolve()
    if not oracle_source.is_relative_to(source_root):
        raise SystemExit(
            f"imported GroupFiniteScalarQuantizer from {oracle_source}, outside pinned "
            f"source root {source_root}; refusing an unverified oracle"
        )

    model = AudioCodecModel.restore_from(restore_path=str(checkpoint), map_location="cpu").eval()
    quantizer = model.vector_quantizer
    if not isinstance(quantizer, GroupFiniteScalarQuantizer):
        raise SystemExit(
            f"checkpoint vector_quantizer is {type(quantizer).__module__}."
            f"{type(quantizer).__name__}, expected GroupFiniteScalarQuantizer"
        )

    n_groups = int(quantizer.num_groups)
    levels_by_group = []
    for group, fsq in enumerate(quantizer.fsqs):
        levels = [int(x) for x in fsq.num_levels.detach().cpu().reshape(-1).tolist()]
        if not levels:
            raise SystemExit(f"checkpoint group {group} has an empty num_levels buffer")
        levels_by_group.append(levels)
    if n_groups != NANOCODEC_GROUPS or len(levels_by_group) != n_groups:
        raise SystemExit(
            f"checkpoint n_groups={n_groups}, fsqs={len(levels_by_group)}; expected "
            f"{NANOCODEC_GROUPS}"
        )
    if any(levels != NANOCODEC_LEVELS for levels in levels_by_group):
        raise SystemExit(
            f"checkpoint levels_by_group={levels_by_group}; expected every group to use "
            f"{NANOCODEC_LEVELS}"
        )

    vocab = int(quantizer.codebook_size)
    expected_vocab = int(np.prod(np.asarray(NANOCODEC_LEVELS, dtype=np.int64)))
    if vocab != expected_vocab:
        raise SystemExit(f"checkpoint codebook_size={vocab}, expected {expected_vocab}")

    time = args.time
    if time < 2:
        raise SystemExit("--time must be >= 2 so both codebook boundaries are exercised")
    codes = np.empty((time, n_groups), dtype=np.uint32)
    for t in range(time):
        for group in range(n_groups):
            codes[t, group] = (t * 7919 + group * 104729 + t * group * 17) % vocab
    codes[0, 0] = 0
    codes[-1, -1] = vocab - 1

    # NeMo public decode contract: [group, batch, time] -> [batch, feature, time].
    indices = torch.from_numpy(codes.T.astype(np.int64, copy=True)).unsqueeze(1)
    input_len = torch.tensor([time], dtype=torch.int64)
    with torch.no_grad():
        decoded = quantizer.decode(indices=indices, input_len=input_len)
    expected_shape = (1, n_groups * len(NANOCODEC_LEVELS), time)
    if tuple(decoded.shape) != expected_shape:
        raise SystemExit(
            f"unexpected NeMo decode shape {tuple(decoded.shape)}, expected {expected_shape}"
        )
    decoded_time_major = decoded.squeeze(0).transpose(0, 1).contiguous().cpu().numpy()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    _write_u32(out_dir / "levels_per_group.u32", np.asarray(NANOCODEC_LEVELS, dtype=np.uint32))
    _write_u32(out_dir / "codes_time_group.u32", codes)
    _write_f32(out_dir / "decoded_features.f32", decoded_time_major)

    _manifest(
        out_dir,
        [
            "#45 NanoCodec Group-FSQ reference fixture",
            f"model repo: {NANOCODEC_REPO}",
            f"repo commit: {NANOCODEC_REPO_COMMIT}",
            f"checkpoint sha256: {checkpoint_sha}",
            f"checkpoint bytes: {checkpoint.stat().st_size}",
            f"NVIDIA-NeMo/Speech commit: {source_head}",
            f"oracle source sha256: {_sha256(oracle_source)}",
            "oracle class: nemo.collections.tts.modules.audio_codec_modules."
            "GroupFiniteScalarQuantizer",
            "oracle call: checkpoint.vector_quantizer.decode(indices=[G,B,T], input_len=[B])",
            "fixture kind: real checkpoint-loaded quantizer; deterministic synthetic indices",
            f"versions: nemo-toolkit=={nemo.__version__} torch=={torch.__version__} "
            f"numpy=={np.__version__}",
            f"checkpoint shape: n_groups={n_groups}; levels_per_group={NANOCODEC_LEVELS}; "
            f"codebook_size={vocab}; embed_dim={n_groups * len(NANOCODEC_LEVELS)}",
            f"fixture shapes: codes_time_group=({time}, {n_groups}); "
            f"decoded_features=({time}, {n_groups * len(NANOCODEC_LEVELS)})",
            "indices: deterministic integer formula with code 0 and codebook_size-1 pinned; "
            "no learned or synthetic codebook weights (FSQ grid is implicit)",
        ],
        ["levels_per_group.u32", "codes_time_group.u32", "decoded_features.f32"],
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    wt = sub.add_parser("wavtokenizer", help="WavTokenizer single-codebook VQ fixture")
    wt.add_argument("--out", required=True)
    wt.add_argument("--seed", type=int, default=0)
    wt.add_argument("--time", type=int, default=32)
    wt.add_argument("--rows", type=int, default=256)
    wt.add_argument("--d-model", type=int, default=64)
    wt.add_argument("--oracle", choices=["torch", "numpy"], default="torch")
    wt.set_defaults(func=dump_wavtokenizer)

    xc = sub.add_parser("xcodec2", help="X-Codec 2 FSQ dequant fixture")
    xc.add_argument("--out", required=True)
    xc.add_argument("--seed", type=int, default=0)
    xc.add_argument("--time", type=int, default=32)
    xc.add_argument("--d-model", type=int, default=64)
    xc.add_argument("--oracle", choices=["torch", "numpy"], default="torch")
    xc.set_defaults(func=dump_xcodec2)

    nc = sub.add_parser("nanocodec", help="NanoCodec real-checkpoint grouped FSQ fixture")
    nc.add_argument("--checkpoint", required=True)
    nc.add_argument("--nemo-source-root", required=True)
    nc.add_argument("--out", required=True)
    nc.add_argument("--time", type=int, default=16)
    nc.set_defaults(func=dump_nanocodec)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
